deploy/obc/storage_class.yaml, pkg/crd/crd.go, pkg/operator/operator.go
* added storage class creation on operator installation
* storage-class name is in the format `NAMESPACE-storage-class`
* provisioner name is aligned with the name in `provisioner.go` - `noobaa.io/NAMESPACE.bucket`
=> deploy a default storage class when deploying a system

Makefile, deploy/internal/service-mgmt.yaml
1. 8080 -> 80
2. 8443 -> 443
3. Managent service will not serve S3 anymore
=> Change the serving ports of the management service

.gitignore, deploy/cluster_role.yaml, pkg/operator/operator.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go, pkg/system/system.go
* creating default storage class for a system when reconciling the system 
* removed storage-class creation on operator installation from the CLI
* fixed `mongo-image` flag that was ignored by `noobaa` CLI
* gitignore additions
=> reconile storage-class in system reconcile + other fixes

cmd/manager/main.go, main.go, pkg/bundle/bundle.go, pkg/crd/crd.go, pkg/obc/provisioner.go, pkg/olm/olm.go, pkg/operator/manager.go, pkg/operator/operator.go, pkg/options/options.go, pkg/system/system.go, pkg/util/fastmapper.go, pkg/util/util.go, test/cli/cli_test.go
1. fixing error handling issues, if by panic or by ignore
2. fixing G304: Potential file inclusion via variable by using filepath.Clean in bundle.go
3. NOSEC in cli-test file so gosec will disregard it
still fails on two types of errors:
1. not verifying certificate: G402: TLS InsecureSkipVerify set true - need to be fixed with a valid certificate
2. G101: Potential hardcoded credentials -  in the build output - seems like we need gosec to skip the build/_output directory when running
=> fixing most gosec issues

deploy/internal/ceph-objectstore-user.yaml, deploy/role.yaml, go.mod, go.sum, pkg/bundle/deploy.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go, pkg/util/util.go
* When not in AWS try to create a `CephObjectstoreUser` to use as a default backing store
* This is still commented out until OCS issue is resolved (https://github.com/openshift/ocs-operator/issues/191)
=> use RGW as default backing store when not in AWS (disabled)

pkg/system/phase4_configuring.go, pkg/util/util.go
* removed calls to `panic` from `GetAWSRegion` in `util.go`. returns error instead
* on errors - generate an event and use `us-east-1` as default 
* Fixes #90
=> use us-east-1 as the default aws region when failing to parse from node name

pkg/backingstore/reconciler.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go
* when not running in AWS, trying to create a default backing store on RGW if available
* listing `CephObjectstore` resources in the same namespace, and using the first one that is found as a target S3 compatible resource
* In backingstore reconciler added support to RGW naming convention for access\secret keys (camel case)
=> fixed default rgw backing store flow

pkg/nb/api.go, pkg/obc/provisioner.go
* when OBC is deleted the provisioned bucket should be deleted with all of its data
* Fixes #110
=> call DeleteBucketAndObjects on OBC provisioner delete

deploy/internal/route-mgmt.yaml, deploy/internal/route-s3.yaml, deploy/internal/service-mgmt.yaml, deploy/internal/service-s3.yaml, deploy/internal/statefulset-core.yaml, deploy/role.yaml, go.mod, go.sum, pkg/bundle/deploy.go, pkg/system/phase2_creating.go, pkg/system/phase3_connecting.go, pkg/system/reconciler.go, pkg/util/util.go
- Generate a secret holding a certificate for each service (using OpenShift serving cert mechanism)
- Mount the secrets as folders in the noobaa-core pod (to be used by the core  for TLS communication)
- Create a secure route for each service the serve using the ingress operator cert and re-encrypt using the cert generated for each service.
=> Create of secure OpenShift routes for NooBaa services (mgmt/s3)- OpenShift only

deploy/auth_delegator_cluster_role_binding.yaml, deploy/internal/statefulset-core.yaml, deploy/service_account.yaml, pkg/bundle/deploy.go, pkg/operator/operator.go, pkg/system/phase2_creating.go, pkg/system/reconciler.go, pkg/util/util.go
- Discover OAuth2 endpoints using the .wellknown auth endpint and relay them to noobaa-core via env vars
- Relay noobaa service account to noobaa-core pod via env variable
- CLI: Add missing service account annotaion and cluster role binding (to system:auth-delegator)
=> Add OAuth2 support

pkg/system/phase2_creating.go
* if an older version of noobaa service-account (one without `Annotations`) exists on the cluster, it causes the operator to crash when trying to assign to the `Annotations` map
* ensuring `Annotations` map existence before assignment.
=> fixed operator panic - ensure annotations map exist on service account

deploy/internal/statefulset-core.yaml, deploy/operator.yaml, doc/backing-store-crd.md, pkg/bundle/deploy.go
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1768409
=> Use default imagePullPolicy to force pull latest tags

doc/bucket-class-crd.md
Clarifying that spread and mirror is case sensitive
=> Additional changes to the docs

pkg/system/phase4_configuring.go
Invalid OwnerReferences can lead to the other children of the owner
being garbage collected. Ref [1][1].
The OBCStorageClass is a non-namespaced (global) resource, which has
OwnerReference set to the NooBaa resource which is a namespaced
resource. This is an invalid OwnerReference.
[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1691546
=> Remove OwnerReferences on OBCStorageClass

go.mod, go.sum, pkg/apis/noobaa/v1alpha1/zz_generated.openapi.go, pkg/options/options.go, pkg/system/phase1_verifying.go, pkg/system/reconciler.go
By default, version constraint checks will fail on the prerelease version if the constraint does not exactly match the version. Trimming the prerelease part solves this problem
=> Trim the prerelease part from the version

pkg/olm/olm.go
* OCP UI crashed when encountered tolerations in noobaa cr
* removed tolerations descriptor from OLM to prevent crash
* fixed wrong descriptor for `imagePullSecret`
=> olm.go GenerateCSV fixes 

deploy/internal/deployment-endpoint.yaml, pkg/bundle/deploy.go, pkg/system/phase4_configuring.go
Using the NooBaa CRD UID because it is always present and unique for each NooBaa.
=> Expose endpoint group Id to the endpoint pods

pkg/backingstore/backingstore.go, pkg/backingstore/reconciler.go, pkg/nb/api.go, pkg/nb/types.go, pkg/obc/obc.go, pkg/obc/provisioner.go, pkg/options/options.go, pkg/pvstore/pvstore.go, pkg/system/phase4_configuring.go, pkg/system/system.go, pkg/util/util.go, test/cli/test_cli_flow.sh, test/cli/test_cli_functions.sh
Fixes for the following issues, some of them not fully:
https://bugzilla.redhat.com/show_bug.cgi?id=1781287 - added handling of Invalid names to KubeCreateSkipExisting instead of just panicing 
https://bugzilla.redhat.com/show_bug.cgi?id=1779732 - added Delete support for pvstore as well as handling special cased of pool being used by buckets/account
https://bugzilla.redhat.com/show_bug.cgi?id=1777295 - added to the CLI special handling of pools being used by buckets/account - it will still hang on deleting directly from kubernetes api, 
we need to think what to do in order to provide better feedback for that kind of failed deletions
=> Fixing BZ issues - 1781287 and 1779732

pkg/system/phase1_verifying.go, pkg/system/phase2_creating.go, test/cli/test_cli_functions.sh
Supporting the following issue from noobaa-operator side:
https://github.com/openshift/ocs-operator/issues/372
it will now get the images (both core and db) in the following order:
1. from the spec - if exists
2. from the env variables - if exists
3. default value in options.go file
=> Add support for images from env variable

README.md, pkg/bundle/deploy.go, pkg/olm/olm.go, pkg/options/options.go, version/version.go
* removed tolerations descriptor in olm.go
* updated noobaa version in operator `options.go` to 5.2.13
* bumped operator version to 2.0.10
Fixes BZ 1785267
=> Backport: olm.go tolerations descriptor fix

go.mod, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go
* fixes https://bugzilla.redhat.com/show_bug.cgi?id=1768382
* changed target bucket name to be of the format `nb.[timestamp milliseconds].[route host name]`
* if the generated name length is longer than 63 it is truncated to 63 (max bucket name length)
=> changed deafult backing store target to be more descriptive

deploy/crds/noobaa.io_noobaas_crd.yaml, deploy/internal/deployment-endpoint.yaml, deploy/internal/service-mgmt.yaml, deploy/internal/service-s3.yaml, go.sum, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, pkg/bundle/deploy.go, pkg/options/options.go, pkg/system/phase1_verifying.go, pkg/system/phase2_creating.go, pkg/system/phase3_connecting.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go, pkg/util/util.go
Currently, we mainly deploy an S3 service and an auto-scaled endpoint group
Changes:
- Create an auth_token secret to be used by endpoints
- Introduce a join secret to hold information on how to join an existing NooBaa cluster
- Add a join secret reference on the NooBaa CRD to indicate that the deployed NooBaa should join an existing cluster using the join information specified in the referenced secret
=> Support deployment of a joined NooBaa on a remote cluster 

pkg/system/phase4_configuring.go
Registering the NooBaa client should not occur when deploying using a join secret
=> System reconcile -  add conditional check before registering to cluster

build/catalog-source.Dockerfile
* fixes to `make gen-olm` failures
* in `quay.io/operator-framework/upstream-registry-builder` the location of `/build/bin/initializer` was changed to `/bin/initializer`
* as a result `registry-server` was also created in `/bin` instead of `/build/bin`
* fixed the paths to make the docker build pass
* also set the base image to a fixed version `quay.io/operator-framework/upstream-registry-builder:v1.5.7`
=> set fixed version for base image in catalog-source.Dockerfile (v1.5.7) and fixed paths

pkg/system/phase4_configuring.go, pkg/util/util.go
fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1796570
* if truncated bucket name ends with a dash then remove it.
* validate generated bucket name and fall back to a simple name (nb + timestamp)
=> validate generated bucket name for backing store targer

deploy/internal/statefulset-db.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go, pkg/util/util.go
Fixes #223 
* required for getting Guaranteed QoS class
* when setting resources requests and limits for all containers in a pod (including init containers), the pod is assigned a `Guaranteed` QoS class
=> set resources requests & limits for db init-container

pkg/nb/router.go, pkg/system/phase3_connecting.go, pkg/system/system.go
* when connecting through the node port, it is possible that there is no connection between different nodes in the cluster using the node ports (e.g. firewall)
* instead of the node port, using the mgmt service DNS name `noobaa-mgmt.[namespace].svc.cluster.local`
=> changed RPC client in the operator to connect using the management service DNS name

pkg/system/phase4_configuring.go
The endpoint pod will fail to pull the image if it's in a private docker registry. Therefore we need to specify the image pull secrets the same way we do in the other deployments
=> The endpoint pod should use the secrets as well

README.md, deploy/internal/service-db.yaml, deploy/internal/service-mgmt.yaml, deploy/internal/service-s3.yaml, pkg/bundle/deploy.go
Also, generate a serving cert for the new database service (This will not force the DB pod to use the cert in any way)
fixes #117
=> Adding support for serving certs for OCP3

pkg/diagnose/diagnose.go, pkg/nb/rpc.go, pkg/system/reconciler.go, pkg/util/util.go
1. Instead of creating http.Client  in every call to util.DiscoverOAuthEndpoints() - Moved the http.Client creation to phase2_creating and passed the same client as argument. 
2. Called res.Body.Close() when it's empty.
1. Fixed BZ #1799077
1.
=> Fix OOMKilled problem

pkg/backingstore/backingstore.go
Will now verify that storageclass exist, and that it's not an obc only type:
```
$ nb backingstore create pv-pool pool1 --num-volumes 3 --pv-size-gb 16 --storage-class jacky.noobaa
INFO[0000] ✅ Exists: NooBaa "noobaa"
INFO[0000] ❌ Not Found: StorageClass "jacky.noobaa"
FATA[0000] ❌ Could not get StorageClass "jacky.noobaa" for system in namespace "jacky"
$ nb backingstore create pv-pool pool1 --num-volumes 3 --pv-size-gb 16 --storage-class jacky.noobaa.io
INFO[0000] ✅ Exists: NooBaa "noobaa"
INFO[0000] ✅ Exists: StorageClass "jacky.noobaa.io"
FATA[0000] ❌ Could not set StorageClass "jacky.noobaa.io" for system in namespace "jacky" - as this class reserved for obc only
```
=> fixing BZ1820297

.travis.yml, README.md, pkg/bundle/deploy.go, pkg/options/options.go, version/version.go
Bump version to 2.3.0
(cherry picked from commit 3d806c3bf12e969c65f705a4baee1257a98b9468)
.travis.yml:
- Added || exit 1 on all scripts calls
(cherry picked from commit ec02220f8543d4d277083280891ab75974c8723a)
=> Backport Version change and travis for into 2.3

.travis/install-minikube.sh
- Update minikube version to 1.8.2
- Update kubernetes version to 1.17.3
- Installing conntrack
- Added MINIKUBE_DEBUG="--alsologtostderr --v=5" commented out by default
- removed the "--extra-config=apiserver.authorization-mode=RBAC" flag as it no longer needed in kubernetes 1.17 and up
=> Updating minikube version

test/cli/test_cli_flow.sh
test_cli_flow.sh:
- Increasing default timeout to avoid rapid timeouts failures
=> Increasing test_cli_flow.sh default timeout

pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/obc/provisioner.go, pkg/system/reconciler.go, pkg/util/util.go
1. Added support for graceful uninstall.
2. Added a check in system reconcile  - if  the system has deletionTimestamp and if graceful_finalizer exist and num of object buckets == 0, remove the graceful_finalizer. else, return error.
3. Added a check in Provision and Grant - if the system has deletionTimestamp and it has graceful_finalizer - return error.
1. need to create a PR for ocs-operator that adds graceful_finalizer to noobaa.
1.
=> Added graceful uninstall support 

pkg/backingstore/reconciler.go
Not allowing to create PV Pools with more than 20 agents.
Fixed: https://bugzilla.redhat.com/show_bug.cgi?id=1835636
=> Max num volumes PV pool fix

deploy/internal/deployment-endpoint.yaml, deploy/internal/pod-agent.yaml, deploy/internal/statefulset-core.yaml, pkg/backingstore/reconciler.go, pkg/bundle/deploy.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/util/util.go
When running in a proxied environment the HTTP_PROXY, HTTPS_PROXY, and NO_PROXY environment variables control which of a pod's outgoing traffic is directed to a proxy and which not.
When cluster-wide proxy setting is used OLM update the operator's env variables to the proper values. In turn, the operator should set the environment variables on the resources that it is responsible for.
This PR update the operator to read the values of the HTTP* environment variables set on the operator container and set them for the `noobaa-core` statefulset and `nobaa-endpoint` deployments
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1819549
Edit: 
We have a gap where changes to the env vars will not be reconciled for pv pool agent pods.
This is because a pod spec cannot be changed and we need …
=> Reconcile noobaa pods HTTP* envs based on operator pod HTTP* envs

pkg/obc/provisioner.go, pkg/system/reconciler.go
Some places uses the string literal where it could have used the
constant. This lets all places use the constant.
Follow-up from reviewing PR #309 
Signed-off-by: Michael Adam <obnox@redhat.com>
=> Use the GracefulFinalizer constant

Makefile, build/empty-kubeconfig
`make cli` runs `openshift-sdk run ...` which requires a kubeconfig.
Up to now, this target relied on minikube being started.
This modifies `devenv.sh` to generate an empty kubeconfig file and set the
KUBECONFIG variable to avoid failure if minikube is not running.
Fixes: #325
Signed-off-by: Michael Adam <obnox@redhat.com>
=> Don't require minikube for building.

deploy/crds/noobaa.io_backingstores_crd.yaml, pkg/apis/noobaa/v1alpha1/backingstore_types.go, pkg/backingstore/reconciler.go, pkg/bundle/deploy.go
1. Added creation of secret when creating a pv pool backingstore if it doesn't exist already.
2. Deleted the secret requirement from the crd
Fixing BZ #1846219
=> Added creation of a secret of PVpool  if it doesn't exist already

pkg/backingstore/reconciler.go, pkg/system/phase4_configuring.go
1. Added a check if 2 minutes passed from the creation of the system in reconcile default backingstore at the part when there is still no default backingstore and still no credentials.
2. If the check returned true, created a secret for the pv-pool and set values of r.DefaultBackingStore
=> Added pvpool as default backingstore after 2 minutes if it does not exist

pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go
This is a workaround for missing cephObjectStore in independent mode.
=> Get an RGW endpoint address from a label, as a fallback to non-existent CephObjectStore

pkg/install/install.go, pkg/system/system.go, test/cli/test_cli_functions.sh
1. Added cleanup_data flag for uninstall. From now on every uninstallation of noobaa will require the user to cleanup his OBs/OBCs by him self / use the new cleanup_data flag that will remove forcefully all his OBs/OBCs.
2. Added use_graceful_finalizer flag for install. by default, noobaa will have graceful_finalizer, by using the use_graceful_flag=false, the finalizer will be removed.
=> Added to NooBaa CLI new install and uninstall flags

pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go
RGW endpoint label will be base64 instead of a regular string to avoid this:
```
Error while reconciling: NooBaa.noobaa.io "noobaa" is invalid: metadata.labels:
Invalid value: "10.70.56.202:8080": a valid label must be an empty string or
consist of alphanumeric characters, '-', '_' or '.', and must start and end with an
alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for
validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```
OCS operator side is in https://github.com/openshift/ocs-operator/pull/580
=> rgw-endpoint label will be changed to a base-64 one

pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go
Base64 padding char `=` cannot be used in a k8s label.
So we dropped base64 encoding in favor of a simple replacement for the host-port separator char `:`
=> Replace RGW endpoint label encoding (base64) with a simple ":" to "_" encoding

pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go
… encoding
Base64 padding char `=` cannot be used in a label.
So we dropped base64 encoding in favor of a simple replace for the host-port seperator char `:`
(cherry picked from commit 28ae9752f6091588e43a1a58f3c89a12a779e229)
=> Backport to 2.3

deploy/internal/ceph-objectstore-user.yaml, pkg/bundle/deploy.go
For some reason kubeclient.Get will not remove/empty keys that do not exists in the CR instance. (which make it act a little bit like merge)
For this reason, in the case where our code creates the ChepObjectStoreUser with an empty store name (independent mode), the next reconcile will refill the value from the template (the value will be STORE_NAME)
Removing the value from the template will fix the issue
=> Remove the default value of spec.store from ChepObjectStoreUser template

deploy/internal/ceph-objectstore-user.yaml, pkg/bundle/deploy.go
For some reason kubeclient.Get will not remove/empty keys that do not exists in the CR instance. (which make it act a little bit like merge)
For this reason, in the case where our code creates the ChepObjectStoreUser with an empty store name (independent mode), the next reconcile will refill the value from the template (the value will be STORE_NAME)
Removing the value from the template will fix the issue
(cherry picked from commit f82f64415c6d24344272479848f17b397d564771)
=> Backport to 2.3: Remove default value from spec.store from ChepObjectStoreUser template

deploy/crds/noobaa.io_v1alpha1_backingstore_cr.yaml, deploy/crds/noobaa.io_v1alpha1_bucketclass_cr.yaml, deploy/crds/noobaa.io_v1alpha1_noobaa_cr.yaml, pkg/backingstore/reconciler.go, pkg/bucketclass/reconciler.go, pkg/bundle/deploy.go, pkg/system/reconciler.go, pkg/util/util.go
The `BackingStore` object sent to `KubeCheck` at the start of the backing store reconcile loop is already filled with a finalizer and label (loaded from the backing store cr template). This means that even in the case where the k8s resource has no finalizers or labels, the in-memory object will contain values for those fields. 
This prevents the operator from adding a finalizer at the start of the reconcile loop (because the operator believes that a finalizer is already present on the backing store).
This PR removed any meta info from the template and adds it back in code after checking that the loaded backing store is missing some or all of the desired meta fields.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1858385
=> Remove app label and finalizer from CR templates and add them in code

pkg/controller/backingstore/backingstore_controller.go, pkg/controller/bucketclass/bucketclass_controller.go, pkg/controller/noobaa/noobaa_controller.go, pkg/operator/manager.go, pkg/util/predicates.go
Also, remove manager SyncPeriod time dev code left by accident in the code
This PR solves the infinite reconcile problem we have in the operator. 
The main reason for the problem is that the operator is watching resources (`NooBaa`, `BackingStore`, `BucketClass`) that it is also responsible for updating,  specifically writing the status of each of these resources on every reconcile cycle.
The fix is to filter the events the reconcile reacts to. Allowing only meaningful changes to passthrough  
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1849309
=> Add predicates to filter out non-relevant events and log relevant events

pkg/options/options.go
Bumped core image to 5.6.0-20200802
=> Bumped core image to 5.6.0-20200802

pkg/options/options.go
Bumped core image to 5.6.0-20200802
(cherry picked from commit 4c9e41ed5dd420142bf3cb76242db2e7252985e4)
=> Backport into 5.6

deploy/crds/noobaa.io_noobaas_crd.yaml, deploy/internal/service-db.yaml, deploy/internal/statefulset-postgres-db.yaml, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/backingstore/reconciler.go, pkg/bundle/deploy.go, pkg/options/options.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go, pkg/system/system.go
- Added db-type flag that can get mongodb or postgres
- Adding statfulset postgres db
- Implemeting the db-type functionality, when using --db-type postgres the db to be installed is postgres
- In statfulset postgres db get the cradentials should be from a secret, currently is is hard coded defaults.
- In statfulset postgres db the mountPath is the same as mongo's
- ~We override NooBaaDB with the postgres yaml when we are calling db-type flag. probebly better way is to keep one NooBaaDB and instead of replacing it, assigned it with NooBaaMongoDB or NooBaaPostgresDB~ 
- noobaa-core is not connecting - as planned for this stage. 
- When using this flag it revokes the db-image flag and currently the postgres image is hard coded (in the options). 
- We might want to change also the …
=> Add db-type flag and the ability to install postgress using the CLI

deploy/internal/pod-agent.yaml, pkg/backingstore/reconciler.go, pkg/bundle/deploy.go
Few updates on how we handle the pods of the pv-pools:
- removed finalizers in order to not get the drain process getting stuck (during OCP upgrade) BZ1867762
- on spec changes in existing pods - check if the pods need to be deleted and then delete it and create a new one with the right spec - fix issue we had with changing the imagePullSecret BZ1868646
- fixing a known gap of ours #364 
=> Change pod delete handling for pvpool

deploy/internal/service-db.yaml, deploy/internal/statefulset-core.yaml, deploy/internal/statefulset-postgres-db.yaml, pkg/bundle/deploy.go, pkg/options/options.go, pkg/system/phase2_creating.go
* changed upstream postgres image to centos/postgresql-12-centos7
* DB service changes
* Pass postgres DB info as envs to noobaa-core
=> operator changes for postgres-db

pkg/backingstore/reconciler.go
when getting an `INVALID_ENDPOINT` error on `check_external_connection` keep requeueing for 5 minutes before returning persistent error
=> keep requeueing backing-store for 5 minutes if getting INVALID_ENDPOINT

pkg/backingstore/reconciler.go, pkg/nb/api.go, pkg/nb/types.go
fix for overlooking a missing AGENT_CONFIG in pvpool secret
recheck for agent_config in case it wasn't available
=> Fixes for issues with retrieving agent_config when the server has issues while creating a pvpool

pkg/options/options.go
Bump core image to 5.6.0-20200903
=> Bump core image

pkg/system/phase2_creating.go
Added checks for non existing dbType variable in the CR.
This is done in order to support previous CRs.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1876118
Signed-off-by: Evgeniy Belyi <jeniawhite92@gmail.com>
=> Fixing dbType from non supported CR

pkg/nb/types.go, pkg/obc/provisioner.go, pkg/options/options.go
adding support for bucket claim owner to the operator - create account will send the bucket claim owner flag
so the server can special handle the created account has a user that can change the bucket policy
operator side of core PR: https://github.com/noobaa/noobaa-core/pull/6069
=> Adding bucket_claim_owner to obc accounts

pkg/system/phase4_configuring.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1876520
* for default backing-stores on top of RGW, the endpoint was constructed from the ceph object-store name. The port that was used was hard-coded `80`
* when RGW is deployed externally (external mode) the endpoint port is different (`8080` in the BZ case). 
* the correct endpoint actually appears in the ceph user secret, so changed the flow to take the endpoint from there. the construction of the endpoint as before only happens as a fallback.
=> fixed wrong endpoint address when RGW is deployed externally

deploy/internal/service-mgmt.yaml, deploy/internal/service-s3.yaml, deploy/internal/servicemonitor-mgmt.yaml, deploy/internal/servicemonitor-s3.yaml, pkg/bundle/deploy.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go
For each pod behind the `noobaa-mgmt` service we will scrape 3 paths:
1. `/metrics/web_server` - nodejs `web_server` process report + nooba reports
2. `/metrics/bg_workers` - nodejs `bg_workers` process report
3. `/metrics/hosted_agents`- nodejs `hosted_agents` process report
For each pod behind the `s3` service we will scrape one paths (on port 7001):
1. `/` - nodejs `endpoint` report
=> Reconcile multiple service monitors with multiple scrape paths

pkg/install/install.go, pkg/system/system.go
CLI noobaa status and uninstall shows actual installed image:
- When there is a system CLI noobaa status will print the actual image that we used
- Add prints of the db image 
Fixes: #64 
=> CLI noobaa status and uninstall shows actual installed image

pkg/backingstore/reconciler.go
1. When getting a bad request Error from create_hosts_pool set the pv-pool phase to rejected.
2. Follow up to https://github.com/noobaa/noobaa-operator/pull/420
1. 
1.
=> Set pv-pool phase to rejected when getting insufficient pv size

deploy/internal/statefulset-db.yaml, pkg/bundle/deploy.go
This will give mongodb enough time to response to a TERMSIG, sent to the container, and shutdown gracefully, before being forcefuly killed using KILLSIG
=> Set noobaa-db pod's termination grace period to 1min (60sec)

pkg/options/options.go
- Bumped core image to 5.6.0-20201013
=> Bumped core image to 5.6.0-20201013

pkg/diagnose/diagnose.go
Changes: 
1. Created the diagnostics tar file directly to specified dir.
Problem: 
using the `nb diagnose --dir` didn't work as expected inside the must-gather pod.
Renaming the tar file to the wanted directory didn't work inside of the must-gather pod and raised an error that implies that the source directory and the target directory are not on the same file systems.
=> Created diagnostic tar file directly to the specified dir

deploy/internal/statefulset-core.yaml, deploy/internal/statefulset-postgres-db.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go, pkg/system/reconciler.go
1. Add secret for postgres creds: user/password
2. connect to both db sts and core sts so they can communicate
3. changed postgres user to noobaa - as postgres user insisted in creating the default db - postgres and not nbcore
4. fixed issues with labels and selectors - to enable db service to really work
=> Add secret for postgres creds

Makefile, build/catalog-source.Dockerfile, deploy/crds/noobaa.io_backingstores_crd.yaml, deploy/crds/noobaa.io_bucketclasses_crd.yaml, deploy/crds/noobaa.io_noobaas_crd.yaml, deploy/obc/objectbucket.io_objectbucketclaims_crd.yaml, deploy/obc/objectbucket.io_objectbuckets_crd.yaml, deploy/olm/noobaa-operator.clusterserviceversion.yaml, pkg/apis/noobaa/v1alpha1/bucketclass_types.go, pkg/bundle/deploy.go, pkg/crd/crd.go, pkg/olm/olm.go, pkg/util/util.go, test/test-olm.sh
* generating CRDs with `--crd-version v1` flag
* updated `crd.go` and `olm.go` to use `apiextensions/v1` module
*  `apiextensions.k8s.io/v1` was released in kubernetes v1.16 - updated `minKubeVersion` to 1.16.0
=> changed CRDs apiversion from apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1 (not beta1)

pkg/system/phase2_creating.go, pkg/system/reconciler.go, pkg/util/util.go
Added a new check on missing env variable and adding them if they appear in the yaml
Doing this only for core sts for now just for you guys to take a look - we can copy the logic to other yamls if we need to - for now tagged as WIP until we figure this out
=> Adding missing Env variables for core sts

pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go, pkg/util/util.go
Signed-off-by: Neeraj K Kashyap <nkashyap@in.ibm.com>
This PR enables the configuration of IBM COS as backing store for NooBaa in the IBM Cloud (IKS /ROKS).
Currently, Cloud Credential Operator is not supporting IBM Cloud creds. The code change assumes a secret `ibm-cloud-cos-creds`, under `kube-system`, will be created by Admin or by the IBM Cloud at the time of cluster creation
```
apiVersion: v1
kind: Secret
metadata:
name: ibm-cloud-cos-creds
namespace: kube-system
type: Opaque
data:
IBM_COS_ACCESS_KEY_ID: RlM2I4ODQ=
IBM_COS_SECRET_ACCESS_KEY: NjNjNmEzZTNk
```
The code change has been tested in IBM Cloud
```
$ oc get backingstore
NAME                           TYPE      PHASE   AGE
noobaa-default-backing-store   ibm-cos   Ready   23m
```
=> In IBM Cloud configure IBM COS as default backing store

pkg/system/system.go
Changing the default DBType to mongodb for US
=> Changing the default DBType to mongodb

pkg/backingstore/backingstore.go
Due to the pv-pool suffix names being changed - possible name is now shorter to fit to linux max allowed length of 63 chars
=> fixing pvpool bs name limit to 43 chars instead of 47

pkg/system/system.go
Fixing CLI when using postgres as DB
- Fixes: BZ #1909488
=> Fixing CLI when using postgres as DB

pkg/system/system.go
Fixing CLI when using postgres as DB
- Fixes: BZ #1909488
(cherry picked from commit b0036cbb724228922d100ef467d2f7a9f56d78ea)
=> Backport to 5.7: Fixing CLI when using postgres as DB

pkg/system/phase2_creating.go
Old sts use to have value before moving to valueFrom - old Value needs to be deleted, otherwise pods can't start
Fix to BZ1915698
=> Fixing upgrade issue with old STS values

pkg/options/options.go
Bumped core image to 5.7.0-20210113
=> Bumped core image to 5.7.0-20210113

pkg/options/options.go
Backport into 5.7: Bumped core image to 5.7.0-20210113
=> Backport into 5.7: Bumped core image to 5.7.0-20210113

pkg/backingstore/reconciler.go
=> Rejecting too long pv-pool backingstore names

pkg/nb/rpc.go, pkg/nb/rpc_ws.go
Fixing BZ1915261
it seems we didn't timeout RPC calls which led to a hanging requests which hold the whole reconcile flow. limiting now to 2 minutes like we do in the server.
=> Adding timeout to RPC calls

pkg/system/phase2_creating.go, pkg/util/util.go
use a different arn prefix (`arn:aws-us-gov`) for credentials request when running in AWS GovCloud.
Fixes #535 
Fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1925533
=> fixed default backing store creation in aws GovCloud

pkg/install/install.go
When running status and the system is not ready, we will not print an empty "System Status"
We will wait for "System Phase is Ready",  and then we will then print the System Status.
Have a working noobaa and do:
1. Run `kubectl edit noobaa noobaa`
2. Edit the image and replace it with a new core image 
3. Wait for the system to go down, then run `noobaa status` using the CLI.
=> CLI | Wait for System Phase is "Ready" on status

deploy/crds/noobaa.io_noobaas_crd.yaml, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/bundle/deploy.go, pkg/options/options.go, pkg/system/phase1_verifying.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go, pkg/system/system.go
- Adding mongodb-url flag that can change the URL of mongo, enabling to connect to a remote mongodb
- Skipping create of db pod when given an external db URL
Expecting URL to start with:  `mongodb://` or `mongodb+srv://`
Fixes: #304
=> Adding mongodb-url flag that can change the url of mongo, enabling to connect to a remote mongodb

pkg/diagnose/diagnose.go
Changed noobaa diagnostics dir time format to epoch
Fixes: BZ #1928451
=> Changed noobaa diagnostics dir time format to epoch

pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go, pkg/util/util.go
Signed-off-by: Ambika Nair <ambiknai@in.ibm.com>
This PR enables to use pv-pool for default backing store in IBM Cloud if COS cred secret is missing
=> In IBM Cloud if COS cred secret is missing use pv-pool for default backing store

.github/workflows/run_ci.yml
- Divide unit test into 2 jobs in order to reduce ~45% of the run time.
=> [GH Action] Divide Unit Test Into 2 Jobs

pkg/options/options.go
Bumped core image to 5.7.0-20210304
=> Bumped core image to 5.7.0-20210304

pkg/options/options.go
Bumped core image to 5.7.0-20210304
(cherry picked from commit 6217b5296abbd1c50e7ac21f25e2aa6a6c4f2d3a)
=> Backport to 5.7: Bumped core image to 5.7.0-20210304

pkg/controller/noobaa/noobaa_controller.go
Fix BZ1935262
Printing only part of the RPCMessage like in following example
```time="2021-03-07T13:02:54Z" level=info msg="RPC Handle: {Op: req, API: server_inter_process_api, Method: load_system_store, Error: <nil>, Params: map[since:1.615122174279e+12]}"```
=> removing auth_token print

pkg/system/phase2_creating.go
Fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1922113
* when we upgrade ocs-operator to 4.7, we apply changes to noobaa SCC from ocs-operator. these changes cause noobaa-db pod to restart
* The SCC changes require some new code to run in noobaa init container, but when noobaa-db-0 starts it is still using the old noobaa-core image as the init container.
* Since the new code is missing, the init container is getting into a crash loop
* Once OCS operator updates the noobaa CR with the new noobaa core image, noobaa-operator updates the noobaa-db STS. For some reason, when the init container is in a crash loop, this update does not cause the pod to restart with the new image (not sure if it's a Statefulset bug or as designed. opened an …
=> delete the noobaa-db pod before starting migration process

deploy/role.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go
* setting `restartPolicy` to never will keep failed pods around so we can examine the failures
* setting `backoffLimit` to 4 (default is 6) to reduce the number of pods that can potentially stay in the NS
* one thing to notice is that failed runs will leave a pod (not running) with ERROR state. This can lead to support cases, but maybe these are cases we want to know about
related to BZ https://bugzilla.redhat.com/show_bug.cgi?id=1938557
=> setting upgrade job restartPolicy to never

deploy/role.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go
* setting to never will keep failed pods around so we can examine the failures
* set backoffLimit to 4 (default is 6) to reduce the number of pods that can potentially stay in the NS
* one thing to notice is that failed runs will leave a pod (not running) with ERROR state
(cherry picked from commit 5838aa641fa131b2994bee6da641f34e93503c69)
=> Backport to 5.7: setting upgrade job restartPolicy to never

pkg/system/phase2_creating.go
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1938557
* noobaa-core is reconciled before we start the migration process
* when changing DB type to postgres, the operator restart noobaa-core and postgres before the migration
* in some cases, noobaa-core starts before the migration starts and it creates a support account (here: https://github.com/noobaa/noobaa-core/blob/c40153e5e4389834ab597fef94ce60615cbeb18a/src/server/web_server.js#L66)
* changed the sequence to reconcile core after migration phase
=> moved core STS reconciliation to run after migration

pkg/system/phase2_creating.go
cherry picked from bbf07c11f64c0627fe1cac5de6ef5dbee0561e7b
=> backport to 5.7 - moved core STS reconciliation to run after migration

pkg/util/util.go
=> Fix for vault kms - when missing backend path field will use the default (secret/) 

pkg/options/options.go, pkg/system/phase2_creating.go
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1945450
* when reconciling mongo STS in migrate flow we no longer have the mong image stored in the spec (dbImage is used for postgres image).
* explicitly set the mongo image when reconciling mongo STS since in some cases the STS could have been reconciled with the posters image.
=> specify mongo db image when reconciling old mongo sts

deploy/internal/deployment-endpoint.yaml, deploy/role.yaml, deploy/role_binding_endpoint.yaml, deploy/role_endpoint.yaml, deploy/scc_endpoint.yaml, deploy/service_account_endpoint.yaml, pkg/bundle/deploy.go, pkg/olm/olm.go, pkg/operator/operator.go, pkg/system/phase4_configuring.go
Adding the needed caps for noobaa-endpoints deployment: set-uid and set-gid, as well as running as root
Also creating a new service account, role and rolebinding for noobaa-endpoints
Adding the use option to both roles for future use instead of the sccs' users list
=> Adding needed changes for NSFS for noobaa-endpoint deployment

pkg/system/phase2_creating.go
Upgrade of a cluster from 4.6 to 4.7.
The label was non-existant in the services and they weren't scrapped by Prometheus because of that.
=> Addition of labels to service reconcile after upgrade from last version

pkg/obc/provisioner.go
- let the library decide if deletion is necessary. 
- this is the expected behavior according to the [docs](https://github.com/kube-object-storage/lib-bucket-provisioner/blob/master/doc/design/object-bucket-lib.md#bucket-deletion)
- same behavior is implemented in [rook's provisioner](https://github.com/rook/rook/blob/a4277d29137ca35d9a98713c663dfa7c705799d4/pkg/operator/ceph/object/bucket/provisioner.go#L201-L214) 
- warn if ob has a ReclaimPolicy != Delete
- fixes https://bugzilla.redhat.com/show_bug.cgi?id=1947796
=> ignore ReclaimPolicy in provisioner Delete implementation

pkg/system/phase2_creating.go
- in some cases mongo service can be updated with wrong values when DBType is changed to postgres and the running operator version is 5.6
- fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1955328
=> reconciling mongo service if it exists regardless of DBType

pkg/system/phase2_creating.go
- in some cases mongo service can be updated with wrong values when DBType is changed to postgres and the running operator version is 5.6
- fixes BZ https://bugzilla.redhat.com/show_bug.cgi?id=1955328
(cherry picked from commit 3e43668cb4913f8b77418671456cf68d8a488d35)
=> Backport to 5.7

deploy/crds/noobaa.io_namespacestores_crd.yaml, pkg/apis/noobaa/v1alpha1/namespacestore_types.go, pkg/backingstore/reconciler.go, pkg/bucketclass/reconciler.go, pkg/bundle/deploy.go, pkg/namespacestore/namespacestore.go, pkg/namespacestore/reconciler.go, pkg/nb/api.go, pkg/nb/types.go, pkg/obc/obc.go, pkg/obc/provisioner.go, pkg/options/options.go
1. in nsfs namespacestore renamed fsPath to fsRootPath as the current core version.
2. renamed default_pool to default_resource as in the current core version.
3. in namespacestore deletion - iterate over all accounts - if account's default resource is the deleted namespacestore - put the internal pool as its default_resource (same behaviour as in backingstore) 
3. Added path option for namespace OBCs creation
** Need to build core and update here the image
=> NSFS path / default_reosurce changes in operator

pkg/obc/provisioner.go
- let the library decide if deletion is necessary.
- warn if ob has a ReclaimPolicy != Delete
(cherry picked from commit 0ca913eb48f1fdbc12e176d4b26a3a83c27e85fa)
=> backport to 5.6

deploy/crds/noobaa.io_namespacestores_crd.yaml, pkg/apis/noobaa/v1alpha1/namespacestore_types.go, pkg/bundle/deploy.go, pkg/namespacestore/namespacestore.go, pkg/namespacestore/reconciler.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go
1. cli command and nsstore CRD will now require pvc-name
2. will attach the new pvc to the endpoint pods if needed
3. option to create more than one mount to the same pvc with subPath option
4. removed fsRootPath - will create all the mounts under /nsfs/<namespace_store_name>
=> Auto PVC mount to endpoint deployment

pkg/options/options.go
Replacing the default DBType from mongo to postgres
This change is only relevant for the NooBaa CLI.
=> Replacing the default DBType from mongo to postgres

pkg/backingstore/backingstore.go, pkg/bucket/bucket.go, pkg/bucketclass/bucketclass.go, pkg/cli/cli.go, pkg/namespacestore/namespacestore.go, pkg/obc/obc.go, pkg/options/options.go, pkg/pvstore/pvstore.go
Issue #484
=========
Execute pre-run check and generate an error if there are elements in the command flag args list, 
which indicate wrong inputs options. The general rule is that all noobaa commands would generate
an error on non-flag arguments due to the PersistentPreRunE implementation at the root Cmd.
Children of the root command will inherit and execute PersistentPreRunE.
Defined a shared Pass function at options, i.e. this implementation never returns
an error for the commands that require non-flag argument, such as for instance
-> noobaa bucket create <bucket-name> [flags] [options]...
Those commands should define their PersistentPreRunE as Pass function.
Tests:
====
Rejecting non-flag arguments
------------------------------
```
➜  noobaa install …
```
=> Generate an error if a user wrongly inputs options with –

go.mod, go.sum
- Update golang.org/x/net using `go get golang.org/x/net` to avoid CVE
No noticeable Breaking changes
- Fixes BZ1966753
- Fixes BZ1966749
=> 5.8: Update golang.org/x/net

deploy/crds/noobaa.io_noobaas_crd.yaml, deploy/internal/deployment-endpoint.yaml, deploy/internal/statefulset-core.yaml, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/bundle/deploy.go, pkg/options/options.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/system.go
- Add NOOBAA_LOG_LEVEL as env variable in deployment-endpoint.yaml and statefulset-core.yaml and into noobaa CR
- Adding the debug-level flag to the options
- Add the debug-level flag functionality in the install command
- Need to add a CLI command that changes the NOOBAA_LOG_LEVEL in noobaa CR for running clusters
- Run `noobaa install --debug-level <number>` and see that the appropriate logs are being printed
=> Add the debug-level flag functionality as install option

deploy/internal/configmap-postgres-db.yaml, deploy/internal/statefulset-postgres-db.yaml, pkg/backingstore/backingstore.go, pkg/backingstore/reconciler.go, pkg/bucketclass/bucketclass.go, pkg/bundle/deploy.go, pkg/namespacestore/namespacestore.go, pkg/obc/obc.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go, pkg/util/util.go
Issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1946792
Test:
Verify in the postgress DB container:
- existence and content of `/opt/app-root/src/postgresql-cfg/noobaa-postgres.conf` file:
```
bash-4.2$ pwd
/opt/app-root/src
bash-4.2$ cat postgresql-cfg/noobaa-postgres.conf
huge_pages = off
```
- `openshift-custom-postgresql.conf` includes the
`noobaa-postgres.conf` file
```
bash-4.2$ grep noobaa-postgres /var/lib/pgsql/openshift-custom-postgresql.conf
include '/opt/app-root/src/postgresql-cfg/noobaa-postgres.conf'
```
=> Disable huge_pages in Postgres config

deploy/internal/configmap-postgres-db.yaml, deploy/internal/statefulset-postgres-db.yaml, pkg/backingstore/backingstore.go, pkg/backingstore/reconciler.go, pkg/bucketclass/bucketclass.go, pkg/bundle/deploy.go, pkg/namespacestore/namespacestore.go, pkg/obc/obc.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go, pkg/util/util.go
Issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1946792
Test:
Verify in the postgress DB container in two scenarios, (a) clean
install and (b) operator upgrade:
- existence and content of /opt/app-root/src/postgresql-cfg/noobaa-postgres.conf file:
bash-4.2$ pwd
/opt/app-root/src
bash-4.2$ cat postgresql-cfg/noobaa-postgres.conf
huge_pages = off
- openshift-custom-postgresql.conf includes the noobaa-postgres.conf file
bash-4.2$ grep noobaa-postgres /var/lib/pgsql/openshift-custom-postgresql.conf
include '/opt/app-root/src/postgresql-cfg/noobaa-postgres.conf'
Verify the postgres DB is up and running with huge pages enabled in
kernel.
(cherry picked from commit 462a265ddf238fc334e60937c45355845cf73ce3)
=> Backport to 5.8 - Disable huge_pages in Postgres config

pkg/system/reconciler.go
- Checking Service "noobaa-db" status only if we use mongo
Fixes: BZ1974573
=> Checking Service "noobaa-db" status only if we use mongo

pkg/bucket/bucket.go
Namespace buckets don't have the capabilities to show the number of objects and sizing.
New output for namespace buckets:
```
Bucket status:
Bucket                 : my-ns-bucket
Type                   : NAMESPACE
Mode                   : OPTIMAL
Num Objects            : N/A
Data Size              : N/A
Data Size Reduced      : N/A
Data Space Avail       : N/A
```
Fixes https://github.com/noobaa/noobaa-operator/issues/671
=> show N/A instead of 0, for namespace buckets

deploy/cluster_role.yaml, pkg/bundle/deploy.go, pkg/system/reconciler.go, pkg/system/system.go, pkg/util/util.go
1. deletes OBC storageclass on CLI uninstall/system delete or regular deletion of noobaa CR.
2. Fixed #631
=> Delete OBC storage class on delete system

deploy/internal/configmap-postgres-db.yaml, deploy/internal/statefulset-postgres-db.yaml, pkg/bundle/deploy.go
* changed postgres default cpu request\limit to match OCS settings
* added postgres tuning settings to postgres configmap
* This is an initial tuning to settings. generated from here: https://pgtune.leopard.in.ua/#/
* added shared_preload_libraries = 'pg_stat_statements' to postgres conf
* at first I wasn't sure if it's a good idea to add it to the PR. saw some (old) blog posts that it shouldn't have a huge impact on performance ([e.g.](http://pgsnaga.blogspot.com/2011/10/performance-impact-of-pgstatstatements.html)) so I think for now it's better to have it in
=> postgres performance improvements

deploy/internal/configmap-postgres-db.yaml, deploy/internal/statefulset-postgres-db.yaml, pkg/bundle/deploy.go
* changed postgres default cpu request\limit to match OCS settings
* added postgres tuning settings to postgres configmap
* This is an initial tuning to settings. generated from here: https://pgtune.leopard.in.ua/#/
* added shared_preload_libraries = 'pg_stat_statements' to postgres conf
* at first I wasn't sure if it's a good idea to add it to the PR. saw some (old) blog posts that it shouldn't have a huge impact on performance ([e.g.](http://pgsnaga.blogspot.com/2011/10/performance-impact-of-pgstatstatements.html)) so I think for now it's better to have it in
(cherry picked from commit 892bb2598981b2b7d80d13b0a055f45cdf30d5fc)
=> [Backport to 5.8] - postgres performance improvements

pkg/namespacestore/namespacestore.go, pkg/namespacestore/reconciler.go, pkg/namespacestore/validation.go, pkg/namespacestore/validation_test.go, pkg/system/phase4_configuring.go, test/cli/resources/nsfs-local-class.yaml, test/cli/resources/nsfs-local-pv.yaml, test/cli/resources/nsfs-local-pvc.yaml, test/cli/test_cli_functions.sh
Link to issue:  
https://github.com/noobaa/noobaa-operator/issues/677
1. Added validation to the namespacestore reconciler and noobaa cli
* Validate if Spec.NSFS.SubPath must be a relative path
* Validate if Spec.NSFS.SubPath must not contain '..'
* Validate if Spec.NSFS.PvcName must not be empty
2. Move all config validations from MakeExternalConnectionParams to the validator
3. Skip DesiredEndpointMounts when namespacestore is in rejected phase
4. Added the validator automation tests
Tests:
```
$noobaa namespacestore create nsfs fs1 --pvc-name='nsfs-vol' --fs-backend='GPFS' --sub-path='/'
INFO[0000] ✅ Exists: NooBaa "noobaa"
FATA[0000] ❌ SubPath / must be a relative path
Options:
--fs-backend='': The file system backend type - CEPH_FS | GPFS | NFSv4
--pvc-name='': The pvc name in which …
```
=> Added namespacestore validation

pkg/system/phase2_creating.go, pkg/system/system.go
since dbType is optional in our CRD it is sometimes omitted in the CR. if it is not supplied then try to infer it from the DB image so it will match
fix for https://bugzilla.redhat.com/show_bug.cgi?id=1969677
=> if dbtype is not provided try to infer it from the db image name

deploy/crds/noobaa.io_bucketclasses_crd.yaml, pkg/apis/noobaa/v1alpha1/bucketclass_types.go, pkg/bucketclass/bucketclass.go, pkg/bucketclass/reconciler.go, pkg/bundle/deploy.go, pkg/nb/api.go, pkg/nb/types.go, pkg/obc/obc.go, pkg/obc/provisioner.go, pkg/options/options.go, pkg/util/util.go
1. Added bucket replication to bucketclass create cli command (both namespace and placement bucketsclasses types)
2. Added to bucketclass CRD replication policy - it's a name of a config map with a  replicationPolicyJSON property which contains a json with a replication_policy root field.
3. Added to util a function which loads the json and is used in both bucketclass reconciler and in provisioner.
4. Added an rpc call to put_bucket_replication in provisioner (after creation of an obc).
5. Added an rpc call to update_bucket_class_replication in bucketclass reconciler.
1. 
1.  tests shouldn't pass until i'll update the core version
=> Bucket Replication - Operator side

pkg/install/install.go, test/cli/test_cli_functions.sh
Since executing unintall command with --cleanup flag removes all CRDs
and affecting all noobaa instances, a confirmation check is added in
order to inform the user and verify that the above is the intended
action.
Fixed: #689
Signed-off-by: Barak Sason Rofman <sason922@gmail.com>
=> Adding confirmation check for uninstall command

pkg/namespacestore/validation.go, pkg/system/phase4_configuring.go
Restrict the max number of characters, for namespaceStore name, to 63
```
$ build/_output/bin/noobaa-operator-local namespacestore create nsfs 1234567890123456789012345678901234567890123456789012345678901111 --fs-backend=GPFS --pvc-name='nsfs-vol'
INFO[0000] ✅ Exists: NooBaa "noobaa"
FATA[0000] ❌  MountPath /nsfs/1234567890123456789012345678901234567890123456789012345678901111 must be no more than 63 characters
Options:
--fs-backend='': The file system backend type - CEPH_FS | GPFS | NFSv4
--pvc-name='': The pvc name in which the file system resides
--sub-path='': The path to a sub directory inside the pvc file system
Usage:
noobaa namespacestore create nsfs <namespace-store-name> [flags] [options]
Use "noobaa options" for a list of global command-line options (applies to all commands). …
```
=> Restrict the max number of characters, for namespaceStore name, to 63

.github/workflows/run_hac_test.yml, .travis/install-5nodes-kind-cluster.sh, Makefile, doc/high-availability-controller.md, go.mod, go.sum, pkg/controller/add_hac.go, pkg/controller/ha/ha_controller.go, pkg/controller/ha/ha_suite_test.go, pkg/controller/ha/hac_test.go, pkg/hac/hac.go
Improve NooBaa pods recovery in case of a node failure. Find noobaa pods
running on the failing node and force delete them to speed up
rescheduling in healthy node.
=> NooBaa Component Rescheduling

pkg/obc/provisioner.go, pkg/system/phase4_configuring.go
* when creating a namespace bucket with OBC the provisioned created a dummy tiering policy with the default bucket class. this was to work around a bug in noobaa core where the internal resource was assigned to the bucket, but it doesn't exist in OCD DS.
* removed the tiering creation for namespace resource and fixed the issue in noobaa-core - https://github.com/noobaa/noobaa-core/pull/6663
fix for https://bugzilla.redhat.com/show_bug.cgi?id=1981331
=> removed tiering creation with default bucket class for namespace bucket

Makefile, build/gen-odf-package.sh, pkg/olm/olm.go, pkg/operator/operator.go
* added `gen-odf-package` make target to generate CSV and CRDs for ODF builds
* this target should be used with these required envs: 
```
csv-name=[csv yaml file name] core-image=[noobaa core image] operator-image=[noobaa operator image] db-image=[postgres db image]
```
* The files are generated under `build/_output/manifests`
=> added make target to generate CSV for ODF

deploy/crds/noobaa.io_noobaas_crd.yaml, deploy/internal/deployment-endpoint.yaml, deploy/internal/statefulset-core.yaml, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/bundle/deploy.go, pkg/controller/noobaa/noobaa_controller.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go, pkg/system/system.go, pkg/util/util.go, test/cli/test_cli_flow.sh, test/cli/test_cli_functions.sh
Signed-off-by: Kfir <kfirpayne@gmail.com>
related to https://github.com/noobaa/noobaa-operator/issues/426
1. Added `envFrom: configMapRef` and `annotations: ConfigMapMD5` to the core and endpoint deployment.
2. The `ConfigMapMD5` annotation referencing to an up-to-date hash of the data array of the `noobaa-config`.
3. Added validation on changes to the configmap, triggering a restart on the core and endpoint pods.
4. Reduced the time interval in the `wait.PollImmediateInfinite()` in the `util.KubeDelete()` to cope with the STS creating the core pod before the `wait.Poll` checking if the pod got deleted, reduced from 1 second to 10 milliseconds.
1. Decide which env vars from the endpoint we can move to the configmap.
1. Fixes #426
1.
=> Load env vars to noobaa core from config map

pkg/olm/olm.go
the wrong annotation was used before. 
these are the correct values: 
https://github.com/openshift/console/blob/22c6951efe7c4bca87f3f934063b9f4dcb0a4058/frontend/packages/operator-lifecycle-manager/src/const.ts#L22-L23
This will trigger the following behavior in the console: 
https://github.com/openshift/console/blob/71167b267da5907553a88f588b8f16b38cda5585/frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx#L81-L87
=> fixed annotation for hiding noobaa operator in OCP UI

Makefile, build/DockerfileDev
Added operator debugger target.
Operator runs from dlv and listens on port 40000 for debugger connection. 
In order to debug the operator process from vscode inside container, perform the following:
1.  Create operator dev image
```
make dev-image
```
2. Edit operator pod or Install noobaa with --operator-image=<dev-image>, for example
```
noobaa install --operator-image=noobaa/noobaa-operator-dev:5.9.0
```
Note the operator will not run and wait for debugger connection.
3. Configure port-forwarder to the operator
```
kubectl port-forward <operator pod> 40000:40000
```
4. Add launch configuration to vscode:
```
{
"name": "Connect to operator",
"type": "go",
"request": "attach",
"mode": "remote",
"remotePath": "${workspaceFolder}",
"port": 40000,
"host": "127.0.0.1"
},
```
5. Run the …
=> Added operator debugger

pkg/system/phase4_configuring.go
- Fixing an upgrade 5.8 to 4.9 flow where we are not setting the correct SCC to the endpoint.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1991256
=> Fixing an upgrade 5.8 to 4.9 flow where we are not setting the correct SCC to the endpoint.

deploy/role.yaml, pkg/bundle/deploy.go, pkg/system/phase4_configuring.go
- DeleteOldServiceMonitor updates the service monitor by removing the old format. This function should only be valid after upgrade from 5.6 to 5.7. it is here in 4.8 to avoid a situation where upgrading to 5.8 from a cluster that didn't went through  this code in 5.7 (upgraded to a 5.7 patch version that does not include this code)
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1989557
=> 5.8: Delete Old Service Monitor BZ 1989557

pkg/diagnose/diagnose.go
This patch changes the diagnose mechanism in the following ways:
1 - Executing diagnose will collect logs for pv-pool as well
2 - Instead of manually specifying for which pods logs should be
collected, logs are automatically collected for all pods (if in the
future additional pods will be added, logs will be collected for those
as well without requiring changes)
3 - The mechanism is enhanced internally, as prior to this changes
multiple listing of pods was being done, with this change only a single
listing is performed
4 - Some code cleaning is done as part of this change
Fixed: #260
Signed-off-by: Barak Sason Rofman <sason922@gmail.com>
=> Modifying diagnose mechanism

Makefile, build/install-operator-sdk.sh
As of now NooBaa Operator cannot compile on architectures different from AMD64 at the moment due to two reasons:
- `x86_64` being hardcoded in [install-operator-sdk.sh](https://github.com/noobaa/noobaa-operator/blob/master/build/install-operator-sdk.sh).
- `operator-framework/operator-registry` only providing AMD64 images.
Both of these issues cause an `exec format error`. 
This PR allows `install-operator-sdk.sh` to download the binary for the correct architecture when launching the build process and updates the `Makefile` to include building locally the `operator-registry` image. With these changes, the operator can successfully compile on different architectures, such as `aarch64`.
Note that the installation with `nb install` will still hang due to `nooba-core` not supporting other …
=> Support building noobaa-operator on ARM64 and other architectures

deploy/role.yaml, pkg/bundle/deploy.go, pkg/system/phase4_configuring.go
- DeleteOldServiceMonitor updates the service monitor by removing the old format. This function should only be valid after upgrade from 5.6 to 5.7
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1973179
=> 5.7: Delete the Old Service Monitor 

deploy/internal/configmap-postgres-db.yaml, deploy/internal/statefulset-postgres-db.yaml, pkg/bundle/deploy.go
changed postgres default cpu request\limit to match OCS settings
added postgres tuning settings to postgres configmap
these is an initial tuning to settings. generated here: https://pgtune.leopard.in.ua/#/
postgresql tuning
initial tuning of postgresql settings to try and reduce cpu consumption and increase performance.
this is a first attempt to tune postgres and we should definitely iterate on that. got these settings by using this conf generator https://pgtune.leopard.in.ua/#/
Revert "postgresql tuning"
This reverts commit ab741da3ee020e584ba02e1167feabf367597b99.
added shared_preload_libraries = 'pg_stat_statements' to postgres conf …
=> [backport to 5.7] postgres performance improvements

pkg/system/phase4_configuring.go
Seems to fix issue of x509: certificate signed by unknown authority
based on this:
https://community.ory.sh/t/problem-with-tls-certificate-signed-by-unknown-authority-using-hydra-client-go/2053
=> Adding timeout to RGW S3 https client

pkg/system/phase2_creating.go
- Cleaning the logs from mongodb errors when we have postgres.
Fixes:  https://bugzilla.redhat.com/show_bug.cgi?id=1973161
=> Cleaning the logs from mongodb errors when we have postgres.

pkg/cli/cli.go, pkg/dbdump/dbdump.go, pkg/diagnose/diagnose.go, test/cli/test_cli_flow.sh, test/cli/test_cli_functions.sh
Adding a CLI command to dump the db.
The db dump is implemented for both mongodb and postgrse  db.
Implementation differs between the db types, as each is executing the
dump itself in a different manner, however the resulting resource is a
tar file of the db dump.
The syntax is "noobaa db-dump".
To get a db dump while using the diagnose command, add the flag "--db-dump"
Fixed: #169
Signed-off-by: Barak Sason Rofman <sason922@gmail.com>
=> Adding DB dump functionality to the CLI

deploy/internal/configmap-postgres-initdb.yaml, deploy/internal/statefulset-db.yaml, deploy/internal/statefulset-postgres-db.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go, pkg/system/reconciler.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1946792
- Extract Postgres initialization into second init container
- During initialization wrap the Postgres binary, force huge_pages=off for initdb
=> initdb huge_pages

deploy/internal/configmap-postgres-initdb.yaml, deploy/internal/statefulset-db.yaml, deploy/internal/statefulset-postgres-db.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go, pkg/system/reconciler.go
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1946792
- Extract Postgres initialisation into second init container
- During initialization wrap the postgres binary, force huge_pages=off for initdb
(cherry picked from commit 40439724ea61bb0e8e162f40c05e9d96d5935947)
=> Backport to 5.9 initdb huge_pages

pkg/backingstore/backingstore.go, pkg/backingstore/reconciler.go, test/cli/test_cli_flow.sh, test/cli/test_cli_functions.sh
Allow definition of pv-pool backing store agent resources requests/limits
1. Use PVPoolSpec VolumeResources to pass memory/cpu resources
2. Expose request/limit cpu/memory resource configuration in CLI `backingstore create pv-pool` command
3. Add CLI tests for new functionality
Investigating [Cache issue](https://github.com/noobaa/noobaa-core/issues/6709).
=> Allow definition of pv-pool backing store agent resources requests/limits

deploy/scc_endpoint.yaml, pkg/bundle/deploy.go
Endpoint SCC is used by the DB.
allowPrivilegeEscalation has to be true for DB init
container pv chown to succeed.
The value is already true in OCS operator:
https://github.com/red-hat-storage/ocs-operator/blob/3ce08ad22efa4b4bcb53e5aa3216d8532f2c4bf1/controllers/ocsinitialization/sccs.go#L169
1. 
1. 
1.
=> Fix CLI install - DB init container

pkg/backingstore/backingstore.go, pkg/namespacestore/namespacestore.go
Remove  Secret data printing from backingstore and namespacestore
1.  Fixes: #783 
1.  Run `noobaa backingstore create` or `noobaa  namespacestore create` and see that it is not printing the `# Secret data:`
=> Remove the prints of S3 credentials from NooBaa create backingstore and namespacestore

pkg/obc/provisioner.go, pkg/system/phase4_configuring.go
(cherry picked from commit 9dbc41421583d1040804fc52ffa700c4d0af015c)
1. backported https://github.com/noobaa/noobaa-operator/pull/686
1. 
1.
=> [backport to 5.8] removed tiering creation for namespace buckets

pkg/olm/olm.go
1.  in CSV generation for ODF - add toleration for `node.ocs.openshift.io/storage`
1. fix for bz https://bugzilla.redhat.com/show_bug.cgi?id=2023275
1.
=> added toleration node.ocs.openshift.io/storage to noobaa-operator deployment

pkg/olm/olm.go
(cherry picked from commit 4ce37dc8646ac886b46ea9388ca8f8334d539cc5)
1. backported pr #798 
1. 
1.
=> [backport to 5.9] added toleration node.ocs.openshift.io/storage to noobaa-operator deployment

build/remove-namespace.sh
Ignore not found error.
Sometimes when trying to remove finalizers, the object already doesn't exist. Skip the error.
=> ignore namespace not found in remove-namespace.sh script 

deploy/internal/admission-webhook.yaml, deploy/internal/service_admission_webhook.yaml, pkg/bundle/deploy.go, pkg/operator/operator.go, pkg/options/options.go, test/cli/test_cli_functions.sh, test/test-olm.sh
1. Add admission webhook deployment in cli installation.
2. Deploy the required resources for the admission webhook (ValidationWebhookConfiguration, Service, Secret).
3. Generate self-signed certificate for the admission webhook server to use.
1. 
1.
=> Add admission webhook cli deployment

deploy/internal/prometheus-rules.yaml, pkg/bundle/deploy.go
Updating prometheus-rules for odf:
changed the expr for odf_system_raw_capacity_used_bytes from `NooBaa_system_capacity` to `NooBaa_total_usage`
According to https://github.com/noobaa/noobaa-mixins/pull/28
1. Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2030602
=> Updating prometheus-rules for odf

pkg/system/azure_utils.go
* when creating a storage account in azure utils - setting EnableHTTPSTrafficOnly param to true.
* this is required for creating a storage account for resource groups that enforce secure transfer for storage account - https://bugzilla.redhat.com/show_bug.cgi?id=1970123
(cherry picked from commit 57a96c1fe3ae6095252c67196cf636e5d172cc24)
Backport to PR https://github.com/noobaa/noobaa-operator/pull/805
=> [Backport to 5.9] set EnableHTTPSTrafficOnly on create storage account

deploy/internal/deployment-endpoint.yaml, deploy/internal/statefulset-core.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go
1. Moved the configmap annotation into the spec.
2. Removed the force delete of the pods (core and endpoint)
3. Added the hash also to the config map under annotation
1. Fixes: https://github.com/noobaa/noobaa-core/issues/6811
1. Edit the configmap noobaa-config
2. See that the endpoint deployment strategy is ramped (first  a new pod is up, then the old one is removed).
=> Moved configmap annotation to change the deployment strategies of the endpoint from recreate to ramped

deploy/internal/deployment-endpoint.yaml, deploy/scc_endpoint.yaml, pkg/bundle/deploy.go
- Adding `fsGroupChangePolicy` and `seLinuxOptions` to `securityContext`
according to https://hackmd.io/7heLp_noQmqU_Ef7VaiCKg when we have a large number of files and we want to mount the volume we can get the `Error: context deadline exceeded`.
there are 2 root causes (which are detailed in the link above), and this PR tries to handle them both.
1. Fixes: https://github.com/noobaa/noobaa-core/issues/6708
2. Fixes: https://github.com/noobaa/noobaa-core/issues/6786
3. Fixes: https://github.com/noobaa/noobaa-core/issues/6707
1. Attach a directory with a large number of files to a bucket (or write a lot of files into an NSFS bucket).
2. Restart the endpoint
3. See that there are the endpoint is not in `CreateContainerError` and there are no …
=> Adding `fsGroupChangePolicy` and `seLinuxOptions` to `securityContext`

pkg/options/options.go
1. updated default core image to master-20211222
=> updated default core image to master-20211222

deploy/internal/admission-webhook.yaml, pkg/admission/test/integ/admission_integ_test.go, pkg/admission/test/unit/admission_unit_test.go, pkg/admission/validate_bucketclass.go, pkg/admission/validate_namespacestore.go, pkg/admission/validator.go, pkg/bucketclass/validation.go, pkg/bundle/deploy.go, pkg/util/util.go
1. add bucketclass validation to the admission webhook server.
2. add unit and integration  tests for the bucketclass validations.
3. bug fix in namespacestore quota validation.
1. 
1. `ginkgo -v pkg/admission/test/integ`
2. `ginkgo -v pkg/admission/test/unit`
=> Add Bucketclass admission validations

pkg/admission/test/integ/admission_integ_test.go, pkg/admission/test/unit/admission_unit_test.go, pkg/admission/validate_backingstore.go, pkg/admission/validate_bucketclass.go, pkg/admission/validate_namespacestore.go, pkg/admission/validator.go, pkg/backingstore/backingstore.go, pkg/backingstore/reconciler.go, pkg/backingstore/validation.go, pkg/bucketclass/reconciler.go, pkg/bucketclass/validation.go, pkg/namespacestore/reconciler.go, pkg/namespacestore/validation.go, pkg/namespacestore/validation_test.go
1. move backingstore and namespacestore validations to a single file so that the cli and the operator could use them, also to avoid duplicate code.
1. 
1.
=> Refactor Backingstore and Namespacestore validations

pkg/nb/api.go, pkg/nb/types.go, pkg/noobaaaccount/noobaaaccount.go, test/cli/test_cli_functions.sh
Add Regenerate S3 Credentials to the CLI
Handling 3 cases:
1. An account with no CRD and no secret
2. An account with no CRD but with secret
3. An account with CRD and with a secret
1.  regenerate the s3 keys see that they changed and try to use them
=> Add Regenerate S3 Credentials to the CLI

pkg/dbdump/dbdump.go, pkg/diagnose/diagnose.go, pkg/util/util.go
1.  We have issue with using kubectl in mustgather - will be using kubectl if we have it in diagnostics, otherwise oc.
2.  If both don't exist we will fail the diagnostic.
1.  Fixed https://bugzilla.redhat.com/show_bug.cgi?id=2026342
1.
=> Update diagnostics to support both kubectl and oc

deploy/crds/noobaa.io_backingstores_crd.yaml, deploy/crds/noobaa.io_namespacestores_crd.yaml, deploy/crds/noobaa.io_noobaas_crd.yaml, deploy/internal/statefulset-core.yaml, deploy/operator.yaml, pkg/apis/noobaa/v1alpha1/backingstore_types.go, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, pkg/backingstore/backingstore.go, pkg/backingstore/reconciler.go, pkg/backingstore/validation.go, pkg/bundle/deploy.go, pkg/namespacestore/validation.go, pkg/nb/types.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go, pkg/system/system.go, pkg/util/util.go
1. Added spec field for backing stores crd to include Role ARN for AWS STS
2. Added spec field for noobaa crd to include Role ARN for AWS STS
3. Added Projected Service account token mount to noobaa-operator and nooba-core pods
4. Added function to create AWS STS backing store
5. Added noobaa install cli option `--aws-sts-role-arn`
6. Added check for AWS STS cluster
7. Added Admission Webhook validation for BackingStore
8. Added Validation check for NamespaceStore to not include AWS STS ARN
Signed-off-by: Kaustav Majumder <kmajumde@redhat.com>
1. Create an STS based Kubernetes or Openshift cluster [see more..](https://docs.openshift.com/container-platform/4.7/authentication/managing_cloud_provider_credentials/cco-mode-sts.html#sts-mode-installing-manual-config_cco-mode-sts)
2. Create Role …
=> Support AWS STS in Noobaa

pkg/admission/test/unit/admission_unit_test.go, pkg/admission/validate_backingstore.go, pkg/admission/validate_bucketclass.go, pkg/admission/validate_namespacestore.go, pkg/backingstore/backingstore.go, pkg/backingstore/reconciler.go, pkg/bucketclass/bucketclass.go, pkg/bucketclass/reconciler.go, pkg/namespacestore/namespacestore.go, pkg/namespacestore/reconciler.go, pkg/namespacestore/validation_test.go, pkg/validations/backingstore_validations.go, pkg/validations/bucketclass_validation.go, pkg/validations/namespacestore_validations.go
1. move all the resource validations to a dedicated package, so it can be used from everywhere in the code without worrying about dependencies errors. 
1. 
1.
=> Separate resource validations to a different package

deploy/role_ui.yaml, deploy/service_account_ui.yaml, pkg/bundle/deploy.go, pkg/olm/olm.go, pkg/operator/operator.go
- Run "noobaa olm csv"
Expected generated YAML should contain the following permission:
```yaml
...
install:
spec:
permissions:
...
- rules:
- apiGroups:
- noobaa.io
resources:
- noobaas
- bucketclasses
verbs:
- get
- watch
- list
serviceAccountName: noobaa-odf-ui
```
See https://bugzilla.redhat.com/show_bug.cgi?id=2031705
=> Add noobaa-odf-ui service account's role rules

pkg/system/azure_utils.go
* when creating a storage account in azure utils - setting EnableHTTPSTrafficOnly param to true.
* this is required for creating a storage account for resource groups that enforce secure transfer for storage account - https://bugzilla.redhat.com/show_bug.cgi?id=1970123
(cherry picked from commit 57a96c1fe3ae6095252c67196cf636e5d172cc24)
1. backported PR #805 
1. 
1.
=> [backport to 5.8] set EnableHTTPSTrafficOnly on create storage account

pkg/admission/server.go
1. fixing a typo error in the admission webhook cert file name.
1.  Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2049029
1.
=> Fix typo in the admission server cert file name

pkg/admission/server.go
(cherry picked from commit 5932fb018cffbae06dd59378a411bb8fb5291209)
1. 
1. 
1.
=> Backport to 5.10: Fix a typo in the admission server cert file

build/install-operator-sdk.sh
1. When building on M1 macs, the identified platform is arm64, but for the version of operator-sdk we use (v0.17.2) there is no arm release.
2. x86 build is running fine on M1 macs using the built in translation (Rosetta)  
1. 
1.
=> always install operator sdk for x86. no arm build for v0.17.2

pkg/validations/backingstore_validations.go
validate request in 'Gi' form
1. Due to an error in the conversion scale, the admission server accepted BS with 15Gi volume size.
2. Fixed the conversion issue and include 'Gi' request form in the validation. 
1. 
1.
=> Fix minimum volume size validation

deploy/internal/configmap-postgres-initdb.yaml, pkg/bundle/deploy.go
- Latest RH postgres images moved the postgres binary
from /opt/rh/rh-postgresql12/root/usr/bin/postgres to /usr/bin/postgres
- see https://bugzilla.redhat.com/show_bug.cgi?id=2051249
=> Fix noobaa-db-pg-0 Pod stuck CrashLoopBackOff state

deploy/internal/configmap-postgres-db.yaml, pkg/bundle/deploy.go
1. Increased number of max_connections due to 'too many clients' and similar error messages received by Postgres.
Notice: By merging this PR the bottleneck will be increased to 600 connections, https://github.com/noobaa/noobaa-operator/pull/854 should be merged as well.
1. 
1.
=> Increase postgres max connections

pkg/noobaaaccount/noobaaaccount.go, pkg/util/util.go
1.  Adding CLI flags is for creating nsfs account
2. Adding `uid`,`gid`,`new_buckets_path` and, `nsfs_only` flags to change the defaults.
3. Add GetFlaIntOrPrompt function to util that checks if the flag is -1 and if it is getting the input from stdin
1. Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2047250
1. create an account via the CLI using those flags and see that it is an nsfs account
=> Adding CLI flags is for creating nsfs account

pkg/admission/test/integ/admission_integ_test.go, pkg/admission/test/unit/admission_unit_test.go, pkg/system/phase1_verifying.go, pkg/system/phase4_configuring.go, pkg/system/system.go, pkg/validations/backingstore_validations.go
This change fixes the Tech Debt introduced by AWS STS 
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2041891
1.Validations for  DefaultBackingStore under Noobaa Spec. 
2. If TargetBucket is not supplied as part of Noobaa Spec, operator needs to create it before creating the backing store.
3. Validations to check for TargetBucket in DefaultBackingStore under Noobaa Spec.
4. CLI options to create AWS STS based default backing store
Signed-off-by: Kaustav Majumder <kmajumde@redhat.com>
1. Use noobaa cli to deploy a AWS STS default backingstore
2. Example : nb system create  --default-backingstore-spec="{\"type\": \"aws-s3\", \"awsS3\": {\"awsSTSRoleARN\": \"arn:aws:iam::261532230807:role/kmajumder_noobaa_sts\", \"region\": \"ap-south-1\",\"targetBucket\":\"nb-target-bucket-1\"}}"
=> Fixed Tech Debt for AWS STS support

deploy/crds/noobaa.io_noobaas_crd.yaml, doc/noobaa-crd.md, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, pkg/bundle/deploy.go, pkg/system/phase2_creating.go, pkg/validations/backingstore_validations.go, test/cli/test_cli_flow.sh, test/cli/test_cli_functions.sh
- This PR allows users to provide postgresql database overrides via NooBaa CR. To achieve so, a new field in the NooBaa CRD had to be added.
This PR potentially fixes #793
1. Deploy operator and operator-catalogue image generated from this PR in a Kubernetes cluster.
2. Run `kubectl edit noobaas.noobaa.io noobaa -n <namespace>`
3. Under `spec` add the following (or any postgresql config):
```yaml
...
dbConf: |
max_connections = 600
...
```
4. Save the changes
5. Check the db config map to confirm the overrides were indeed applied by running `kubectl get cm noobaa-postgres-config -n <namespace> -o=go-template='{{index .data "noobaa-postgres.conf"}}'`
- https://github.com/noobaa/noobaa-operator/issues/793#issuecomment-103374 …
=> Support PostgresDB config override from NooBaa CR

pkg/obc/obc.go
- Add Regenerate S3 Credentials for OBC to the CLI
- Fixed the RPC call for list accounts
1.  Regenerate OBC credentials
2. See that s3 ops are working with the new credentials
=> Add Regenerate S3 Credentials for OBC to the CLI

pkg/noobaaaccount/noobaaaccount.go, pkg/noobaaaccount/reconciler.go, test/cli/test_cli_functions.sh
- Fix noobaaaccount CLI to be able to get also namespacestore as a resource
1. Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2047250
1. create nsfs namespacestore
```
$ noobaa namespacestore create nsfs fs1 --pvc-name=‘nsfs-vol’ --fs-backend=‘GPFS’
...
INFO[0003] :white_check_mark: NamespaceStore “fs1” Phase is Ready
nsfs:
fsBackend: GPFS
pvcName: nsfs-vol
subPath: “”
type: nsfs
```
2. create nsfs account and see that it is possible to use that  nsfs namespacestore
```
$ noobaa account create --default_resource fs1 --nsfs_account_config --nsfs_only --full_permission --uid 342 --gid 987 testaccount2
...
INFO[0007] :white_check_mark: NooBaaAccount “testaccount2” Phase is Ready
allow_bucket_creation: true
allowed_buckets: …
```
=> Fix noobaaaccount to be able to get also namespacestore as a resource

deploy/internal/route-s3.yaml, pkg/bundle/deploy.go
- Add insecureEdgeTerminationPolicy to the route-s3.yaml
https://docs.openshift.com/container-platform/4.9/rest_api/network_apis/route-route-openshift-io-v1.html
1. Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2063691
1. on an openshift cluster path the route and see that it is not getting reconciled 
```
oc patch route s3 -n openshift-storage --type merge -p '{"spec":{"tls":{"insecureEdgeTerminationPolicy":"Redirect","termination":"reencrypt"}}}'
```
=> Add insecureEdgeTerminationPolicy to the route-s3.yaml

build/gen-odf-package.sh, go.mod, pkg/admission/test/integ/admission_integ_test.go, pkg/backingstore/backingstore.go, pkg/backingstore/reconciler.go, pkg/bucketclass/bucketclass.go, pkg/controller/backingstore/backingstore_controller.go, pkg/controller/namespacestore/namespacestore_controller.go, pkg/namespacestore/namespacestore.go, pkg/namespacestore/reconciler.go, pkg/nb/api.go, pkg/nb/types.go, pkg/util/util.go, test/cli/resources/empty-secret.yaml, test/cli/test_cli_flow.sh, test/cli/test_cli_functions.sh
related to https://github.com/noobaa/noobaa-operator/issues/684
1. Added a Watch on backing-store Secret events to detect a change in the secret and trigger  a reconcile.
2. Changed `EditExternalConnectionCredentialsAPI` (seems unused) to `UpdateExternalConnectionAPI` to call the relevant  RPC call when needed.
3. Added detection of a mismatch in the used connection by the operator and trying to update the connection.
4. the mismatch found on the reconciler will be based on secret key mismatch and will not detect a mismatch in the access key.
1. https://bugzilla.redhat.com/show_bug.cgi?id=1992090
1. Create two backingstores with the same cloud credentials.
2. Create two namespacestores with the same cloud credentials.
=> Added ability to update BackingStore external connection

.github/workflows/golangci-lint.yml
- Bumped the version in golangci-lint.yml to fix the GH Action lint.
=> Bumped the version in golangci-lint.yml to fix the GH Action lint.

deploy/internal/admission-webhook.yaml, pkg/admission/validate_noobaa.go, pkg/admission/validator.go, pkg/bundle/deploy.go, pkg/install/install.go, pkg/operator/operator.go, test/cli/test_cli_flow.sh, test/cli/test_cli_functions.sh
1. Adds admission controller for Noobaa CR - Prevents resource deletion
2. Preserve the uninstall functionality by altering the WebhookConfiguration before uninstalling.
1. Install noobaa `noobaa install -n <ns> --admission`
2. Attempt to delete Noobaa CR `kubectl delete noobaas.noobaa.io -n<ns> noobaa` => Request should fail with error.
4. Uninstall noobaa `noobaa uninstall -n <ns>` => Should uninstall noobaa
=> Add noobaa admission controller to prevent CR deletion

.github/workflows/golangci-lint.yml, pkg/system/phase2_creating.go, pkg/util/util.go
* for Azure gov\DOD, creating an Azure default backingstore requires a more complicated solution.
* identifying azure gov\dod regions base on the "topology.kubernetes.io/region" label on the nodes.
* when running on azure gov, IsAzurePlatformNonGovernment returns false. as a result a pv pool backingstore is created in phase 4
(cherry picked from commit 176d41b0be4fec46710d6824afa1cfc0c8b1ec4d)
1. backported https://github.com/noobaa/noobaa-operator/pull/907
1. fixes https://bugzilla.redhat.com/show_bug.cgi?id=2079504
1.
=> [backport to 5.10] create a pv-pool default backing store in azure gov platforms

deploy/cluster_role.yaml, deploy/crds/noobaa.io_noobaas_crd.yaml, pkg/admission/validate_noobaa.go, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/bundle/deploy.go, pkg/install/install.go, pkg/operator/operator.go, pkg/system/phase4_configuring.go, pkg/system/system.go, pkg/util/util.go
1. Adds `spec.cleanupPolicy.allowNoobaaDeletion` in NooBaa CR which disables the Noobaa CR deletion prevention feature added in https://github.com/noobaa/noobaa-operator/pull/903.
1. If no policy is specified, it defaults to `false`.
2. Changes the CLI uninstall flow. Now, `noobaa uninstall` just sets `spec.cleanupPolicy.allowNoobaaDeletion` to `true` which triggers noobaa operator to disable the Noobaa CR deletion feature hence allowing the `uninstall` to proceed as usual.
1. Install noobaa operator: `nb install --admission -n <ns>`
2. Run: `kubectl delete noobaas.noobaa.io noobaa -n <ns>` - should fail
=> Add Noobaa CR cleanup policy

pkg/backingstore/backingstore.go, pkg/namespacestore/namespacestore.go
1. check the store type before searching for identical secrets.
1. https://bugzilla.redhat.com/show_bug.cgi?id=2084503
1.
=> Preventing the cli from searching for identical secrets for pvpool 

pkg/backingstore/reconciler.go, pkg/util/util.go
Adding namespace to secretRef from the backingstore or namespacestore when it is missing
1. https://bugzilla.redhat.com/show_bug.cgi?id=2084201
1. We want to add webhooks to avoid create of backingstore with a secret ref without a namespace
=> Adding namespace to secretRef from the backingstore or namespacestore when it is missing

deploy/cluster_role.yaml, pkg/bundle/deploy.go, pkg/system/phase4_configuring.go
1. searching noobaa admission controller by the webhook name and not by the `ValidatingWebhookConfiguration` name.
1. 
1.
=> Fix searching noobaa webhook by name

deploy/cluster_role.yaml, pkg/bundle/deploy.go, pkg/system/phase4_configuring.go
removed Get for webhook config
(cherry picked from commit 9e27116fc78b750471303ee2edbac2a5205fbd19)
1.  backport #920 
1. Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2086982
1.
=> [backport to 5.11] fix searching noobaa webhook by name

pkg/backingstore/backingstore.go, pkg/namespacestore/namespacestore.go
1. checking that the secret returned from `util.GetNamespaceStoreSecret()` and `util.GetBackingStoreSecret()` is not nil.
1. 
1.
=> Fix map secret to store

deploy/cluster_role.yaml, deploy/internal/statefulset-db.yaml, deploy/internal/statefulset-postgres-db.yaml, deploy/role.yaml, deploy/role_binding_db.yaml, deploy/role_db.yaml, deploy/scc_db.yaml, deploy/scc_endpoint.yaml, deploy/service_account_db.yaml, pkg/bundle/deploy.go, pkg/olm/olm.go, pkg/operator/operator.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go
1. Noobaa operator no longer uses 'noobaa' SCC and relies on RBAC only.
2. Handle SCC RBAC creation for DB and Endpoint inside operator's
reconcile loop.
3. OCS operator interface:
a. OCS operator no longer needs to create 'noobaa' & 'noobaa-endpoint'
SCCs. newNooBaaSCC() and newNooBaaEndpointSCC() functions should be
removed from the OCS codebase.
b. Use ''noobaa olm csv' to pass operator's RBAC resources to OCS.
4. Create a rbac/scc for the db.
=> Refactor SCC/RBAC

pkg/backingstore/backingstore.go, pkg/backingstore/reconciler.go, pkg/namespacestore/namespacestore.go, pkg/namespacestore/reconciler.go, pkg/util/util.go
1. this function is not relevant for pvpool and nsfs store types , therefor adding a check in the beginning if the mandatory properties are empty return nil.
1. https://bugzilla.redhat.com/show_bug.cgi?id=2084503
2. https://bugzilla.redhat.com/show_bug.cgi?id=2091894
1.
=> Fix check identical secrets

pkg/backingstore/reconciler.go, pkg/namespacestore/reconciler.go, pkg/util/util.go
(cherry picked from commit dbf490c83b7140bc732b1a8f9339ef2463538add)
1. backported https://github.com/noobaa/noobaa-operator/pull/937
1. 
1.
=> [backport to 5.11] Fix set secret owner reference

pkg/noobaaaccount/noobaaaccount.go, pkg/obc/obc.go, pkg/options/options.go, pkg/system/system.go, test/cli/test_cli_functions.sh
Masked the ACCESS_KEYS and passwords to * by default, in status output.
And, if the `--show-secrets` flag is passed to the command the secrets
are shown.
Fixes: #928
1. Try running the command `noobaa status` after successful installation, you should see the secrets as `*`
2. Run the same command, but this time with the `--show-secrets` flag. The secrets will be visible.
Signed-off-by: nik-redhat <nladha@redhat.com>
=> Added option to show/hide secrets in status output

pkg/backingstore/backingstore.go
Issue: cli doesn't show error when creating a backingstore that isn't available in the commands
Fix: When trying to create unsupported backingstore, An error should be prompted
Fixes: #274
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>
1.
=> cli doesn't show error when creating a backingstore that isn't available in the commands

pkg/namespacestore/namespacestore.go
When trying to create unsupported namespacestore, An error should be prompted
Fixes: #951
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>
=> Issue: cli doesn't show error when creating a namespacestore that isn't available in the commands

pkg/backingstore/reconciler.go, pkg/namespacestore/reconciler.go
1. remove RPC error type check returned from check_external_connection call, any RPC error should trigger a temporary error and there is no need to check if it's a `INVALID_SCHEMA_PARAMS` error.
1. https://bugzilla.redhat.com/show_bug.cgi?id=2101380
1.
=> Remove RPC error type check

pkg/nb/api.go, pkg/nb/types.go, pkg/system/system.go
1. added CLI command `set-debug-level` under `system`. 
``` 
noobaa system set-debug-level [level]
```
2. level can be 0-5 or `warn`
3. implemented by using `publish_to_cluster` to send `debug_api.set_debug_level` to all registered processes. 
4. this setting is not persistent and is only applied to the currently running core and endpoints pods
1. 
1.
=> added set-debug-level command to CLI

Makefile, build/gen-odf-package.sh, pkg/olm/olm.go
* added --obc-crd flag to olm catalog CLI - can be either owned\required\none
* added obc-crd var to Makefile which is used by gen-odf-package target
* default behavior is "required", same as it was before
1. 
1.
=> added an option to own OB\OBC in noobaa CSV

pkg/olm/olm.go
1. fixes a bug introduced in PR #960 
2. when `csvParams == nil`, the default is to require OBC
1. Fixes #961
1. run `noobaa olm csv` 
2. the command should print the CSV instead of crashing
=> Fixed issue #961 - require OBC in CSV when csvParams=nil

pkg/backingstore/backingstore.go, pkg/system/system.go
1. Set the default secret as a combination of backingstore spec type and
name for default backing store.
Fixes: #683 
1. Run the `noobaa backingstore status noobaa-default-backing-store` command, it won't panic.
Signed-off-by: nik-redhat <nladha@redhat.com>
=> Fixed default secret for backingstore

pkg/backingstore/reconciler.go, pkg/nb/types.go
Signed-off-by: Kaustav Majumder <kmajumde@redhat.com>
1. Added `AWSSTSARN` field to CheckExternalConnectionsParams
2. Added AWSSTSARN value from AddExternalConnectionParams to CheckExternalConnectionsParams
1. The CheckExternalConnectionsApi was not passing the RoleArn for existing target bucket.
1. Use noobaa cli to deploy a AWS STS default backingstore
2. Example : nb system create  --default-backingstore-spec="{\"type\": \"aws-s3\", \"awsS3\": {\"awsSTSRoleARN\": \"arn:aws:iam::261532230807:role/kmajumder_noobaa_sts\", \"region\": \"ap-south-1\",\"targetBucket\":\"nb-target-bucket-1\"}}"
=> Fix AWS STS checkExternalConnection to pass AWSSTSARN

README.md, pkg/bundle/deploy.go, version/version.go
1. Bump the z stream version to 5.10.6(it was pointing to older version)
=> [5.10] Update the z version in version.go file from 5.10.1 to 5.10.6

deploy/internal/configmap-ca-inject.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go
following this documentation: https://docs.openshift.com/container-platform/4.11/networking/configuring-a-custom-pki.html
1. Add support for OCP CA Inject in case we have namespace openshift-config in the cluster
2. It will create a config map name noobaa-inject-ca, which OCP will inject with system supported CA
3. It will attach this config map under "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
1. Fixed https://bugzilla.redhat.com/show_bug.cgi?id=2121104
1. Add a backingstore to a compatible S3 which uses a self sign cert.
2. Install the self signed certificate to OCP (following above doc)
3. see that there is no issue with self signed certs when creating backingstore, and when trying to write to it (using OBC)
=> Support OCP injected CA

.github/workflows/manual-build.yml
1. This PR fixes failures in nightly builds. testing for image existence with direct requests to `index.docker.io` now fails with 410
2. testing for noobaa-core image existence with `docker manifest inspect` command, which is independent of docker API directly.
3. based on this [stack overflow answer](https://stackoverflow.com/a/52077346)
1. 
1.
=> changed the way image existence is checked in manual-build workflow

.github/workflows/manual-build.yml
1. this image is used by ocs operator CI. 
2. required for ocs-operator PR https://github.com/red-hat-storage/ocs-operator/pull/1771
1. 
1.
=> own OB\OBC CRDs when building bundle image

pkg/backingstore/backingstore.go, pkg/namespacestore/namespacestore.go
The issue symptom, described in the BZ below, is that creating backingstores fails with `"Note that using more than one secret with the same credentials is not supported"`.  Later AWS S3 operations generate `AccessDenied` error.
According to Ben Eli's great analysis, this only happens if we create backing stores with the MCG CLI and the "--secret-name" option.
This change passes the secret pointed by the "--secret-name" option to [`util.CheckForIdenticalSecretsCreds()`](https://github.com/noobaa/noobaa-operator/blob/24022e21a3881fb64d2ddf1eccf799eb4c6c4f01/pkg/util/util.go#L1818) instead of the default `fmt.Sprintf("backing-store-%s-%s", storeType, name)` one.
-  https://bugzilla.redhat.com/show_bug.cgi?id=2121353
=> Handle creating backingstore with the CLI and the "--secret-name" option.

pkg/backingstore/backingstore.go, pkg/namespacestore/namespacestore.go
Fix for https://bugzilla.redhat.com/show_bug.cgi?id=2121353
(cherry picked from commit 41cbb87ebfe52dcd809cb5ae3e705b1cdceb8c0b)
1. backport of https://github.com/noobaa/noobaa-operator/pull/992
1. 
1.
=> [Backport to 5.12] Handle creating backingstore with the CLI and the "--secret-name" option

pkg/backingstore/reconciler.go, pkg/util/util.go, pkg/util/util_test.go
Fix util.CheckForIdenticalSecretsCreds() for alternative key names
This issue was noted at #992, according to [this comment](https://github.com/noobaa/noobaa-operator/pull/992#issuecomment-1315069219), util.CheckForIdenticalSecretsCreds() uses an empty string `""` as a value for the backing store secret key & id.
Refactor an existing functionality.
=> Map alternate keys value

pkg/olm/olm.go, pkg/operator/operator.go, pkg/system/phase4_configuring.go
Avoid race where noobaa-endpoint SA does not exist while the noobaa-db stateful set is transitioning via init container image update. Pass the endpoint RBAC to OLM via CSV, while handling the endpoint's SCC within the operator.
See https://bugzilla.redhat.com/show_bug.cgi?id=2149261
=> RBAC for endpoint is handled by OLM

pkg/olm/olm.go, pkg/operator/operator.go, pkg/system/phase4_configuring.go
(cherry picked from commit 07ada708c3fddeefd76d8962921561df063c935d)
1. Avoid race where noobaa-endpoint SA does not exist while the noobaa-db stateful set is transitioning via init container image update. Pass the endpoint RBAC to OLM via CSV, while handling the endpoint's SCC within the operator.
1. https://bugzilla.redhat.com/show_bug.cgi?id=2149261
=> [Backport to 5.12] RBAC for endpoint is handled by OLM

pkg/validations/backingstore_validations.go
Prompting more readable error when we get CONNECTED_BUCKET_DELETING
1.  Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2144823
1. create OB (backed by aws backingstore)
2. upload 1 Mil + objects (with 10000 directories)
3. now delete OBC, verify both OB & OBC are deleted successfully!
4. now delete respective bucketclass, very bucketclass is deleted successfully
5. now delete respective backingstore and see the error message
=> Prompting more readable error when we get CONNECTED_BUCKET_DELETING

pkg/validations/backingstore_validations.go
Prompting more readable error when we get CONNECTED_BUCKET_DELETING
(cherry picked from commit fa46462481c800dfafe374e343741982b107f3ec)
=> [Backport to 5.12] Prompting more readable error when we get CONNECTED_BUCKET_DELETING

.github/workflows/releaser.yaml, build/Dockerfile, build/tools/builder-pre.sh, build/tools/builder.sh, build/tools/releaser-post.sh, build/tools/releaser.sh, build/tools/utils.sh
This PR attempts to provide a Github workflow which can be used to automate:
1. Updating `version/version.go`.
2. Updating `options.go`.
3. Update README.md.
4. Release of NooBaa CLI binaries for macos and linux platform (amd64 and arm64).
5. Release of NooBaa operator docker image to dockerhub and quay.
6. Release of NooBaa CLI homebrew formula.
7. Release of krew plugin (disabled in this PR, krew requires a manual first PR and then it can be enabled here).
8. Release of operator on Operator Hub
Flow:
1. Workflow will first read the `version/version.go` to figure out which version is supposed to be built and released.
2. README.md is updated accordingly and push the changes to the base branch.
3. Build assets like: CLI …
=> Add workflow for automated NooBaa releases

deploy/crds/noobaa.io_namespacestores_crd.yaml, doc/namespace-store-crd.md, pkg/admission/validate_namespacestore.go, pkg/apis/noobaa/v1alpha1/namespacestore_types.go, pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, pkg/bundle/deploy.go, pkg/namespacestore/namespacestore.go, pkg/namespacestore/reconciler.go, pkg/util/util.go, pkg/validations/namespacestore_validations.go
1. Adding support for Namespace GoogleCloudStorage
2. Adding CLI for creating NS GoogleCloudStorage
3. Adding validation for Namespacestore GoogleCloudStorage
4. Updating the Namespacestore crd documentation
We need to add tests once the core side will have Namespace GoogleCloudStorage, Currently running throw this flow will fail miserably 🙂
=> Adding support for Namespace GoogleCloudStorage

build/install-operator-sdk.sh
Align operator-sdk download URL with instructions from https://sdk.operatorframework.io/docs/installation/
Build tested on AWS/Graviton machine (arm64).
Signed-off-by: Shachar Sharon <ssharon@redhat.com>
1. Use proper ARCH tag when using operator-sdk (do not asume hard-coded x86_64)
1. Build noobaa-operator image on arm64 machine (AWS Graviton)
1. AWS aarch64 vm
=> build: use proper operator-sdk on ARM64

.github/workflows/golangci-lint.yml, .github/workflows/manual-build.yml, .github/workflows/releaser.yaml, .github/workflows/run_admission_test.yml, .github/workflows/run_ci.yml, .github/workflows/run_hac_test.yml, .github/workflows/run_kms_dev_test.yml, .github/workflows/run_kms_ibm_kp_test.yml, .github/workflows/run_kms_kmip_test.yml, .github/workflows/run_kms_tls_sa_test.yml, .github/workflows/run_kms_tls_token_test.yml, .github/workflows/testing.yml
According to _CI next steps_ meeting:
1. Change default timeouts for our tests to 1.5h (90 minutes).
2. Change all checkout to v3 (v2 is using node version 12).
3. Use GH Concurrency to cancel the previous run.
General cleanup (was not in the meeting): 
1. Update [golangci-lint-action](https://github.com/marketplace/actions/run-golangci-lint) to the latest version.
2. Update [setup-go](https://github.com/marketplace/actions/setup-go-environment) to the latest version - except for one case in `run_ci` file (see [this issue](https://github.com/noobaa/noobaa-operator/issues/1031) for more details).
3. Remove extra newlines.
4. Remove comments that explain the code itself.
The main gap is that the default timeout of jobs is 6 …
=> changes to all GitHub workflows - timeout, checkout v3, concurrency, general cleanup

doc/install-on-minikube-on-ubuntu.md, doc/obc-provisioner.md
1. Add the characters EXAMPLE as a prefix in secrets examples for lines the infoSec found in its alerts that were false-positive alerts in files with ".md" extension.
1. When I worked on the GH Action on a copy of noobaa-operator repository I got false-positive alerts from infoSec.
2. One of the ways to turn it off is to add EXAMPLE as a prefix in secrets, which is the simplest way, suggested by @bplaxco.
1. none
=> Add the characters EXAMPLE as a prefix in secrets examples

pkg/util/kms/test/kmip/pykmip/Dockerfile
Default pip installed pykmip-server generates the following error:
```
sqlalchemy.exc.InvalidRequestError: Implicitly combining column managed_objects.uid with column crypto_objects.uid under attribute 'unique_identifier'.  Please configure one or more attributes for these same-named columns explicitly.
```
See https://github.com/OpenKMIP/PyKMIP/issues/687 for this workaround
=> Fix kmip test

pkg/noobaaaccount/noobaaaccount.go
1. Fix Bug #1043 nb account status of admin@noobaa.io by change the order of conditions nb account status.
1. Show nb account status of [admin@noobaa.io](mailto:admin@noobaa.io) (without any error message).
1. Based on the instructions [here](https://gist.github.com/dannyzaken/c85f0006e5d6582c8d8666cafce6ab76) - the steps of _‘Build images’_ and _‘Deploy noobaa’._
2. Run: `nb account status admin@noobaa.io `
_Note: `nb` is a alias that runs the local operator from `build/_output/bin` (alias created by `devenv`)._
=> Fix Bug #1043 | Noobaa Account Status of admin@noobaa.io

go.mod, go.sum
- Bump goutils v1.1.0 -> v1.1.1
1. Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2159867
=> [Direct on 5.12] Bump goutils v1.1.0 -> v1.1.1

pkg/system/azure_utils.go
The blob storage accessible publicly installed inside  the noobaa cluster in default configuration.
Reason: in `pkg/system/azure_utils.go`
While creating the blob storage the `AllowBlobPublicAccess` should be `false`. By default this parameter is considered to be `true` and access was configured to be `public`.
Explicitly defining `AllowBlobPublicAccess = false` which make blob storage to be configured in `private` mode.
```
step 1:
...
spec:
azureBlob:
secret:
name: noobaa-azure-container-creds
namespace: disallowaccess
targetBlobContainer: noobaacontainersep7h
type: azure-blob
step 2:
apiVersion: v1
data:
AccountKey: QlR6amJSK1JSZ0VTa1VVcVdRNW5ERWllaGFzUExTMmhyMG5pSFJkL0hsTjNpR1lBYXdEa0dWSGdaWlRjOWVQNDFBMWhOODBRV283citBU3Q5SjU1VUE9PQ==
AccountName: bm9vYmFhYWNjb3VudHZqZG5y …
```
=> default access mode of blob storage in noobaa should be private

pkg/system/azure_utils.go
The blob storage accessible publicly installed inside  the noobaa cluster in default configuration.
Reason: in "pkg/system/azure_utils.go"
While creating the blob storage the 'AllowBlobPublicAccess' should be false. By default this parameter is considered to be true and access was configured to be public.
Fix: explicitly defining 'AllowBlobPublicAccess = false' which make blob storage to be configured in private mode.
Steps to verify:
step 1:
...
spec:
azureBlob:
secret:
name: noobaa-azure-container-creds
namespace: disallowaccess
targetBlobContainer: noobaacontainersep7h
type: azure-blob
step 2:
apiVersion: v1
data:
AccountKey: QlR6amJSK1JSZ0VTa1VVcVdRNW5ERWllaGFzUExTMmhyMG5pSFJkL0hsTjNpR1lBYXdEa0dWSGdaWlRjOWVQNDFBMWhOODBRV283citBU3Q5SjU1VUE9PQ==
AccountName: bm9vYmFhYWNjb3VudHZqZG5y …
=> [Backport to 5.12] default access mode of blob storage in noobaa should be private

pkg/system/azure_utils.go
The blob storage accessible publicly installed inside  the noobaa cluster in default configuration.
Reason: in "pkg/system/azure_utils.go"
While creating the blob storage the 'AllowBlobPublicAccess' should be false. By default this parameter is considered to be true and access was configured to be public.
Fix: explicitly defining 'AllowBlobPublicAccess = false' which make blob storage to be configured in private mode.
Steps to verify:
step 1:
...
spec:
azureBlob:
secret:
name: noobaa-azure-container-creds
namespace: disallowaccess
targetBlobContainer: noobaacontainersep7h
type: azure-blob
step 2:
apiVersion: v1
data:
AccountKey: QlR6amJSK1JSZ0VTa1VVcVdRNW5ERWllaGFzUExTMmhyMG5pSFJkL0hsTjNpR1lBYXdEa0dWSGdaWlRjOWVQNDFBMWhOODBRV283citBU3Q5SjU1VUE9PQ==
AccountName: bm9vYmFhYWNjb3VudHZqZG5y …
=> [Backport to 5.11] default access mode of blob storage in noobaa should be private

pkg/system/azure_utils.go
The blob storage accessible publicly installed inside  the noobaa cluster in default configuration.
Reason: in "pkg/system/azure_utils.go"
While creating the blob storage the 'AllowBlobPublicAccess' should be false. By default this parameter is considered to be true and access was configured to be public.
Fix: explicitly defining 'AllowBlobPublicAccess = false' which make blob storage to be configured in private mode.
Steps to verify:
step 1:
...
spec:
azureBlob:
secret:
name: noobaa-azure-container-creds
namespace: disallowaccess
targetBlobContainer: noobaacontainersep7h
type: azure-blob
step 2:
apiVersion: v1
data:
AccountKey: QlR6amJSK1JSZ0VTa1VVcVdRNW5ERWllaGFzUExTMmhyMG5pSFJkL0hsTjNpR1lBYXdEa0dWSGdaWlRjOWVQNDFBMWhOODBRV283citBU3Q5SjU1VUE9PQ==
AccountName: bm9vYmFhYWNjb3VudHZqZG5y …
=> [Backport to 5.10] default access mode of blob storage in noobaa should be private

.github/workflows/run_admission_test.yml, pkg/admission/test/integ/admission_integ_test.go
Changes in the admission tests (integration tests):
1. Separate the last delete test (It, Should Allow) into 2 tests (bs = backingstore, ns = namespacestore).
2. Set the default resource explicitly before starting the first delete operation test.
Changes in the admission test workflow:
1. Clone core repo and build it.
2. Install nb with max resources to pass the tests.
3. Collect logs and upload artifacts.
1. I could not add this fix (#1033) because a test in the integration test didn't pass due to a change in the timing.
1. none, it is checked in the workflow.
=> Admission Tests Changes - Integration and Workflow

pkg/dbdump/dbdump.go
1. Add namespace option in db-dump (not only default) in PG DB only.
1. Today db-dump works well only with the default namespace.
1. Based on the instructions [here](https://gist.github.com/dannyzaken/c85f0006e5d6582c8d8666cafce6ab76) - ‘Build images’.
2. Deploy Noobaa to a namespace that is different than the default (nb install -n test, for example).
3. Run: `nb diagnose --db-dump --dir=my-db-logs-test -n test`.
_Note: `nb` is an alias that runs the local operator from `build/_output/bin` (alias created by `devenv`)._
After running the command (no error):
Viewing the file that was generated (size is above zero bytes):
=> Bug Fix #1040 | Add Namespace Option in Db-Dump (Not Only Default) In PG DB Only

pkg/backingstore/reconciler.go
1. Using the default backing store (type: pv-pool) we found that the phase is `Ready` and the mode is `INITIALIZING`.
1. Inside the issue you can find the details of the investigation.
In default backing store (type: pv-pool):
1. Based on the instructions [here](https://gist.github.com/dannyzaken/c85f0006e5d6582c8d8666cafce6ab76) - the steps of _‘Build images’_ and _‘Deploy noobaa’._
2. `kubectl wait --for=condition=available backingstore/noobaa-default-backing-store --timeout=3m`
3. Right after getting `backingstore.noobaa.io/noobaa-default-backing-store condition met` Run:
`  kubectl edit backingstore/noobaa-default-backing-store`
5. Check at the end of the file that the phase is `Ready` and the mode is `OPTIMAL`.
=> Bug Fix #1007 | Default backing store avoid phase Ready with mode INITIALIZING

pkg/backingstore/backingstore.go, pkg/backingstore/reconciler.go, pkg/controller/backingstore/backingstore_controller.go, pkg/obc/provisioner.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/system.go, pkg/util/util.go
1.  Add toleration and affinity to backingstore pod after editing noobaa CR by adding it as a part of `needUpdate`.
2. Edit the controller of backingstore and add a watch explicitly on changes in noobaa CR.
3. Create a generic function `contains` (will be discussed).
4. Change the condition of toleration and affinity (to be set even if it is `nil`).
1. Title:  Toleration not added to the noobaa-default-backing-store pod after editing storagecluster CR and subs with toleration (to the original BZ about **tolerations** we also added issue #1066 about **affinities**).
2. Before we implemented the change (on adding a change - affinity or toleration): the pods core, db, and endpoint were be terminated and then running, but the operator and backinstore pods were not. 
For the operator it is …
=> Fix Bug BZ 2149872, 1066 | Add Toleration And Affinity to Backingstore Pod after Editing Noobaa CR

deploy/internal/prometheus-rules.yaml, pkg/bundle/deploy.go
Prometheus-rules.yaml should be updated according to https://github.com/noobaa/noobaa-mixins/pull/23
The tag "Noobaa_bucket_quota" has been changed to
"Noobaa_bucket_size_quota" in noobaa-mixins and reflecting the same into noobaa-operator in this PR
* https://bugzilla.redhat.com/show_bug.cgi?id=2154250
Steps to Reproduce:
1. Create bucket in NooBaa and set capacity quota to 2 GB (RPC call {'name': '<bucket-name>', 'quota': 
{'unit': 'GIGABYTE', 'size': 2}}).
2. Upload 5 files with size 500MB into the bucket.
3. Check alerts in ODF Monitoring.
OR
This patch can be tested with the following TC https://github.com/red-hat-storage/ocs-ci/blob/b28dfcd0e3f7fcf624d6590dd40255821058fbf7/tests/manage/monitoring/prometheus/test_noobaa.py#L21
=> Noobaa bucket quota alerts are not working

.github/workflows/run_admission_test.yml, .travis/number_of_pods_in_system.sh
1. Remove the comments about open issues that were closed (#1040 and #1007).
2. Add script to wait until we have the backingstore pod (in k8s we cannot wait for a resource that doesn't exist, more information [here](https://github.com/kubernetes/kubernetes/issues/83242)).
3. Update core repo to the latest commit.
1. none
1. none, will be tested in the workflow.
=> CI | Update Admission Tests Workflow

.github/workflows/run_admission_test.yml
The admission test froze the version of the core in the GitHub action, possibly to ensure stability during testing. However, the comment suggests that it is necessary to update the commit periodically to keep up with changes or fixes in the codebase.
```shell
```
Use the operator's default NooBaa core image, defined by [options](https://github.com/noobaa/noobaa-operator/blob/f7358501716816250702d9a4c96f2526f98534e7/pkg/options/options.go#L33), which may not be the most recent version of the NooBaa core but is presumably stable enough to use.
=> Admission test - release NooBaa core image

deploy/operator.yaml, pkg/bundle/deploy.go
This PR adds security context to NooBaa operator pod as per the requirements of the IBM VA report.
https://bugzilla.redhat.com/show_bug.cgi?id=2167308
=> add security context to NooBaa operator pod

deploy/internal/statefulset-db.yaml, deploy/internal/statefulset-postgres-db.yaml, deploy/scc_db.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go
This PR attempts to replace FS ownership change init container with K8s FSGroup in an attempt to:
1. Fix https://github.com/noobaa/noobaa-core/issues/7030.
FSGroup unfortunately is not a silver bullet:
- Its usage helps us gets rid of init container but that just delegates the responsibility of changing permissions and setting owner to kubelet. In theory, this should be more performant because CRI doesn't have to spin up a container just so that we can do our permission adjustment rather kubelet does that automatically on the mounted volume.
- Kubelet will perform 2 actions on the mounted directory
- Change the group of the owner to the `fsGroup` passed in pod spec. Kubelet does this simply by running `os.Lchown(file, -1, int(*fsGroup))` which is run as a `root` user. This should work …
=> Replace ownership change init container with K8s FSGroup

.github/workflows/golangci-lint.yml, pkg/util/util.go
(cherry picked from commit 0adccb7d59faf8ae848a803352315dab93b19f31)
1. backported https://github.com/noobaa/noobaa-operator/pull/1086
1. Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2183480
1.
=> [5.13 backport] update aws regions

pkg/backingstore/backingstore.go, pkg/namespacestore/namespacestore.go
1. Change Azure fields (account name and account key) to `GetFlagStringOrPromptPassword`.
1. The characters in fields account-name and account-key would not appear (same as in aws-s3) after this fix.
1. Deploy Noobaa On Minikube (Instructions are in draft [here](https://github.com/noobaa/noobaa-core/pull/7261) until the will be moved to the operator repo).
2. it happens in namespacestore and backingstore:
* Namespacestore - Run: `nb namespacestore create azure-blob <name>`, for example: `nb namespacestore create azure-blob shira-azure`
* Backingstore - Run: `nb backingstore create azure-blob <name>`, for example: `nb backingstore create azure-blob shira-bs-azure`
=> Bug Fix 1089 | `account-name` And `account-key` Should Not Appear When Creating azure-blob Namespacestore or Backingstore

pkg/options/options.go, pkg/system/system.go
1. added `--dev` flag to noobaa CLI
2. same as `--mini` but with higher resources requests tuned for a dev environment (mainly M1 macs)
1. Fixes https://github.com/noobaa/noobaa-operator/issues/1017
1.
=> added --dev flag to the cli

.github/workflows/golangci-lint.yml, .github/workflows/run_admission_test.yml, .github/workflows/run_ci.yml, .github/workflows/run_hac_test.yml, .github/workflows/run_kms_dev_test.yml, .github/workflows/run_kms_ibm_kp_test.yml, .github/workflows/run_kms_kmip_test.yml, .github/workflows/run_kms_tls_sa_test.yml, .github/workflows/run_kms_tls_token_test.yml, .github/workflows/testing.yml
1. Add `workflow_dispatch` option where we didn't have it.
2. Exclude `doc` directory from the CI (for more information you can see [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths)).
1. none
1. none
=> CI | Exclude 'docs' Directory From GitHub Workflows 

.github/workflows/golangci-lint.yml, .github/workflows/run_admission_test.yml, .github/workflows/run_ci.yml, .github/workflows/run_hac_test.yml, .github/workflows/run_kms_dev_test.yml, .github/workflows/run_kms_ibm_kp_test.yml, .github/workflows/run_kms_kmip_test.yml, .github/workflows/run_kms_tls_sa_test.yml, .github/workflows/run_kms_tls_token_test.yml, .github/workflows/testing.yml
1. Undo exclude doc directory from CI. After this change all workflows will run on every change (even if it is only documentation).
This was added in #1093, but it doesn't work well with required tests. We decided not to use the workaround to solve it (as described [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks)). 
1. none
1. none
=> CI | Undo Exclude Doc Directory from CI

pkg/system/phase1_verifying.go, pkg/system/phase2_creating.go, pkg/validations/noobaa_validation.go
1. update condition which validates noobaa CR for autoscaler and adds default AutoscalerType to noobaa CR if no type is mentioned (#1023 )
1.  If noobaa AutoscalerType is empty noobaa installation is in an error state
1. Install noobaa in a cluster after installing Prometheus
2. check for the newly created HPA1 autoscaler
=> Noobaa CR valiation Fix

pkg/system/phase2_creating.go, pkg/util/util.go
`noobaa-db` SCC was updated recently. This update is not getting reflected in system upgrades because NooBaa operator does not update the SCC if it already exists. This PR simply forces the operator to apply the intended SCC to the cluster repeatedly in order to keep it in sync.
1. Install NooBaa in an openshift cluster (IMPORTANT). NooBaa Operator version must be older than 16th April 2023.
2. Wait for NooBaa to be healthy.
3. Update NooBaa operator image to the one built off this PR.
4. Old DB pod MUST terminate and a new pod should come up. Failure to do so is an issue.
=> Fix DB SCC reconcile

.github/workflows/manual-build.yml, .github/workflows/testing.yml
1. Change deprecating set-output (instead we use `GITHUB_OUTPUT`), more information [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
1. none
1. none
=> CI | Change Deprecating `set-output`

.github/workflows/run_kms_rotate_test.yml, Makefile, deploy/crds/noobaa.io_noobaas_crd.yaml, go.mod, go.sum, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, pkg/bundle/deploy.go, pkg/options/options.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go, pkg/util/kms/kms.go, pkg/util/kms/kms_ibm_kp.go, pkg/util/kms/kms_k8s.go, pkg/util/kms/kms_kmip.go, pkg/util/kms/kms_vault.go, pkg/util/kms/kms_version.go, pkg/util/kms/test/ibm-kp/kms_ibm_kp_test.go, pkg/util/kms/test/rotate/kms_rotate_suite_test.go, pkg/util/kms/test/rotate/kms_rotate_test.go
This is the interface for sharing keys between the NooBaa operator and the NooBaa core, endpoint pods for the Master Root Key rotation feature. [The Root key rotate - core side #7218](https://github.com/noobaa/noobaa-core/pull/7218)
The secret will contain a list of keys and the pointer to the current key.
```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
name: noobaa-root-master-key-volume
namespace: default
data:
active_root_key: a2V5LTE2Nzg4MjYyMzE1Mjk3ODk0Mzc=
key-1678826231529789437: cTJ1SG5pbXJYeHViVTJTUVkwZmZ6eWVhMFNQSHAwLzNUMS9Wbi9vcGNPVT0=
```
The keys secret volume is mounted into the core, endpoint pods as a volume,
under `/etc/noobaa-server/root_keys` directory
```shell
bash-4.4$ cd /etc/noobaa-server/root_keys
bash-4.4$ ls -l
total 0
lrwxrwxrwx 1 root root 22 Mar 14 …
```
=> Master Root Key rotation for K8S secret backend

deploy/internal/prometheus-rules.yaml, pkg/bundle/deploy.go
`NooBaaBucketExceedingSizeQuotaState` and `NooBaaBucketReachingQuantityQuotaState` are missing in the deployment and the result which the alerts are not getting triggered. Adding the above alerts to this patch.
Ref Patch: https://github.com/noobaa/noobaa-mixins/pull/23
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2154250
=> Adding quantity quota alerts

pkg/backingstore/reconciler.go, pkg/namespacestore/reconciler.go
1. this issue is caused by ReadSystemInfo failing on deletion. this should not cause the deletion to fail. added a check to continue deleting if the error is persistent 
1. https://github.com/noobaa/noobaa-operator/issues/1035 
1. testing instructions in issue
=> ignore ReadSystemInfo persistent error in deletion

.github/workflows/run_admission_test.yml, deploy/job_analyze_resource.yml, pkg/backingstore/backingstore.go, pkg/bundle/deploy.go, pkg/cli/cli.go, pkg/diagnostics/analyze.go, pkg/diagnostics/collect.go, pkg/diagnostics/dbdump.go, pkg/diagnostics/diagnostics.go, pkg/namespacestore/namespacestore.go, pkg/util/util.go, test/cli/test_cli_functions.sh
1. Add (instead of the existing command  `nb diagnose`) `nb diagnostics collect`.
2. Add (instead of the existing command  `nb db-dump`) `nb diagnostics db-dump`.
3. Add new commands to run a few tests on a resource (backingstore or namespacestore):
`nb diagnostics analyze backingstore <name>`
`nb diagnostics analyze namespacestore <name>`
`nb diagnostics analyze resources`
4. Add a yaml file that contains the template of the job that we will run on a single resource (backingstore or namespacestore) using the code in noobaa/noobaa-core#7228.
For more information see Jira [MCGI-144](https://issues.redhat.com/browse/MCGI-144)
1. In this PR we don't handle the case of AWS STS ([MCGI-149](https://issues.redhat.com/browse/MCGI-149)).
Note: to actually run the test you'll need to add the …
=> Diagnose Resource

pkg/system/phase3_connecting.go
1. Adding the port to the ExternalDNS list as we do to all the other lists: InternalIP and InternalDNS
2. Later in the code in phase4_configuring we are going over this list and trying to remove the port 
https://github.com/jackyalbo/noobaa-operator/blob/cee21fef5f8723df29d6bce6198d38671b0d45c7/pkg/system/phase4_configuring.go#L344-L351
3. this fails as we didn't use to have a port - and we are ignoring this kind of issue so the list doesn't have the ExternalDNS just the Internal - so not propogated to the endpoint and it can't split this virtual host when he gets request url with the external virtual host form. like: obc-bucket-92ab874d-3bce-4c26-b086-XXXX.s3-openshift-storage.apps.xxxx.lab.upshift.rdu2.redhat.com
bucket =  obc-bucket-92ab874d-3bce-4c26-b086-XXXX
externalDNS = …
=> fixing issue - setting externalDNS without port

Makefile, pkg/bucketclass/bucketclass.go, pkg/bucketclass/reconciler.go, pkg/obc/provisioner.go, pkg/obc/validation.go, pkg/util/util.go, pkg/validations/bucketclass_validation.go, pkg/validations/common_bucket_validation_integ_test.go, pkg/validations/common_bucket_validations.go, pkg/validations/validations_suite_test.go
1. Merged same code existed in different contexts:
a. merged usage of Namespace bucket info structure creation existing in bucketclass reconciler and in obc provisioner code.
b. Moved validations of namespace policy/placement policy to bucket_class validations class
c. moved replication validation to a new class called common_bucket_validations.go
d. moved replication validation from prepare replication params to validateOBC() and validateOB() functions to get it validated as soon as possible before creating the bucket in NooBaa.
these changes are all needed as they will be re-used again in COSI PR https://github.com/noobaa/noobaa-operator/pull/1132
1. 
1.
=> Refactoring | re-use of code

pkg/nb/rpc_ws.go
1.  Remove printing inside `rpc_ws.go` to avoid a race condition (anyway, there was a plan to refactor and remove it in #811 ).
- `PendingRequests` is a map inside `RPCConnWS`.
- 2 goroutines are relevant in this scope: goroutine `SendPings()` and goroutine `ReadMessages()` which inside it we have `HandleResponse()`.
- When we call `HandleResponse()` we lock the part of the code which deletes an element from a map - but a concurrent goroutine might at this time call `ping` and inside it print `RPCConnW` which contains the map.
- We can have a concurrent write (inside `HandleResponse` we delete) and iterate over the map (inside `ping` read the map).
- In order to help with the investigation we added before the deep-print (`%+v` of the struct `RPCConnW`) a printing of each property …
=> Bug Fix #1135 BZ 2214288 | Remove Printing inside `rpc_WS` to Avoid Race Condition

pkg/nb/rpc_ws.go
(cherry picked from commit 945cced82a00c30a40804629d96b50a6e36f09d4)
1. [Backport to 5.12] remove printing inside rpc_ws to avoid race condition
=> [Backport to 5.12] remove printing inside rpc_ws to avoid race condition

pkg/nb/rpc_ws.go
(cherry picked from commit 945cced82a00c30a40804629d96b50a6e36f09d4)
1. [backport to 5.13] remove printing inside rpc_ws to avoid race condition
=> [backport to 5.13] remove printing inside rpc_ws to avoid race condition

deploy/internal/hpa-keda-scaled-object.yaml, deploy/internal/hpav2-autoscaling.yaml, pkg/bundle/deploy.go, pkg/system/autoscaler.go, pkg/system/reconciler.go
1.  update noobaa endpoint pod with respect to noobaa CR spec. 
1. https://bugzilla.redhat.com/show_bug.cgi?id=2217904
1. install Prometheus(only if Promethue missing) and noobaa in cluster 
eg: ``` helm install prometheus  prometheus-community/kube-prometheus-stack -n monitoring ```
nb install --operator-image='{image}' --noobaa-image='{image}' -n {namespace} --autoscaler-type hpav2 --prometheus-namespace {namespace}
2. update noobaa CR with autoscalerType and prometheusNamespace
``` autoscaler: ```
``` autoscalerType: hpav2 ```
``` prometheusNamespace: monitoring ```
3.update noobaa endpoint min and max count from noobaa CR and check the noobaa endpoint scale up/down.
=> update noobaa endpoint replication

deploy/internal/hpa-keda-scaled-object.yaml, deploy/internal/hpav2-autoscaling.yaml, pkg/bundle/deploy.go, pkg/system/autoscaler.go
1. use CPU usage percentage for noobaa endpoint autoscaling.
2. Both HPAV2 and KEDA will use CPU usage percentages for autoscaling. 
3. This Change also makes sure the existing code for Prometheus based autoscaling is not get changed.
1.  CPU usage percentage for noobaa endpoint autoscaling
1. Install noobaa with hpav2 or keda as autoscaler-type
2. push/pull data to S3 endpoint and monitor CPU percentage, noobaa endpoint should autoscale when CPU percentage goes above 80%
3. CPU less than 80% noobaa endpoint should downscale
=> CPU utilization for HPA

deploy/operator.yaml, pkg/bundle/deploy.go, pkg/util/util.go
1. As we are trying to create an RGW bucket using the operator, we are supposed to have the needed certificates in case RGW uses self-signed certificates. We handled it in core by mounting the OCP-injected CAs, but we didn't for the operator.
2. loading the mounted CA list from "/etc/pki/ca-trust/extracted/pem" happens only once when the operator pod is starting (issue with golang). So, if this mount will be changing in the background we will need to restart the pod in order for the new file to take effect. In order to avoid this restart, I added this file to our reconciled AddToRootCAs util. So we will just need to wait for the next system reconciliation instead of a pod restart.
1. Fixed https://bugzilla.redhat.com/show_bug.cgi?id=2153199
1. Create a cluster with external Ceph (External …
=> Adding ca-inject to the operator yaml as optional, and add it to rootCAs list

deploy/cosi/bucket_class.yaml, deploy/cosi/cosi_bucket.yaml, doc/cosi-provisioner.md, go.mod, go.sum, pkg/apis/noobaa/v1alpha1/cosi_types.go, pkg/bucketclass/bucketclass.go, pkg/bundle/deploy.go, pkg/cli/cli.go, pkg/cosi/cosi.go, pkg/cosi/cosi_bucket_claim.go, pkg/cosi/cosi_bucket_class.go, pkg/cosi/cosi_cli_test.go, pkg/cosi/provisioner.go, pkg/cosi/validation.go, pkg/util/util.go
1. Added cosi bucket claim and bucket class commands to noobaa cli.
2. Supported create, list, status and delete for both COSI bucketclaim and bucketclass
3. Refactored bucketclass cli in order to use the same populate functions for cosi bucketclass.
4. Added COSI types 
5. Added COSI bucket crd yaml to be used on COSI bucket claim creation.
6. Updated docs
7. Added cli integration tests
1. make test-cosi
=> COSI | CLI | bucketclass & bucketclaim support

Makefile, build/gen-odf-package.sh
1. when cosi image was not given, the flags passed to the cli command were `--cosi-sidecar-image --obc-crd=owned`
2. the olm cli evaluated `--obc-crd` to be the default `required`
1. 
1.
=> fixed default cosi image for make gen-odf-package

pkg/cosi/provisioner.go, pkg/options/options.go
1. Removing the path to the COSI socket in case of an old Panic that left it open and will deny cosi provisioner from starting
2. Changed CosiDriverAddress to CosiDriverPath so we can use it in both places: in removal and when creating new provisioner 
1. 
1.
=> Fixing issue with bounded COSI socket

doc/noobaa-crd.md, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/system/phase4_configuring.go, pkg/util/util.go
1. a new [topology-spread-constraints/](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) is added for noobaa endpoint pod to make sure the endpoint pod spread across multiple nodes with a skew difference of 1.
1. https://issues.redhat.com/browse/MCGI-116
1. increase the number of endpoint pods either through HPA or manually through  `noobaa-endpoint` Deployment. Each pod should be spread in different nodes with a maximum skew difference of 1. One point to remember is `whenUnsatisfiable` is configured as `ScheduleAnyway` so if there is any CPU/Memory constraint in nodes that node will be skipped and the pod added to another node without considering topology-spread-constraints.
=> Endpoints  topology-spread-constraints added

pkg/backingstore/reconciler.go, pkg/namespacestore/reconciler.go, pkg/nb/types.go
Signed-off-by: Ben <belimele@redhat.com>
(cherry picked from commit 8b70af667a2bddf929a6bbc1507e2e7b3e14ac15)
1. Backport to 5.14
=> Backport to 5.14

deploy/crds/noobaa.io_noobaas_crd.yaml, deploy/internal/deployment-endpoint.yaml, deploy/internal/statefulset-core.yaml, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, pkg/bundle/deploy.go, pkg/options/options.go, pkg/system/phase2_creating.go, pkg/system/reconciler.go, pkg/system/system.go
1. Adding support to provide a secret reference to a postgres DB URL in noobaa CRD. The secret has to have a key called "db_url" and to be in this format: **potgres://**_user_**:**_password_**@**_full DNS name of external server_**:**_port_**/**_db-name_
2. Adding a CLI option to add postgres-url in the same format in 1. for example:
```
noobaa install --postgres-url="postgres://postgres:GWHMacB1ajy1SkY4Q5FH4myc60lJHTbF3I99LLCCwnLj32Je815cWd92JeQeBSiz@externalserver.namespace.svc:5432/nbcore"
``` 
CLI will create the expected secret and attach it to the noobaa system CRD
1. 
1.
=> Adding basic support for working with external postgres DB

pkg/options/options.go
1.  Updating to the latest image in order to support the changes introduced in https://github.com/noobaa/noobaa-operator/pull/1176
=> Update `ContainerImage` to point to the latest build

doc/dev_guide/deply_noobaa_on_minikube_or_rancher_desktop.md
1. Add guide deploy noobaa on minikube or Rancher Desktop (for developers).
1. Gap - update documentation:
- https://github.com/noobaa/noobaa-operator/blob/master/doc/minikube-demo-script.md
- https://github.com/noobaa/noobaa-operator/blob/master/doc/install-on-minikube-on-ubuntu.md
1. none.
This PR was originally opened in noobaa-core repository noobaa/noobaa-core#7261
=> Add Deploy Noobaa On Minikube or Rancher Desktop Documentation (For Developers)

Makefile
Correcting the syntax error introduced in https://github.com/noobaa/noobaa-operator/pull/1183
=> Correcting misaligned .PHONY in Makefile

pkg/system/autoscaler.go
1. Skip hpav2 resources creation if the metrics type is `Resource`
1. https://bugzilla.redhat.com/show_bug.cgi?id=2228805#c2
1. install noobaa and Prometheus adaptor should not be created if metrics type is Resource
=> Skip hpav2 resources if metrics type is Resource

pkg/util/util.go
1. Update AWS regions with `il-central-1` (see [here](https://aws.amazon.com/blogs/aws/now-open-aws-israel-tel-aviv-region/)).
1. Gap: use the aws-sdk-go to get automated and most updated list of regions.
2. Related to #1086.
1. none.
=> Update AWS Regions

pkg/backingstore/reconciler.go, pkg/namespacestore/reconciler.go, pkg/nb/types.go
1. Pass region param to connection.
1. none.
Need to build with noobaa change noobaa/noobaa-core#7433.
1. Deploy noobaa on MInikube or Rancher Desktop (see [guide](https://github.com/noobaa/noobaa-operator/blob/master/doc/dev_guide/deply_noobaa_on_minikube_or_rancher_desktop.md)).
_Note: `nb` is an alias that runs the local operator from `build/_output/bin` (alias created by `devenv`)._
2. Create namespacestore/backingstore and pass the region explicitly:
`nb namespacestore create aws-s3  <namespace-store-name> --region=<target-bucket-region>`.
`nb backingstore create aws-s3  <backingstore-store-name> --region=<target-bucket-region>`.
3. Add printings to `check_external_connection`, `check_aws_connection` and see that the region passed.
Note: test on buckets in the regions 'us-east-1' and …
=> Pass Region Param to External Connection

pkg/system/autoscaler.go
Signed-off-by: naveenpaul1 <napaul@redhat.com>
(cherry picked from commit 349e04e9f9dfedd78d43a89df29368888ff4af40)
1. backport of #1190 
1. Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2228805
1.
=> [backport to 5.14] Skip hpav2 resources if metrics type is Resource

Makefile
Signed-off-by: Ben <belimele@redhat.com>
(cherry picked from commit 554dfff5c11aa5cae78ed25dcdfebe1c431d569d)
1. backport https://github.com/noobaa/noobaa-operator/pull/1198 
1. 
1.
=> [backport to 5.14] Fix the operator image make target

pkg/cosi/cosi_bucket_claim.go, pkg/cosi/provisioner.go, pkg/cosi/validation.go, pkg/obc/obc.go, pkg/obc/provisioner.go, pkg/obc/validation.go, pkg/validations/common_bucket_validation_integ_test.go, pkg/validations/common_bucket_validations.go
1. In the latest validation refactoring - https://github.com/noobaa/noobaa-operator/commit/a64c96dc3adcbabbec210ad1bdfc69970c6bdfe6  , replication validation was added to OBC validations, but the cli was not able to communicate with noobaa core using an internal RPC connection, tests env var hid this issue on the CI, found it on manual testing. 
1. 
1.
=> CLI | Fix creation and validation of OBC with replication

deploy/job_analyze_resource.yml, pkg/bundle/deploy.go, pkg/diagnostics/analyze.go
1. pass region in analyze resource.
1. none
Note: to actually run the test you'll need to add the changes from this noobaa/noobaa-core#7452.
1. Deploy noobaa on MInikube or Rancher Desktop (see [guide](https://github.com/noobaa/noobaa-operator/blob/master/doc/dev_guide/deply_noobaa_on_minikube_or_rancher_desktop.md)).
_Note: `nb` is an alias that runs the local operator from `build/_output/bin` (alias created by `devenv`)._
2. For backingstore, Run:
`nb backingstore create aws-s3 <backing-store-name>` (optional: add the `--region` flag).
`nb diagnostics analyze backingstore <backing-store-name>`
3. For namespacestore, Run:
`nb namespacestore create aws-s3 <namespace-store-name>`  (optional: add the `--region` flag).
`nb diagnostics analyze namespacestore <namespace-store-name>`
3. For all …
=> Pass Region in Analyze Resource

deploy/internal/deployment-endpoint.yaml, deploy/internal/statefulset-core.yaml, pkg/bundle/deploy.go, pkg/options/options.go, pkg/system/phase2_creating.go, pkg/system/reconciler.go, pkg/system/system.go, test/cli/test_cli_flow.sh, test/cli/test_cli_functions.sh
1. After adding support of connection-string to noobaa-core. We adapting some of the options to support external DB to work with connection strings.
2. Now we won't create 2 secrets, the same secret created/given to the operator will also be used in 'core'
3. Added some more verifications to the connection string. Once SSL is introduced we will switch it with the operator actually trying to connect to the DB itself and these temp checks won't be needed.
4. Changing core version to be after the push of connection string to master.
5. Adding new test case to cli flow to install and uninstall noobaa connected to external DB (the test starting a pod with postgres:15 as the external DB) 
1. 
1.
=> Supporting core connection string in operator

Makefile, deploy/crds/noobaa.io_noobaas.yaml, deploy/internal/deployment-endpoint.yaml, deploy/internal/statefulset-core.yaml, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, pkg/backingstore/backingstore.go, pkg/backingstore/reconciler.go, pkg/bundle/deploy.go, pkg/operator/operator.go, pkg/options/options.go, pkg/system/phase2_creating.go, pkg/system/system.go, pkg/util/util.go, test/cli/resources/external-db-ssl.yaml, test/cli/resources/external-db.yaml, test/cli/test_cli_flow.sh, test/cli/test_cli_functions.sh
Commit 1:
1.  Adding support to SSL with external postgres DB both for server side (ssl-required will validate the certificate of the server), and also for client side (user can use ssl-key and ssl-cert to connect with the server)
Commit 2:
1. Adding an options to run noobaa install with ssl options (both sides)
2. Adding the options to run test-cli with --dev option to make it possible to run on M1 macs
1. 
1.
=> Adding SSL support to External Postgres

pkg/system/phase4_configuring.go
1. Fallback to PV pool when cloud credential (CCO) was sent but didn't receive Secrets by the limited time that we defined. In the current implementation, it is 10 minutes (the number was chosen arbitrarily).
2. Record it as an event (using `recorder.Event`).
3. Save variable `secretName` for readability.
1. The option to use CCO with Manual mode was already introduced in 4.13 (as you can see in the [doc of CCO](https://docs.openshift.com/container-platform/4.13/authentication/managing_cloud_provider_credentials/cco-mode-sts.html)) and this change would be backport.
* Tests were on the cluster bot using `launch 4.14 aws`.
**Before this change:**
1. Install noobaa with default CCO mode - noobaa install should be Ready and we would have default backingstore type will be AWS.
2. Install …
=> Bug Fix BZ 2242854 | Fallback to PV Pool (CCO)

deploy/crds/noobaa.io_noobaaaccounts.yaml, pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go, pkg/bucket/bucket.go, pkg/bundle/deploy.go, pkg/nb/types.go, pkg/noobaaaccount/noobaaaccount.go, pkg/options/options.go
1. Added support for force_md5_etag in operator.
=> Added support for force_md5_etag for bucket and account

pkg/noobaaaccount/noobaaaccount.go, pkg/obc/obc.go
1. Add flag `app-namespace` to command `obc regenerate` (it is used in the code, but not in the usage).
2. Rename `ob.Name` to `ob-%s-%s` instead of `obs-%s-%s`.
3. Fix a couple of typos.
1. Without the flag it causes an error: 
> Error: unknown flag: --app-namespace, See 'noobaa obc regenerate --help' for usage.
1. none
=> Bug Fix BZ 2242414 | Add Flag `app-namespace` To Command `obc regenerate`

pkg/obc/obc.go
1. Use `appNamespace` instead of `options.Namespace` for secret namespace (`obc regenerate`).
1. Without this change we would get an Error: "Could not find secret: name-of-obc, will not regenerate keys."
2. PR #1230 added the option to use the flag, this fix is also needed also (for using the command with this flag).
After we have an image of noobaa-cli with those changes and we installed noobaa (tested on the cluster-bot):
1. Create new namespace: `oc new-project craig-ns1`
2. Create an OBC in the namespace "craig-ns1": `noobaa obc create craig-test-obc2 --app-namespace craig-ns1`.
3. Regenerating an OBC in the namespace "craig-ns1": `noobaa obc regenerate craig-test-obc2 --app-namespace craig-ns1`.
=> Bug Fix BZ 2242414 | Use `appNamespace` Instead of `options.Namespace` For Secret

.github/workflows/run_admission_test.yml
1. Increase the timeout of waiting for the default backing store in run_admission_test (the number was chosen arbitrarily).
1. I observed that I had some cases where the test failed because it exceeded the timeout.
2. GAP - after solving the timeout issue, the tests might still fail and this needs investigation, for example ([here](https://github.com/noobaa/noobaa-operator/actions/runs/6543908815/job/17769325462?pr=1229)):
> Summarizing 3 Failures:
> 
> [Fail] time="2023-10-17T07:47:47Z" level=info msg="✅ Exists: Service \"admission-webhook-service\"\n"
> Admission server integration tests Create operations Pass create validations [It] Should Allow 
> /home/runner/work/noobaa-operator/noobaa-operator/noobaa-operator/pkg/admission/test/integ/admission_integ_test.go:177
> 
> [Panic!] …
=> CI | Increase Timeout In run_admission_test

pkg/nb/router.go
Signed-off-by: Aayush Chouhan <aayush.chouhan97@gmail.com>
(cherry picked from commit 0f3dd04f29952dbe87b357653c8ac4ab6f6fb2f3)
1. 
1. https://bugzilla.redhat.com/show_bug.cgi?id=2246333
1.
=> [backport to 5.13] BugFix - [MCG] RPC method "list_objects" fails with "RPC: object.list_objects() Call failed: failed to WebSocket dial"

pkg/nb/router.go, pkg/options/options.go
…_objects() Call failed: failed to WebSocket dial"
Signed-off-by: Aayush Chouhan <aayush.chouhan97@gmail.com>
(cherry picked from commit 0f3dd04f29952dbe87b357653c8ac4ab6f6fb2f3)
1. https://bugzilla.redhat.com/show_bug.cgi?id=2246334
1. 
1.
=> [Backport to 5.12] BugFix - [MCG] RPC method "list_objects" fails with "RPC: object.list_objects() Call failed: failed to WebSocket dial"

pkg/system/phase4_configuring.go
(cherry picked from commit d61774ed908e73bb23eebd4fd13953779e2a5331)
1. Fallback to PV pool when cloud credential (CCO) was sent but didn't receive Secrets by the limited time that we defined
2. Record it as an event (using recorder.Event)
1. https://bugzilla.redhat.com/show_bug.cgi?id=2242880
1.
=> [Backport to 5.13] fix - fallback to pv pool (cco)

pkg/system/phase2_creating.go
1. add logs when the storage class of DB is different (print the name of them).
2. Add logs in case DB volume resources are different (without values).
3. Fix a typo in a comment.
1. none
1. Build the image and deploy noobaa on local cluster (see [guide](https://github.com/noobaa/noobaa-operator/blob/master/doc/dev_guide/deply_noobaa_on_minikube_or_rancher_desktop.md)).
_Note: `nb` is an alias that runs the local operator from `build/_output/bin` (alias created by `devenv`)._
2. Change the storage class of DB in noobaa: 
`kubectl edit noobaa -n <your-namespace>`
and paste under "dbType: postgres"
"dbStorageClass: lala" ("lala" has no meaning, just not an empty string).
3. You can see the events in `kubectl describe noobaa -n <your-namespace>`:
> Warning  DBStorageClassIsImmutable  46s …
=> Add Logs to `Setdesirednoobaadb` Before Record an Event

pkg/backingstore/backingstore.go, pkg/namespacestore/namespacestore.go
1. Edit noobaa CLI short of creation of `noobaa backingstore create aws-sts`.
2. Add validation to `aws-sts-arn` that the user enters.
3. Add the above changes to `noobaa namespacestore create aws-sts`.
1. none, I thought that the description creates an expectation to see a new type of `aws-sts-s3` which is not true (it is `aws-s3`), hence suggesting to change it.
To see the new changes in the noobaa CLI build the image using `make cli`.
1. `noobaa backingstore create --help` attached partial output:
> Available Commands:
>   aws-s3                 Create aws-s3 backing store (using long-lived credentials)
>   aws-sts-s3          Create aws-s3 backing store (using STS, short-lived credentials)
2.  `noobaa namespacestore create --help` attached partial output:
> Available Commands:
> …
=> Edit CLI Short of Creation of Type `aws-sts-s3` in BS and NS

pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go, pkg/util/util.go
1. Change variable name `IBMCloudCOSCreds` to `IBMCosBucketCreds` - since `CloudCred` suffix is for `CredentialsRequest` and currently we don't use `CredentialsRequest` in IBM COS.
2. Change the comment in `prepareIBMBackingStore` related to "cred request" (because there is no `CredentialsRequest`).
3. Change printing from hard-coded ("PV-Pool") to const variable.
4. Fix typo in comment
1. none
1. none
=> Default Backingstore IBM COS - Change Comment and Variable Name

pkg/noobaaaccount/noobaaaccount.go, pkg/obc/obc.go
Regenerating s3 credentials for OBC not in a different namespace fails
1. Add Flag app-namespace To Command obc regenerate
2. Use appNamespace Instead of options.Namespace For Secret 
1. Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2246328
=> [Backport into 5.14] Regenerating s3 credentials for OBC not in a different namespace fails

pkg/system/phase4_configuring.go
1. Add a condition before assignment to map, to avoid the error: panic: assignment to entry in nil map.
1. Details are in the issue.
1. Written in the issue.
=> Bug Fix #1259 | Fix Bug Operator Restart on GCP Cluster

.github/workflows/golangci-lint.yml
1. updated golangci-lint to latest version - 1.55
2. removed deprecated flags that produced warning
1. 
1.
=> updated golangci-lint to 1.55 + removed depracated flags

Makefile, build/gen-odf-package.sh, deploy/crds/noobaa.io_noobaas.yaml, deploy/internal/configmap-postgres-initdb.yaml, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, pkg/bundle/deploy.go, pkg/olm/olm.go, pkg/options/options.go, pkg/system/phase2_creating.go
1. Moving efforts started in PR #1221 by @nadavMiz  to here in order to merge the code.
1. 
1.
=> [Clone] Add upgrade process for postgres DB version 15

pkg/util/util.go
Signed-off-by: Ben <belimele@redhat.com>
(cherry picked from commit e59f5e872e6ec08d5a36b26b359c3975dc9f36a1)
1. backported PR #1279 
1. 
1.
=> [backport to 5.15] Fix the label-based IBM cluster region lookup (#1279)

pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go, pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, pkg/nb/types.go, pkg/noobaaaccount/noobaaaccount.go, pkg/noobaaaccount/reconciler.go
1. Added force_md5_etag in NoobaaAccount CmdUpdate
1. force_md5_etag was missing in NoobaaAccount CmdUpdate.
=> Fix - Added force_md5_etag in NoobaaAccount CmdUpdate 

doc/psql15-upgrade.md
=> Adding document on PgSql upgrade procedure

pkg/system/phase2_creating.go
1. in case of MongoDB we still ran the upgrade process for Postgres - we shouldn't 
1. 
1.
=> Fix - don't run db 15 upgrade for mongoDB

doc/psql15-upgrade.md, pkg/backingstore/backingstore.go, pkg/backingstore/reconciler.go, pkg/system/phase2_creating.go, pkg/system/system.go
1. Adding document on pgsql upgrade procedure
2. Fix the CLI upgrade option by adding a missing namespace field to the system's YAML (#1285)
3. fix - don't run db 15 upgrade for mongoDB
4. Remove upgradeBackingStore
1. Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2255586
2. Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2258681
=> [Backport into 5.15] backporting some bug fixes

deploy/crds/noobaa.io_noobaas.yaml, deploy/internal/deployment-endpoint.yaml, deploy/internal/service-syslog.yaml, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go, pkg/bundle/deploy.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go
Whenever an object operation comes to endpoint, handle_request function process it and logs it to its /var/log/messages.
We need these logs to be sent on noobaa core so that we can process it further and accordingly write it to log bucket as log objects.
In this code change we are creating a service noobaa-syslog. We will send logs from end point to this service which in turn deliver it to noobaa core.
Credit goes to aprinzse@redhat.com for the code contribution.
=> Noobaa/Bucket Logging : syslog service for log transfer

.github/workflows/golangci-lint.yml, .github/workflows/manual-build.yml, .github/workflows/releaser.yaml, .github/workflows/run_admission_test.yml, .github/workflows/run_ci.yml, .github/workflows/run_cosi_test.yaml, .github/workflows/run_hac_test.yml, .github/workflows/run_kms_dev_test.yml, .github/workflows/run_kms_ibm_kp_test.yml, .github/workflows/run_kms_kmip_test.yml, .github/workflows/run_kms_rotate_test.yml, .github/workflows/run_kms_tls_sa_test.yml, .github/workflows/run_kms_tls_token_test.yml, .github/workflows/testing.yml
1. Update the checkout and setup-go version from 3 to 4.
1. Currently we have a warning in our CI:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-go@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
1. none, will be tested in the CI.
=> CI | Update Checkout and Setup-Go Version

pkg/system/phase1_verifying.go
1. we are printing: `collation of external DB url: "BLA", is not supported: %!s(<nil>)`. we will now print with the correct collation.
1. 
1.
=> fixing error for collation external PG

README.md, pkg/bundle/deploy.go, version/version.go
=> Bump version to 5.16.0

pkg/system/azure_utils.go, pkg/system/phase4_configuring.go, pkg/util/util.go
=> [5.15 BACKPORT] Utilize the refreshing global CA bundle for the Azure and Google clients

pkg/util/util.go
1. Update AWS regions with `ca-west-1` (see [here](https://aws.amazon.com/blogs/aws/the-aws-canada-west-calgary-region-is-now-available/
)).
1. Currently we don't have the region `ca-west-1` that was added lately.
1. none.
1. 
1.
=> Update AWS Regions with New Region

deploy/crds/noobaa.io_noobaas.yaml, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/bundle/deploy.go, pkg/system/phase2_creating.go
1. we want to allow users to deny HTTP in Noobaa s3 route, so it will be compatible with OpenShift compliance operator
1. Fixed https://bugzilla.redhat.com/show_bug.cgi?id=2222146
1.
=> Adding denyHTTP option to NooBaa CR

pkg/system/phase2_creating.go
1. We returned a wrong state in case the init-container still is running and not yet completed. 
We returned State.String() which didn't just return Running but also printed some more info about the state.
As we later in the code checks explicitly for Running we should return the correct state
2. Added prints so we will know for sure what state the HasUpgradeDbContainerFailed function returned. 
3. Added events for the different phases of the upgrade procedure
1. 
1.
=> [DB Upgrade] Fixing returned status and adding prints

deploy/internal/route-s3.yaml, pkg/bundle/deploy.go
1. Disable the cookies when using s3 routes as some s3 clients like Cyberduck don't handle them correctly. 
1. Fixed #1327
1. install a noobaa system on top of OCP cluster
2. try to connect to the system with default access keys using Cyberduck
3. see that you can connect and list the buckets and not get issues about bad signature
=> Adding disable_cookies annotation to S3 route

pkg/system/phase2_creating.go
1. When the secret had already been created, our internal secret which was used as a mount to our pods, was failing to be updated. Changing the reconcile function to apply the updated data to the secret fix this issue.
1. 
1.
=> Fixing reconcile for mounted root-key secret noobaa-root-master-key-volume

pkg/util/kms/kms_azure.go, pkg/util/kms/test/azure-vault/kms_azure_vault_test.go
Fixing AzureClientCertPath in kms for azure
The azure kms is expecting the secret to be present
at key azure.AzureClientCertPath. We were storing the
secret with wrong key which which was stopping azure kms
to read the secret the from expected key.
This patch handles the correction
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2275049
=> Fixing AzureClientCertPath in kms for azure

pkg/util/util.go
[Backport into 5.14] Fix the label-based IBM cluster region lookup (#1279)
Signed-off-by: Ben <belimele@redhat.com>
(cherry picked from commit e59f5e872e6ec08d5a36b26b359c3975dc9f36a1)
=> [Backport into 5.14] Fix the label-based IBM cluster region lookup (#1279)

pkg/backingstore/reconciler.go, pkg/namespacestore/reconciler.go, pkg/nb/types.go
Fix printing of Identity
we should see in the logs:
```
time="2024-05-01T15:15:37Z" level=info msg="✈️  RPC: account.check_external_connection() Request: {Name:newbc EndpointType:AWS Endpoint:https://s3.amazonaws.com Identity:**** Secret:**** AuthMethod: AWSSTSARN: IgnoreNameAlreadyExist:false AzureLogAccessKeys:<nil> Region:}"
```
https://bugzilla.redhat.com/show_bug.cgi?id=2277186
=> Fix printing of Identity

deploy/internal/pod-agent.yaml, deploy/internal/statefulset-postgres-db.yaml, pkg/bundle/deploy.go
* Fix for mount permissions
* For some reason, the changes in #1340 caused the PV to be mounted without write permissions for GID 0 and be owned by root user. 
* Added fsGroup 0 to the agent pod. This adds `w` permission to the mount for the owning GID 0 and provides write access to the agent process.
* Also moved `allowPrivilegeEscalation` in the DB sts to the container security context
* This setting can only be set in the container security context, not the pod security context. (see [here](https://medium.com/pareture/k8s-podsecuritycontext-vs-containersecuritycontext-4ca682670f7b))
1. Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2278120
1. Create a pv pool on an openshift cluster
2. Make sure it runs successfully 
3. The issue is not reproducible on minikube\rancher, since the pv …
=> Fix for mount permissions on the agents PV

deploy/scc_db.yaml, pkg/bundle/deploy.go
In the master branch and 5.16, because we do no longer have an init container, we no longer require a lot of privileges to operate. The same is **not** true for versions before and including 5.15.
I tried multiple combinations of:
```
AUDIT_WRITE
CHOWN
DAC_OVERRIDE
FOWNER
FSETID
KILL
MKNOD
NET_BIND_SERVICE
SETFCAP
SETGID
SETPCAP
SETUID
SYS_CHROOT
```
capabilities but nothing really worked hence adding back the dropped default privileges. Will seek exception for this container (and I think we did do that initially for 5.14).
1. Broke 4.15.3 RC build - fixing that
1. Created a fresh openshift-cluster from cluster bot.
2. Used CLI built from this patch and ran `nb install ...`.
3. Waited for the system to be stable.
4. Ran `aws s3 ls` against the deployment.
5. Created obc and then S3 ops …
=> [5.15] SCC Fix

pkg/nb/api.go, pkg/nb/types.go, pkg/noobaaaccount/noobaaaccount.go, pkg/options/options.go, pkg/util/util.go, test/cli/test_cli_functions.sh
1. Added a CLI command to manually update account credentials (access key and secret key). Users can provide the access key and secret key as flags, or they will be prompted to enter them if the flags are not specified.
For example: `noobaa account credentials --access-key=<access-key> --secret-key=<secret-key>`
Additionally, validation checks have been implemented for both keys to ensure the command succeeds only with valid credentials.
1. `make test-cli-flow`
=> Support to update credentials manually to an account

pkg/noobaaaccount/noobaaaccount.go
1.  Added the casting for `access_keys` in GenerateNonCrdAccountKeys.
1. Casting gap
=> Fixed type casting for GenerateNonCrdAccountKeys

deploy/crds/noobaa.io_noobaas.yaml, deploy/internal/nsfs-pvc-cr.yaml, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/bundle/deploy.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go, pkg/util/util.go
NSFS: Create default resource objects on Fusion HCI
ODF MCG on Fusion HCI with Spectrum Scale CNSA should
configure the default BucketClass, Namespacestore and
default PVC to use NSFS.
To set up NSFS on kubernetes, we need to create pvc
and namespacestore which can be used to create nsfs
bucket class. These nsfs buckets are used to create
a user bucket by s3 client.
=> Nsfs : Default resources on hci odf

pkg/system/phase1_verifying.go, pkg/system/phase2_creating.go, pkg/system/reconciler.go
1.  Added validation checks for `BucketLoggingPVC` to ensure it is specified for 'guaranteed' logging and has ReadWriteMany (RWX) access. Also, in case of ODF we will create a new PVC if not provided by the user.
=> Validations for BucketLoggingPVC in case of guaranteed bucket logging

deploy/internal/configmap-postgres-initdb.yaml, pkg/bundle/deploy.go
* Postgres upgrade scripts are being run in an init container. since postgres server is required for dump and restore in different Postgres versions, it is being run in the background in the upgrade scripts using the container's script `/usr/bin/run-postgresql`.
* `run-postgresql` runs postgres twice, first time for initialization if needed, and second time to actually run the server with the given params.
* in some cases the upgrade script identifies postgres as ready in the initialization run, and starts the restore from dump. then if `run-postgresql` stops the server, the restore fails.
* To fix - added 30 sec sleep after pg_isready, to alow for the init phase to complete (usually it should take a few seconds)
* Also added error handling and retries in case there are any errors in the …
=> [Direct to 5.15] Added error handling and retries in postgres upgrade scripts

deploy/internal/deployment-endpoint.yaml, deploy/internal/statefulset-core.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go
1.  Binding bucket logging pvc and path to core and endpoint pods
PVC yaml (example):
```apiVersion: v1
kind: PersistentVolumeClaim
metadata:
name: aayush-pvc
spec:
storageClassName: standard
accessModes:
- ReadWriteMany
resources:
requests:
storage: 1Gi
```
=> Binding bucket logging pvc and path to core and endpoint pods

pkg/system/reconciler.go
1. Changed the volume mount path from 'etc/logs/bucket-logs' to '/etc/logs/bucket-logs'.
1. Improvement #1371 
1.
=> Fix the VolumeMount path for bucket logging

pkg/system/phase1_verifying.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go
1.  Checking for bucket logging pvc only if BucketLoggingPVC is provided by the user. Currently, checks are failing if cephfs storage class is already present inside the cluster.
1. Improvement: #1368 
1.
=> Checking for pvc only if BucketLoggingPVC is not nil

go.mod, go.sum
Bumps [github.com/hashicorp/go-retryablehttp](https://github.com/hashicorp/go-retryablehttp) from 0.7.6 to 0.7.7.
- [Changelog](https://github.com/hashicorp/go-retryablehttp/blob/main/CHANGELOG.md)
- [Commits](https://github.com/hashicorp/go-retryablehttp/compare/v0.7.6...v0.7.7)
---
updated-dependencies:
- dependency-name: github.com/hashicorp/go-retryablehttp dependency-type: indirect ...
Signed-off-by: dependabot[bot] <support@github.com>
(cherry picked from commit 5de77157482ea8a738c339fb211307afa22c5b55)
=> [Backport into 5.16] Bump github.com/hashicorp/go-retryablehttp from 0.7.6 to 0.7.7

README.md, pkg/bundle/deploy.go, version/version.go
[5.15] Bumping version from 5.15.4 to 5.15.6
- We are skipping 5.15.5 as it was used for a quick respin on the downstream, with no code changes in NooBaa.
=> [5.15] Bumping version from 5.15.4 to 5.15.6

deploy/internal/statefulset-core.yaml, deploy/role_binding_core.yaml, deploy/role_core.yaml, deploy/scc_endpoint.yaml, deploy/service_account_core.yaml, pkg/bundle/deploy.go, pkg/olm/olm.go, pkg/operator/operator.go
1. Added SA/Role/Rolebinding for noobaa-core pod. As I don't think any additional SSC caps over noobaa-db used this SCC
2. Fixed noobaa-endpoint SCC to use MustRunAs instead RunAsAny to avoid inner namespace s3linux labeling - which blocks access between endpoints and core and between endpoints.
1. 
1.
=> Fixing SCC issues for bucket logging

pkg/system/reconciler.go
1. If the noobaa db image is `NOOBAA_PSQL_12_IMAGE` when completing reconciliation, set the noobaa CR to `Rejected`
1. https://bugzilla.redhat.com/show_bug.cgi?id=2299836
1.
=> [Direct to 4.15] Set Noobaa status to rejected if failed to upgrade to postgresql-15

deploy/internal/statefulset-core.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go, pkg/util/util.go
1.  part of the change required in [Implement OCS and MCG operator support for pool ownership](https://issues.redhat.com/browse/RHSTOR-6123) adds an indication to the core that the cluster is set to provider mode upon deployment.
1. This implementation supports [RHSTOR-5187 - Support Provider & Consumer mode](https://issues.redhat.com/browse/RHSTOR-5187)
1.
=> Implement operator support for pool ownership

pkg/system/phase2_creating.go
* this change is done directly on 5.15. The code in the master (5.16 and up) removes the need for an init container. 
* upgrade of postgres 12 to 15 assumes there is an init container to the DB sts.
* in some cases, it is possible that the DB is running without an init container.
* If no init container exists, the operator will crash when attempting to access the init containers array.
* The fix adds an init container to the pod spec from the DB statefulset template (statefulset-postgres-db.yaml)
1. Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2281839
1. install noobaa
2. stop the operator
3. remove the init container from DB sts
4. start the operator. it should now add the init container back.
=> [Direct To 5.15] add InitCotnainers to DB sts if not exist

pkg/backingstore/reconciler.go, pkg/system/phase4_configuring.go, pkg/util/util.go
1. Currently, when we create a pv backingstore then the backingstore pod got scheduled on the random basis on any node. This is not good as if any node goes down all the backingstore pod on that node will be down. To increase the performance we have added topology spread constraints to the backingstore pod so they get scheduled on spread basis.
1. fix: https://bugzilla.redhat.com/show_bug.cgi?id=2294846
1. After installing noobaa, try creating new pv-backingstore and check if the pv backingstore pod got scheduled and spread across the multiple nodes. Each pod should be spread in different nodes with a maximum skew difference of 1.
=> Added TopologySpreadConstraints to the backingstore pod for better performance

deploy/internal/pod-agent.yaml, pkg/backingstore/reconciler.go, pkg/bundle/deploy.go
1. Kubernetes automatically mounts a service account token for every pod by default. 
2. The best practice is to mount it only for pods that require access to the Kubernetes API. 
3. For now, disabling automount for pv-pool pods. We should consider it for all pods other than the operator.
4. see more info [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#opt-out-of-api-credential-automounting) 
1. 
1.
=> disable automatic mount of SA token for pv-pool pod

pkg/system/phase2_creating.go, pkg/system/reconciler.go
1. Currently, bucketLogVolumes and bucketLogVolumeMounts are not updating in noobaa core pod once set with bucketLogging. Added a fix to update both of them with bucketLogging.
1. fix: https://bugzilla.redhat.com/show_bug.cgi?id=2302842
2. Improvement: #1371 
1. Try updating bucketLoggingPVC in bucketLogging or removing bucketLogging and check if both volumes and volumeMounts got updated in noobaa core.
=> Added a fix to update bucketLogVolumes and bucketLogVolumeMounts in noobaa core pod

deploy/internal/deployment-endpoint.yaml, pkg/bundle/deploy.go
1. For future use in bucket logging - need node awareness in the pods. This suppose to push the name of the node running the pod to the pod environment variables.
1. 
1.
=> Adding node name env var to endpoints

deploy/internal/deployment-endpoint.yaml, deploy/internal/pod-agent.yaml, pkg/backingstore/reconciler.go, pkg/bundle/deploy.go, pkg/controller/backingstore/backingstore_controller.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/reconciler.go, pkg/util/util.go
=> backport into 5.17

deploy/internal/statefulset-core.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go
1. moved the check for the env var to the appropriate location
2. changed env var location in yaml file and made it optional
1. https://bugzilla.redhat.com/show_bug.cgi?id=2301889
2. change introduced as part of [epic](https://issues.redhat.com/browse/RHSTOR-5187) were causing clusters deployed in provider mode to fail deployment, operator crashed while trying to change env var value which was not found.
1.
=> Fix provider env var panic

.github/workflows/manual-build.yml
1. mandatory env `psql-12-image` was missing in the `make bundle-image` command
=> Fixed 'Build Bundle' step in manaual-build workflow

pkg/noobaaaccount/reconciler.go, pkg/system/phase1_verifying.go, pkg/system/phase4_configuring.go, pkg/util/util.go
1.  continuation of Kaustav's [PR](https://github.com/noobaa/noobaa-operator/pull/1389) 
1. 
1.
=> Added support to join external noobaa system from hosted clusters

deploy/internal/deployment-endpoint.yaml, deploy/internal/pod-agent.yaml, deploy/internal/statefulset-core.yaml, pkg/backingstore/reconciler.go, pkg/bundle/deploy.go, pkg/system/phase2_creating.go
This patch is in sync with the changes on noobaa-core side.
https://github.com/noobaa/noobaa-core/pull/8281
We need to make sure a user can enable/disable the log color generated by core, endpoint and backing store.
- Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2297435
=> noobaa/operator: Provide option to disable log colors

pkg/olm/olm.go
1. The capabilities annotation indicates the maturity level of the operator in the OLM
2. more details here: https://sdk.operatorframework.io/docs/overview/operator-capabilities/#level-2---seamless-upgrades
1. https://bugzilla.redhat.com/show_bug.cgi?id=2303820
1. generate noobaa CSV. e.g.:
```
make gen-odf-package csv-name="noobaa-operator.csv" core-image="noobaa/noobaa-core:5.10.0" db-image="centos/postgresql:12" operator-image="noobaa/noobaa-operator:5.10.0" obc-crd="none" psql-12-image="ttt"
```
2. check that the generated CSV has the `capabilities` annotation with `Seamless Upgrades` values
=> Added annotation to CSV capabilities="Seamless Upgrades"

pkg/olm/olm.go
(cherry picked from commit d089ca8186cecaf0fb6ffcd01d068a0b08a7f500)
1. backported https://github.com/noobaa/noobaa-operator/pull/1423
1. The capabilities annotation indicates the maturity level of the operator in the OLM
2. more details here: https://sdk.operatorframework.io/docs/overview/operator-capabilities/#level-2---seamless-upgrades
1. https://bugzilla.redhat.com/show_bug.cgi?id=2303820
1. generate noobaa CSV. e.g.:
```
make gen-odf-package csv-name="noobaa-operator.csv" core-image="noobaa/noobaa-core:5.10.0" db-image="centos/postgresql:12" operator-image="noobaa/noobaa-operator:5.10.0" obc-crd="none" psql-12-image="ttt"
```
2. check that the generated CSV has the `capabilities` annotation with `Seamless Upgrades` values
=> [Bakport to 5.17] added annotation to CSV capabilities="Seamless Upgrades"

Makefile
Disabling lint as a quick fix to release the CI flow.
=> Disabling lint as a quick fix to release the CI flow.

Makefile, deploy/role_binding_core.yaml, deploy/role_core.yaml, pkg/bundle/deploy.go, pkg/operator/operator.go, pkg/system/phase2_creating.go
(cherry picked from commit 43966a48ad3d0460a2eb97467fe4fb1382bd3cd1)
1. 
1. 
1.
=> [Backport to 5.17] Fix serviceAccount for noobaa-core

Makefile
Lint is deprecated and failing due to a dependency. 
Disabling it as a quick fix to release the CI flow.
(cherry picked from commit c0948d3d7f548124f25b68bdd3f2aec7c247bf9f)
=> [Backport into 5.16] Disabling lint as a quick fix to release the CI flow. 

Makefile
Lint is deprecated and failing due to a dependency. 
Disabling it as a quick fix to release the CI flow.
(cherry picked from commit c0948d3d7f548124f25b68bdd3f2aec7c247bf9f)
=> [Backport into 5.14] Disabling lint as a quick fix to release the CI flow.

Makefile, test/cli/test_cli_flow.sh
Lint is deprecated and failing due to a dependency. 
Disabling it as a quick fix to release the CI flow.
(cherry picked from commit c0948d3d7f548124f25b68bdd3f2aec7c247bf9f)
=> [Backport into 5.15] Disabling lint as a quick fix to release the CI flow. 

.golangci.yml, Makefile, pkg/backingstore/backingstore.go, pkg/bucketclass/bucketclass.go, pkg/cosi/provisioner.go, pkg/namespacestore/namespacestore.go, pkg/nb/rpc_ws.go, pkg/obc/provisioner.go, pkg/system/reconciler.go, pkg/util/kms/test/dev/kms_dev_test.go, pkg/util/kms/test/ibm-kp/kms_ibm_kp_test.go
- Using `golangci-lint` for lint in the Makefile target
- Adding `.golangci.yml` as a configuration file
- Fixing some lint errors
1.  run `make lint`
=> CI | Using golangci-lint for lint in the Makefile target

deploy/role_binding_core.yaml, pkg/bundle/deploy.go
The PR removes hardcoded namespace from rolebinding. Without this, core pod loses its elevated privileges ultimately failing to perform internally some kubectl operations (eg. required to get connection details).
=> Remove hardcoded namespace from rolebinding

pkg/diagnostics/diagnostics.go, pkg/diagnostics/report.go
1. The CLI command checks and logs the values of essential environment variables related to proxy configuration (HTTP_PROXY, HTTPS_PROXY, NO_PROXY). It performs the following actions:
Checks: Verifies if these proxy environment variables are set and not empty.
This implementation currently focuses on proxy environment variables but is designed with future expansion in mind. Additional checks and diagnostics will be introduced in the future.
1. BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2302136
1. Try running noobaa cli  command `noobaa diagnostics report` to check the proxy status. 
**Note:** Use the command `kubectl set env deployment/noobaa-operator -c noobaa-operator HTTP_PROXY=localhost:8080` to update the proxy vars.
=> Added a CLI sub-command in noobaa diagnostics to print proxy details

pkg/backingstore/reconciler.go
1.  When we upgrade between versions with NOOBAA_LOG_COLOR from one with none. it's possible that the pod won't have this env var and will return null, in this case we will get segmentation fault
2. fixed to check if null; if so, don't check the value.
1. 
1.
=> NOOBAA_LOG_COLOR  - Add check env var is not null

pkg/bucket/bucket.go, pkg/nb/types.go, pkg/noobaaaccount/noobaaaccount.go, pkg/noobaaaccount/reconciler.go, pkg/util/util.go
1. Updated forceMd5Etag to a Boolean Pointer Type (*bool): The forceMd5Etag flag is now handled as a pointer to a boolean (*bool) to explicitly track whether the flag was provided by the user:
- If the flag was set, forceMd5Etag points to a true or false value. 
- If the flag was not set, forceMd5Etag remains nil, preventing unintended changes to the ForceMd5Etag field.
1. Improvement: #1215 
2. BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2312533
1. Try creating and updating the bucket using cli.
2. Try creating and updating the NoobaaAccount using cli and yaml both.
=> Updated forceMD5Etag to boolean pointer type

pkg/diagnostics/report.go
1. Printing overriden  vars in  cli command `noobaa diagnostics report`.
Output:
1. After installing noobaa try running `noobaa diagnostics report` cli command to check the status.
=> Printing overrided  vars in  cli command `noobaa diagnostics report`

deploy/olm/noobaa-operator.clusterserviceversion.yaml, pkg/bundle/deploy.go
1. Update Noobaa operator CSV to install on all Namespaces
2. OCS client operator has a dependency on Noobaa operator, but noobaa operator doesn't allow to install on all namespaces.This patch fixes the above
1. https://bugzilla.redhat.com/show_bug.cgi?id=2314211
1. Noobaa operator should get installed on all namespaces
=> Add support for AllNamespaces install mode

deploy/internal/service-db.yaml, pkg/bundle/deploy.go
1. Without this on GKE we don't get the DNS name of the pod created `noobaa-db-pg-0.noobaa-db-pg.<namespace>.svc`
2. see https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields
3. see https://kubernetes.io/docs/concepts/services-networking/service/#headless-services
4. For some reason on Openshift this works also for non-headless service, but on GKE it won't generate the DNS for the pods unless it's headless (see with kubectl get endpointslices).
1. Fixes #432
1. Deploy on GKE
=> Fix #432: Change db service to headless needed to get direct pod dns name on GKE

.github/workflows/golangci-lint.yml
Removing golangci-lint-action in favor or make lint
=> Removing golangci-lint-action in favor or make lint

pkg/util/util.go
1. Update AWS regions - add `ap-southeast-5` (it was added lately, see [here](https://aws.amazon.com/blogs/aws/now-open-aws-asia-pacific-malaysia-region/)).
1. Update AWS regions.
1. none
=> Fix Bug BZ 2320939 | Update AWS Regions

deploy/internal/deployment-endpoint.yaml, deploy/internal/statefulset-core.yaml, deploy/operator.yaml, doc/dev_guide/create_aws_role.sh, doc/dev_guide/troubleshoot_sts_cluster.md, pkg/bundle/deploy.go
1. In PR #1391 the service account name of `statefulset-core.yaml` was changed from "noobaa" to 'noobaa-core" (see [here](https://github.com/noobaa/noobaa-operator/pull/1391/files#diff-d3a8aafe07a48415e712a53978cd91e809e3f05496824cdea7f2948e2b2fd951L24)), hence we update the existing docs  related to AWS STS.
2. Added a comment near the service account name, in case someone would change it so it would know that there additional actions and impact on users of existing deployed AWS STS clusters for this change.
3. Added a section in the troubleshooting for such case, or for partial trust policy (that doesn't have the new service account).
1. Was raised as a part of [BZ 2322124](https://bugzilla.redhat.com/show_bug.cgi?id=2322124).
2. GAP - worth improving the of the variables name in the …
=> Docs | STS | Update Docs (Noobaa Core Service Account Name Changed)

README.md, pkg/bundle/deploy.go, version/version.go
[5.16] Bumping version from 5.16.3 to 5.16.4
=> [5.16] Bumping version from 5.16.3 to 5.16.4

.github/workflows/golangci-lint.yml, .golangci.yml, Makefile, pkg/backingstore/backingstore.go, pkg/bucketclass/bucketclass.go, pkg/cosi/provisioner.go, pkg/install/install.go, pkg/namespacestore/namespacestore.go, pkg/nb/rpc_ws.go, pkg/noobaaaccount/noobaaaccount.go, pkg/obc/obc.go, pkg/obc/provisioner.go, pkg/system/reconciler.go, pkg/util/kms/test/dev/kms_dev_test.go, pkg/util/kms/test/ibm-kp/kms_ibm_kp_test.go
1. [Backport into 5.17] CI | Fixing deprecated linter
=> [Backport into 5.17] CI | Fixing deprecated linter

pkg/diagnostics/report.go
1. Added ARN checks in the diagnostics report for both backingstores and namespacestores having AWS STS ARN string.
1. 
1. Try running command `noobaa diagnostics report` to see the output.
=> Added ARN checks in the diagnostics report

pkg/system/phase2_creating.go, pkg/util/kms/kms_vault.go, pkg/util/kms/kms_version.go, pkg/util/kms/test/dev/kms_dev_test.go, pkg/util/kms/test/tls-sa/kms_tls_sa_test.go, pkg/util/kms/test/tls-token/kms_tls_token_test.go
This PR adds support for key Rotation for Vault KMS.
=> kms: Root key rotation for Vault KMS

pkg/bucket/bucket.go, pkg/nb/api.go, pkg/nb/types.go
1. After changing the api for list buckets, we need to update operator to support it as well otherwise nb api will fail listing the buckets
2. Adding the new params to the API
3. updating the list bucket nb cli command to support the new params
1. Fixed https://issues.redhat.com/browse/DFBUGS-822
1. run the scenario in the bug: noobaa-cli bucket list
2. make sure you see the buckets and no schema errors appear
=> Adapting operator to new bucket list API change

pkg/bucketclass/bucketclass.go, pkg/obc/obc.go, test/cli/test_cli_functions.sh
While deleting OBC or Bucketclass which does not exist, we should display an error message and should not silently give success.
https://issues.redhat.com/browse/DFBUGS-201
As part of this I have also modified test_cli_functions.sh
Test under "delete_namespacestore_path" function was failing because we do not have a bucket which we are trying to delete. It was passing silently. In this function we are fetching the list of bucketclass and obc freshly and deleting those objects. I think that should cover the cases.
=> Noobaa/Operator: Display error message

pkg/bucketclass/bucketclass.go, pkg/obc/obc.go, test/cli/test_cli_functions.sh
While deleting OBC or Bucketclass which does not exist, we should display an error message and should not silently give success.
Signed-off-by: Ashish Pandey <aspandey@redhat.com>
(cherry picked from commit 553c49674a0e20b2fb566915278a5b2ab4009ea2)
1. https://issues.redhat.com/browse/DFBUGS-201
=> [Backport into 5.18] Noobaa/Operator: Display error message

pkg/system/phase2_creating.go
1. For bucket logging and bucket notification, we allocate a pvc from cephfs (if no explicit pvc was specified).
The check for whether there's already a pvc was wrong.
1. https://issues.redhat.com/browse/DFBUGS-988
2. https://issues.redhat.com/browse/DFBUGS-991
1. See bugs for reproduction scenario
=> bucket notification - check pvcName, not pvc DFBUGS 988, 991

deploy/cluster_role.yaml, pkg/bundle/deploy.go, pkg/util/util.go
1. Root Cause: The problem arises when the AWS cluster region cannot be determined from node names, especially in cases where the node naming convention does not include the region or when the DHCP option modifies DNS settings, causing standard parsing methods to fail.
2. Solution: To resolve this, the solution first attempts to fetch the region directly from the cluster configuration, which is the most reliable source. If this fails, it falls back to parsing the region from the node name.
1. Bug: https://issues.redhat.com/browse/DFBUGS-747
1. Install noobaa operator on AWS cluster and check for default backingstore creation with DHCP option set and not set.
=> Bug-fix for fetching region from AWS cluster obj in GetAWSRegion()

pkg/system/phase2_creating.go
1. Backport of https://github.com/noobaa/noobaa-operator/commit/88aef436a298b16f86526a2d76d246705926cd66 to 5.18
1. https://issues.redhat.com/browse/DFBUGS-988 and 991.
1.
=> [Backport into 5.18] bucket notification - check pvcName, not pvc DFBUGS 988, 991 (#1485)

pkg/system/phase2_creating.go
1. Simplify connect file mount path.
1. All connect files are now in one directory instead of each connect file in its own directory.
=> Bucket Notification - connect filename simplification

pkg/system/phase2_creating.go
This 5.18 commit is a backport of 84fd834356b221504c2607f697b071cb8d547fbe.
=> BACKPORT Bucket Notification - connect filename simplification (#1494)

pkg/system/azure_utils.go
1. updated storage account to version 2
1. storage v1 is marked as legacy type from [Microsoft](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview#legacy-storage-account-types) 
1.
=> [azure] updated storage version.

pkg/backingstore/reconciler.go
We need to allow to modify the matchLabel of
topologySpreadConstraints for noobaa's backingstore pods.
https://issues.redhat.com/browse/DFBUGS-277
Testing -
1 - Create a backing store.
2 - Check the label for backingstore and also the pod
kubectl get backingstore my-backingstore -o yaml
kubectl describe pod my-backingstore-noobaa-pod-c2348d65
3 - 
Change the label of a backingstore object like this -
kubectl label backingstore my-backingstore  backingstore=noobaa-new --overwrite
This will trigger the reconciliation and the pod will be reinitialize and now have a "backingstore=noobaa-new" as label
=> Noobaa/Backingstore : Need facility to change labels

Makefile
Without setuptools, running operator-courier fails with:
```
Traceback (most recent call last):
File "/Users/zregvart/work/croz/noobaa/noobaa-operator/build/_output/venv/bin/operator-courier", line 5, in <module>
from operatorcourier.cli import main
File "/Users/zregvart/work/croz/noobaa/noobaa-operator/build/_output/venv/lib/python3.13/site-packages/operatorcourier/cli.py", line 2, in <module>
import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
make: *** [gen-olm] Error 1
```
1. Adds installation of setuptools python package
1. n/a
1. run `make` on brand new python setup
=> Also install setuptools

pkg/system/phase2_creating.go
1. Change mount path of connection secret to include name of secret.
1. Allow multiple secrets to be configures in NooBaa crd spec under bucketNotifications.connections.
https://issues.redhat.com/browse/DFBUGS-1481
1. Configure two connections in bucketNotifications.connections.
=> bucket notifications - connect mount should be unique

pkg/system/phase4_configuring.go
1. Since PR https://github.com/noobaa/noobaa-core/pull/8667 the endpoint validate the new notifications conf before applying the change to DB. This means we need the connect files also in endpoint.
1. put bucket notifications stopped working in containerized after above PR was merged.
1. Simple put bucket notification scenario.
=> bucket notifications - need connect files also in endpoint for put bucket notif

pkg/system/phase4_configuring.go
1. This PR fixes a lint failure with The latest golangci-lint
2. fixes error 
```
should omit nil check; len() for nil slices is defined as zero (gosimple)
```
1. 
1.
=> fixed lint error

Makefile, build/gen-odf-package.sh, pkg/cnpg/cnpg.go, pkg/olm/olm.go
1. Added Cloudnativ-pg resources in noobaa CSV
- Added cnpg deployment and permissions to CSV InstallStrategy
- Added cnpg CRDs to noobaa owned CRD list
2. olm.go code cleanup
3. Refactored cnpg.go
- Simplified CnpgResources struct by holding one instance for each resource (besides CRDs) instead of holding it in a slice.
- Filter out canned cluster roles that are unnecessary for noobaa.
- limited the scope of the operator to a single namespace
- Reduced unnecessary cnpg operator permissions. Moved most of the cluster rules to a namespace-scoped role
- Configured WATCH_NAMESPACE for the operator so it will not watch the entire cluster.
- Added cluster role for non-OLM deployments to allow modifying the admissions webhooks (required by the cnpg operator).
1. 
1.
=> Integrated Cloudnative-pg into OLM package

build/gen-odf-package.sh
To fix noobaa-operator nightly build, for now removed the cnpg-image param inside `gen-odf-package.sh`. We will restore it once we have an upstream build of noobaa variant of cnpg-operator.
1. 
1.
=> temporarily remove cnpg image from gen-odf-package.sh

.github/workflows/build-cnpg.yml, .github/workflows/manual-build.yml
Add GitHub workflow that builds a customized version of CloudNative PostgreSQL (CNPG) operator. The workflow:
- Allows selection of CNPG version tag (default v1.25.0)
- Modifies API group references from postgresql.cnpg.io to postgresql.cnpg.noobaa.io
- Builds and pushes a custom Docker image to Quay.io repository
- Uses manual trigger via workflow_dispatch
This enables NooBaa to maintain a customized version of the CNPG operator with necessary API group modifications.
1. Manually dispatch the workflow
=> Add workflow to build custom CNPG operator image

build/gen-odf-package.sh, pkg/cnpg/cnpg.go, pkg/olm/olm.go
- Added the env "WEBHOOK_CERT_DIR" to the
- In gen-odf-package.sh - allow the cnpg-image to be optional. if not passed, cnpg will not be included in the csv.
1. 
1.
=> Fixes for OLM deployments

build/gen-odf-package.sh
1. Use different quotes for entire cmd and single commands inside it to support env vars with space.
1. 
REPLACES="has space" OBC_CRD=none MANIFESTS=MA CSV_NAME=CS CORE_IMAGE=CO PSQL_12_IMAGE=PS DB_IMAGE=DB OPERATOR_IMAGE=OP COSI_SIDECAR_IMAGE=CO ./build/gen-odf-package.sh 
--obc-crd=none
=> gen_odf - quote with single quote

doc/bucket-notifications.md
1. Add documentation for the Bucket Notifications feature for the operator - changes in CRD and how connection secrets are handled.
=> Bucket Notifications - docs

go.mod, go.sum
update `golang.org/x/oauth2` to avoid CVE
=> Update `golang.org/x/oauth2` to avoid CVE

pkg/noobaaaccount/reconciler.go
1. Currently the noobaa account  secret created for storageconsumer doesnot have 
AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY.
2. This is required for noobaa object browser to be able to connect to remote s3 endpoint via proxy
1. https://issues.redhat.com/browse/RHSTOR-6903
1.  Create a noobaa account with this annotation `remote-client-noobaa: "true" `
2. Check the noobaa account secret created
3. It should have auth_token mgmt_url and AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY.
=> Add AWS_ACCESS_KEY_ID & AWS_SECRET_ACCESS_KEY to noobaa-account secret

pkg/controller/obc/obc_controller.go, pkg/obc/provisioner.go, test/cli/test_cli_functions.sh
1.  Added a mechanism to detect label changes in OBCs and trigger a custom function whenever an update occurs. This ensures that label modifications are automatically recognized and handled without requiring a full reconciliation.
1. Fixed: https://issues.redhat.com/browse/DFBUGS-1615
1.  `make test-cli-flow`
=> Added a fix to update bucket tagging when OBC labels are updated

go.mod, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/cnpg/cnpg.go, pkg/install/install.go, pkg/system/db_reconciler.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go, pkg/system/system.go
- When upgrading from a deployment with an existing DB, provide the DB details in the cluster CR, to perform data import.
- Upgrade flow is as follows:
- If DB sts exist:
- Stop core\endpoints pods
- Create a cnpg cluster with import details in the CR
- The cnpg operator will start the first instance and deploy an import job to import the data. After the import is completed, the second instance will started.
- Wait for cluster to complete import and become Ready
- Once ready scale down the noobaa-db-pg sts to 0 replicas.
- The reconciliation will wait for the cluster to be ready, and a temp error is returned until it is.
- The old sts is not deleted, to have it around for backup. In future versions we should cleanup all the leftovers.
- Updated `noobaa upgrade` command in noobaa cli, to …
=> Implemented data import from the old DB to the cluster on upgrade

pkg/olm/olm.go
1. the configmap is required by cnpg operator to start the instances pods
2. write the CM yaml to the manifests dir when generating a bundle.
1. 
1.
=> Added cnpg-default-monitoring configmap to opeartor bundle

pkg/system/phase4_configuring.go
1. Add an env variable for each nsfs nsr mount.
This way endpoints have a way to tell whether an nsr (that they get from system store) should be mounted or not.
1. 
1. Reduce config.NAMESPACE_MONITOR_DELAY to 1000ms.
2. Create nsfs nsr
3. nsr should not be rejected (by endpoints existing before its creation).
=> nsfs - add mounted nsr name to env. DFBUGS-153

deploy/crds/noobaa.io_noobaas.yaml, pkg/apis/noobaa/v1alpha1/noobaa_types.go, pkg/bundle/deploy.go, pkg/options/options.go, pkg/system/phase2_creating.go, pkg/system/system.go
1. Added logic to disable the creation of routes based on the `DisableRoutes` flag. If the flag is set to true, the route creation is skipped, ensuring that routes are only created when necessary, based on the flag value. This allows more control over whether routes are deployed in the cluster.
1.  JIRA: https://issues.redhat.com/browse/RHSTOR-7195
1. Manual testing instructions:
-  Need ocp cluster as routes supported by openshift (use cluster-bot).
-  Install ODF and create storage system.
-  Update the operator image (latest including the changes) everywhere in the below csv:
`$ oc edit csv mcg-operator.v4.18.1-rhodf` (please use image from quay/docker)
-  Update the noobaa CRD using below command:
`$ oc apply -f noobaa-operator/deploy/crds/noobaa.io_noobaas.yaml`
-  Edit noobaa …
=> Added a flag DisableRoutes to manage openshift routes in noobaa

pkg/cli/cli_suite_test.go, pkg/cli/cli_test.go, pkg/namespacestore/namespacestore.go
1. Block NSS creation when SignatureVersion v4 and endpoint non-secure and return with error.
2. Setting signature version v2 for non-secure endpoint to avoid body content sign in. With secure request body sigin is disabled by [default.](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Config.html#s3DisableBodySigning-property)
No change for Backingstore since uploadPart upload(Non-file stream) is not supported by backingstore. 
1. https://issues.redhat.com/browse/DFBUGS-1035
NSS is in rejected state because the endpoint provided is non-secure and CLI is adding signature version to the endpoint request when try to access data this is creating issue in aws-sdk
related Github issue: https://github.com/aws/aws-sdk-js/issues/965
1. go test ./pkg/cli/
=> Block NSS creation when  SignatureVersion v4 and endpoint non-secure

deploy/internal/configmap-postgres-db.yaml, deploy/internal/statefulset-postgres-db.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go
- mount a memory based volumen for `/dev/shm`
- extend `terminationGracePeriodSeconds` to 70 seconds
- configure `pg_stat_statements.track = all` to track all types of queries when enabled.
1.  https://issues.redhat.com/browse/DFBUGS-2458
1. after upgrade, check noobaa-db-pg statefulset and verify the following:  
- There is a volume and volume mounts for `/dev/shm`
- `terminationGracePeriodSeconds` is 70 
- check that the configmap `noobaa-postgres-config` contains the line `pg_stat_statements.track = all`
=> postgres setup enhancements

deploy/internal/configmap-postgres-db.yaml, deploy/internal/statefulset-postgres-db.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go
- mount a memory based volumen for `/dev/shm`
- extend `terminationGracePeriodSeconds` to 70 seconds
- configure `pg_stat_statements.track = all` to track all types of queries when enabled.
(cherry picked from commit 1027adec78fd920323c87bf804284437fd7d309c)
1. 
1. 
1.
=> [Backport to 5.16] postgres setup enhancements

deploy/internal/configmap-postgres-db.yaml, deploy/internal/statefulset-postgres-db.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go
- mount a memory based volumen for `/dev/shm`
- extend `terminationGracePeriodSeconds` to 70 seconds
- configure `pg_stat_statements.track = all` to track all types of queries when enabled.
(cherry picked from commit 1027adec78fd920323c87bf804284437fd7d309c)
1. 
1. 
1.
=> [Backport to 5.17] postgres setup enhancements

deploy/internal/configmap-postgres-db.yaml, deploy/internal/statefulset-postgres-db.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go
- mount a memory based volumen for `/dev/shm`
- extend `terminationGracePeriodSeconds` to 70 seconds
- configure `pg_stat_statements.track = all` to track all types of queries when enabled.
(cherry picked from commit 1027adec78fd920323c87bf804284437fd7d309c)
1. 
1. 
1.
=> [Backport to 5.15] postgres setup enhancements

deploy/internal/deployment-endpoint.yaml, deploy/internal/statefulset-core.yaml, pkg/bundle/deploy.go, pkg/options/options.go, pkg/system/db_reconciler.go, pkg/system/phase2_creating.go, pkg/system/phase4_configuring.go
1. Passing postgres secret as a vol mount instead of env
2. Changed core image to `noobaa/noobaa-core:master-20250518`
1. https://issues.redhat.com/browse/DFBUGS-1466
1. install noobaa
2. noobaa-core statefulset and noobaa-endpoint deployments should not contain the envs for postgres connection details.
=> Passing postgres secret as a vol mount instead of env

deploy/internal/Dockerfile.postgres, deploy/internal/scripts/db-crash-collector.sh, deploy/internal/scripts/run-postgresql-wrapper.sh, deploy/internal/statefulset-postgres-db.yaml, pkg/bundle/deploy.go, pkg/system/phase2_creating.go
This code enhances our PostgreSQL container with comprehensive logging and crash diagnostics. It will not be merged, it is only here for public access and review as part of our debugging efforts for [issue 2414](https://issues.redhat.com/browse/DFBUGS-2414). It introduces two key scripts:
1. run-postgresql-wrapper.sh
- Captures all stdout/stderr from PostgreSQL startup and runtime and saves it into logs on the DB PV
- Logs to timestamped files in /var/lib/pgsql/diagnostics/
2. db-crash-collector.sh
- Collects a snapshot of the environment upon crashing
- Saves termination logs, PostgreSQL configs, environment variables, and process list
There are two flows -
The first is executed on startup. It wraps the Postgres' pod [original CMD and …
=> [Review only] Save DB diagnostics for CLBO debugging

pkg/util/kms/kms_kmip.go, pkg/util/kms/kms_kmip_storage.go, pkg/util/kms/kms_version.go
1.  As some KMIP doesn't support any CryptographicLength, we will revert to saving only one key in KMIP. Once we want to support rotating secrets, we will need to find a better solution
(cherry picked from commit 5b3aa9edaf290fa7452588075b8ead431c862a81)
1. 
1.
=> [Backport to 5.19] Fixing KMIP issues

README.md, pkg/bundle/deploy.go, pkg/util/util.go, version/version.go
- Update AWS Regions with ap-east-2
(cherry picked from commit 376fc5337430b99887212f989effe8380b27c778)
1. https://issues.redhat.com/browse/DFBUGS-2915
=> [Backport into 5.19] Update AWS Regions with ap-east-2

pkg/system/db_reconciler.go
1. when checking if the cluster spec is changed, the `Spec.Affinity` field was not checked.
2. This is already fixed in master as part of other changes, and should be fixed in 4.19 only.
1. https://issues.redhat.com/browse/DFBUGS-3797 
1.
=> [Direct to 5.19] Check if Spec.Affinity is changed in wasClusterSpecChanged
