deploy/internal/statefulset-core.yaml
pkg/cli/cli.go
pkg/nb/api.go
pkg/pvstore/pvstore.go
pkg/system/reconciler.go

Add CLI control for pvstore (hosts_pool). For now, initial control - create & list only.

Add pvstore control from CLI

---

pkg/olm/olm.go

command: olm csv yaml

---

pkg/backingstore/reconciler.go

Fixing name of BackingStore in an error message

BackingStore : Fixing error message 

---

.travis.yml
Makefile
deploy/crds/noobaa_v1alpha1_noobaa_crd.yaml
deploy/olm-catalog/package/noobaa-operator.package.yaml
deploy/olm-catalog/package/noobaa-operator.v1.1.1.clusterserviceversion.yaml
deploy/operator.yaml
go.mod
go.sum
pkg/apis/noobaa/v1alpha1/noobaa_types.go
pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
pkg/apis/noobaa/v1alpha1/zz_generated.openapi.go
pkg/olm/olm.go
pkg/options/options.go
pkg/system/phase2_creating.go
pkg/system/system.go
version/version.go

1. CLI fix to avoid install error when STS is not ready
2. NooBaa.Spec.DBVolumeResources for overriding the default volume size

v1.1.1 fixes version

---

pkg/obc/provisioner.go

* when `create_account` does not return access keys (noobaa core version 5.0), the OBC provisioner failed to provision a bucket and got stuck in an infinite loop of creating new accounts.
* fixed so that if access keys are not returned in `create_account` then `read_account` is used to get the keys.
* Fixes #50

fix for cases where create_account doesn't return access keys

---

deploy/internal/service-monitor.yaml
deploy/role.yaml
pkg/system/phase2_creating.go
pkg/system/phase4_configuring.go
pkg/system/reconciler.go

In order to recognize NooBaa as a target in Prometheus.
Fixes #41
https://bugzilla.redhat.com/show_bug.cgi?id=1748465

Addition of ServiceMontior

---

go.mod

this fixes conflicts in OCS operator

changed prometheus operator version in go.mod to 0.29.0

---

cmd/manager/main.go
main.go
pkg/cli/cli.go

return non-zero exit code on error

---

doc/noobaa.1

Adding simple man page (it's a rpmlint require)

Adding simple man page

---

pkg/backingstore/backingstore.go
pkg/bucketclass/bucketclass.go
pkg/cli/cli.go
pkg/diagnose/diagnose.go
pkg/util/util.go

Added diagnostics option to the CLI of the operator.

Addition of diagnostics option to CLI

---

README.md
deploy/operator.yaml
pkg/bundle/deploy.go
pkg/options/options.go
version/version.go

Bump operator and core versions

Bump operator and core versions

---

README.md
deploy/operator.yaml
pkg/bundle/deploy.go
pkg/options/options.go
version/version.go

bump operator version to 2.0.8

bump operator version

---

README.md
deploy/internal/statefulset-core.yaml
deploy/operator.yaml
doc/backing-store-crd.md
doc/bucket-class-crd.md
pkg/backingstore/reconciler.go
pkg/bucketclass/reconciler.go
pkg/bundle/deploy.go
pkg/cli/cli.go
pkg/nb/api.go
pkg/nb/rpc.go
pkg/options/options.go
pkg/system/cmd_api_call.go
pkg/system/reconciler.go
pkg/system/system.go
version/version.go

Backport to 2.0

---

.travis.yml
Makefile
pkg/options/options.go
test/cli/test_cli_flow.sh
test/cli/test_cli_functions.sh

Create test cli flow for travis

Create test cli flow for travis

---

deploy/cluster_role.yaml
deploy/internal/service-db.yaml
deploy/internal/statefulset-core.yaml
deploy/internal/statefulset-db.yaml
pkg/bundle/deploy.go
pkg/system/phase2_creating.go
pkg/system/reconciler.go
pkg/system/system.go

1. added statefulset-db, and moved the relevant parts from statefuleset-core to it.
2. added db-pod and service-db to support the changes.
1.
1.

Split DB to separate pod

---

pkg/backingstore/reconciler.go
pkg/util/util.go

google cloud bug fixes

---

pkg/bucketclass/reconciler.go
pkg/nb/api.go
pkg/nb/types.go

bucketclass reconciler will update the BE with the edits of the bucketclasses and change the relevant tiering policies and tiers
Fixes #59

Addition of bucketclass edit reconciler

---

pkg/apis/noobaa/v1alpha1/zz_generated.openapi.go
pkg/bundle/deploy.go

gen-api after version bump

---

pkg/backingstore/backingstore.go

Fixing CLI errors handling for CreatePVPool on illegal values

Fixing error handling for CreatePVPool on illegal values

---

pkg/options/options.go
pkg/system/system.go
test/cli/test_cli_functions.sh

- Add mini flag and enforce low pod resource usage when used
- Update CLI tests to use the mini flag

Support --min option in NooBaa CLI to be used in low resource environments 

---

pkg/olm/olm.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1785906

Fix Display Names for CRDs

---

deploy/internal/service-db.yaml
pkg/bundle/deploy.go
pkg/system/phase2_creating.go

* changed db service from NodePort to ClusterIP (internal only)
* fixed MONGODB_URL env in core statefulset

changed db service from NodePort to ClusterIP 

---

pkg/obc/obc.go
pkg/obc/provisioner.go
pkg/system/system.go

OBC provisioner will set BUCKET_HOST to the s3 service internal DNS

---

README.md
pkg/bundle/deploy.go
pkg/olm/olm.go
pkg/options/options.go
version/version.go

Reverts noobaa/noobaa-operator#197

Revert "Backport: olm.go tolerations descriptor fix"

---

pkg/bucketclass/reconciler.go
pkg/nb/api.go
pkg/nb/types.go

On BE errors, BE will now decide and send the desired bucket-class tiering structure back to the operator
BE side is here: https://github.com/noobaa/noobaa-core/pull/5876

Operator get revert instruction from BE

---

pkg/nb/api.go
pkg/nb/types.go
pkg/options/options.go
pkg/system/phase3_connecting.go
pkg/system/phase4_configuring.go

Also, support the NBClient for remote deployments
and bump noNooBaa core image reference

Report on endpoint group config changes to the core

---

pkg/backingstore/backingstore.go
pkg/backingstore/reconciler.go
pkg/nb/types.go
pkg/options/options.go
pkg/pvstore/pvstore.go

1. Send backingstore info when creating cloud/host pool
1. Fixed BZ : #1765866
1.

Fix deletion of pool when it was created as a backingstore - operator side

---

build/catalog-source.Dockerfile
deploy/obc/lib-bucket-provisioner.package.yaml
deploy/obc/lib-bucket-provisioner.v1.0.0.clusterserviceversion.yaml
pkg/bundle/deploy.go

Fixed back lib-bucket-provisioner catalog source version.

Fixed lib-bucket-provisioner catalog source version

---

pkg/system/phase4_configuring.go

should fix BZ https://bugzilla.redhat.com/show_bug.cgi?id=1793189
still needs to be tested

added svc.cluster.local to RGW endpoint

---

deploy/crds/noobaa.io_noobaas_crd.yaml
pkg/apis/noobaa/v1alpha1/noobaa_types.go
pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
pkg/bundle/deploy.go
pkg/nb/types.go
pkg/options/options.go
pkg/system/phase4_configuring.go

- Add the field in the NooBaa spec
- Reconcile the value into an env var used by the endpoints pods

Enable setting region in the noobaa CR spec

---

pkg/backingstore/reconciler.go
pkg/util/util.go
test/cli/test_cli_flow.sh
test/cli/test_cli_functions.sh

Fixes #222 
* use 20GB as default PV size

use default volume size instead of crashing when VolumeResources is not set in backingstore

---

pkg/system/reconciler.go

Added print of memory usage before/after every phase.

Add Memory Usage print

---

pkg/nb/rpc_ws.go
pkg/system/phase3_connecting.go

Added check for correct suffix in RPC client address configuration.

Additional checks in RPC configuration and print fixes

---

pkg/nb/router.go
pkg/nb/rpc_ws.go
pkg/system/phase3_connecting.go
pkg/system/system.go

Backport to 2.1

---

deploy/internal/deployment-endpoint.yaml
deploy/internal/statefulset-core.yaml
pkg/bundle/deploy.go

Added additional variable to disable compression
https://bugzilla.redhat.com/show_bug.cgi?id=1800599

Allow to disable compression

---

pkg/olm/olm.go

1. Added secret.name
1. Fixed BZ #1800541 
1.

add secret.name in backingstore spec descriptor

---

pkg/backingstore/reconciler.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1807941

Check valid PV size

---

pkg/backingstore/reconciler.go

1. replaced in limits check the minimal PV size to be 16G instead of 20Gi . 
1. Fixed BZ #1813655
1.

Fixed minimal pv size check

---

pkg/backingstore/backingstore.go

1. Added validation of maximal number of characters of pv-pool name.
1. Added to error message the maximal size of volumes.
1. Fixed BZ #1813656 & Fixed BZ #1813706
1.

Pv pool bugs fixes 

---

pkg/olm/olm.go

FIxed secrets at olm

---

pkg/olm/olm.go

(cherry picked from commit 384612b4cde9af28d107d003a1ab0a07b1cbc6ad)

Backport to 2.1: secret fixes

---

pkg/olm/olm.go

(cherry picked from commit 384612b4cde9af28d107d003a1ab0a07b1cbc6ad)

Backport to 2.2: secret fixes

---

pkg/backingstore/reconciler.go

* when backing-store references a secret with an empty name, the operator was exiting with panic in `util.KubeCheck`
* validating the secret name in backingstore reconcile. returning persistent error if the name is empty

fixed panic when backing-store references a secret with an empty name

---

README.md
pkg/options/options.go

* updated `options.go`
* updated `README.md`

updated core and operator versions for 2.1.0. release

---

README.md
pkg/bundle/deploy.go
pkg/options/options.go
version/version.go

(cherry picked from commit b74f2331e05c150eba2d0dca831e1159de4d6be0)

updated version and readme for 2.1.1

---

pkg/bucketclass/bucketclass.go
pkg/controller/bucketclass/bucketclass_controller.go

* added map function `MapBackingstoreToBucketclasses` to return a list of bucket classes using a specific backing store
* added `Watch` in `bucketclass_controller` to reconcile bucket class when a connected backing store is updated

added watch on backingstores in bucketclass_controller

---

README.md
pkg/bundle/deploy.go
pkg/options/options.go
version/version.go

Bump version to 2.2.0

---

README.md
pkg/bundle/deploy.go
version/version.go

Bump version to 2.3.0

---

.travis.yml

.travis.yml:
- Added || exit 1 on all scripts calls

Travis: fix to quit immediately after the first script fails

---

Makefile

Adding version to the dependencies in the makefile
Fixes: #294

Adding version to the dependencies in the makefile

---

test/cli/test_cli_flow.sh
test/cli/test_cli_functions.sh

Uninstall cleanup flag added to the flow

Cleanup flag added randomly to test cli flow

---

deploy/crds/noobaa.io_backingstores_crd.yaml
deploy/crds/noobaa.io_v1alpha1_backingstore_cr.yaml
deploy/internal/pod-agent.yaml
deploy/internal/pvc-agent.yaml
pkg/apis/noobaa/v1alpha1/backingstore_types.go
pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
pkg/backingstore/backingstore.go
pkg/backingstore/reconciler.go
pkg/bundle/deploy.go
pkg/controller/backingstore/backingstore_controller.go
pkg/nb/api.go
pkg/nb/types.go
pkg/operator/manager.go
pkg/options/options.go
pkg/pvstore/pvstore.go
pkg/system/system.go
pkg/util/util.go

- operator will add, scale-up and delete pvpools during reconcile
- Add support to getting agent-config from noobaa-core
- Add util command wrapper for kube client DeleteAllOf
- small fixes to backingstore commands

moving pvpool backstore resposibilty to operator

---

deploy/internal/prometheus-rules.yaml
pkg/bundle/deploy.go

Add waiting time for prom alerts

---

deploy/crds/noobaa.io_backingstores_crd.yaml
deploy/crds/noobaa.io_v1alpha1_backingstore_cr.yaml
deploy/internal/deployment-endpoint.yaml
deploy/internal/pod-agent.yaml
deploy/internal/prometheus-rules.yaml
deploy/internal/pvc-agent.yaml
deploy/internal/statefulset-core.yaml
pkg/apis/noobaa/v1alpha1/backingstore_types.go
pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
pkg/backingstore/backingstore.go
pkg/backingstore/reconciler.go
pkg/bundle/deploy.go
pkg/controller/backingstore/backingstore_controller.go
pkg/nb/api.go
pkg/nb/types.go
pkg/operator/manager.go
pkg/options/options.go
pkg/pvstore/pvstore.go
pkg/system/phase2_creating.go
pkg/system/phase4_configuring.go
pkg/system/system.go
pkg/util/util.go

Backport to 2.3

---

pkg/system/reconciler.go

This is another fallout of looking at #309. 
It just struck me that the indentation in `VerifyObjectBucketCleanup()` is unnecessarily deep. This patch reduced it by adding early exits. Look at the patch with `git show -w` to see that it is really minimal. This does not change the behavior at all, just streamlines the code.
Not sure if such a coding style is appreciated in noobaa-operator or not. Just putting it up here for comment.
It is currently based on top of PR #323 since there is a context overlap.

Reduce indentation in VerifyObjectBucketCleanup()

---

README.md
pkg/options/options.go

Bump core image to 5.5.0-rc2

---

README.md
pkg/bundle/deploy.go
version/version.go

Bump version to 5.6.0

---

pkg/system/phase4_configuring.go

(cherry picked from commit 24e34d7e2687c4062fec231abddec81cab32e853)

Backport to 2.2: added tolerations to endpoint spec

---

pkg/backingstore/reconciler.go

1. used PVPoolDefaultStorageClass if it as the storage class for pvc.
1. FIxed BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1850334
1.

Fix default storage class missing problem

---

test/cli/test_cli_flow.sh
test/cli/test_cli_functions.sh

- Add the ability to run a function when reaching the timeout
- Running check_obc when reaching timeout on obc create
- Add timeout to noobaa uninstall
- Add the ability to pass new timeout in sec to timeout function

TEST_CLI | Add the ability to run a function when reaching the timeout

---

pkg/nb/api.go
pkg/nb/types.go
pkg/options/options.go
pkg/system/phase4_configuring.go

Using the new `get_system_status` API to acquire the status of the noobaa system.

Refactor system creation flow.

---

pkg/nb/api.go
pkg/nb/types.go
pkg/options/options.go
pkg/system/phase4_configuring.go

Using the new `get_system_status` API to acquire the status of the noobaa system.
(cherry picked from commit 40a7d2dbd0bbf24c570ffd4d161da927d2e62172)

Backport to 2.2

---

pkg/nb/api.go
pkg/nb/types.go
pkg/options/options.go
pkg/system/phase4_configuring.go

Using the new `get_system_status` API to acquire the status of the noobaa system.
(cherry picked from commit 40a7d2dbd0bbf24c570ffd4d161da927d2e62172)

Backport to 2.3: Refactor system creation flow.

---

pkg/backingstore/backingstore.go

rejecting storage-class of rgw bucket as well as noobaa's obc

---

deploy/crds/noobaa.io_v1alpha1_backingstore_cr.yaml
deploy/crds/noobaa.io_v1alpha1_bucketclass_cr.yaml
deploy/crds/noobaa.io_v1alpha1_noobaa_cr.yaml
pkg/backingstore/reconciler.go
pkg/bucketclass/reconciler.go
pkg/bundle/deploy.go
pkg/system/reconciler.go
pkg/util/util.go

(cherry picked from commit 31896b83a9f3804392a6c9748b81278b32233166)

Remove app label and finalizer from CR templates and add them in code

---

.travis/install-python.sh

- .travis/install-python.sh: Updating pyenv global to 3.7.1

Updating pyenv global to 3.7.1

---

.travis/install-python.sh
pkg/controller/backingstore/backingstore_controller.go
pkg/controller/bucketclass/bucketclass_controller.go
pkg/controller/noobaa/noobaa_controller.go
pkg/operator/manager.go
pkg/util/predicates.go

Also remove manager SyncPeriod time dev code left by accident in the code
(cherry picked from commit 6494c42c043e7e42fd6bf07d69897ea1c4e2c274)

Add predicates to filter out non-relevant events and log relevant events

---

pkg/backingstore/reconciler.go
pkg/bucketclass/reconciler.go
pkg/system/reconciler.go

Fixing BZ https://bugzilla.redhat.com/show_bug.cgi?id=1866781
updateStatus errors wasn't handled (only printed) causing that an error happening while updating the status (just in the end of the the reconcile cycle) to leave the phase not changed until the next reconcile which will never run as no new events will happen (as the backingstore is really in Ready state - just wasn't able to update the CR)

Handle updateStatus errors - so it will cause more future reconciles in case of a failure

---

pkg/backingstore/reconciler.go
pkg/bucketclass/reconciler.go
pkg/system/reconciler.go

Fixing BZ https://bugzilla.redhat.com/show_bug.cgi?id=1866781
updateStatus errors wasn't handled (only printed) causing that an error happening while updating the status (just in the end of the the reconcile cycle) to leave the phase not changed until the next reconcile which will never run as no new events will happen (as the backingstore is really in Ready state - just wasn't able to update the CR)

Handle updateStatus errors - to continue recocnciles on errors

---

pkg/backingstore/reconciler.go
pkg/bucketclass/reconciler.go
pkg/system/reconciler.go

removing the unneeded call to setPhase and adding comments
Signed-off-by: jackyalbo jalbo@redhat.com

Cleanups and fixes to updateStatus - continue of PR#386

---

pkg/controller/backingstore/backingstore_controller.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1867762

Will reconcile on mode change for backingstores

---

deploy/internal/pod-agent.yaml
pkg/backingstore/reconciler.go
pkg/bundle/deploy.go

change with pod delete handling for pvpool

---

deploy/internal/pod-agent.yaml
pkg/bundle/deploy.go

changing default mem req in pvpool pod to 400M

---

pkg/options/options.go

Fixing noobaa core version

---

pkg/olm/olm.go

Signed-off-by: N Balachandran <nibalach@redhat.com>

Fixed typo in crd description

---

pkg/system/phase4_configuring.go

https://bugzilla.redhat.com/show_bug.cgi?id=1876520
reordered the cases where endpoint was not found in the secret

addition to PR #422 - reordered if-else cases

---

pkg/backingstore/reconciler.go

1. Fixed the units of minimal PV size to be in Gi and not in G.
1. BZ #1873220
1.

fixing minimal PV size to be in Gi units and not G

---

deploy/internal/route-mgmt.yaml
pkg/bundle/deploy.go

Adding redirect insecureEdgeTerminationPolicy to management route

---

pkg/diagnose/diagnose.go

1. Added --dir flag for saving the tar file in destination directory.
1. Fixed #435 
1.

Added --dir flag to noobaa diagnose

---

deploy/internal/cloud_creds_gcp_cr.yaml
go.mod
go.sum
pkg/bundle/deploy.go
pkg/system/phase2_creating.go
pkg/system/phase4_configuring.go
pkg/system/reconciler.go
pkg/util/util.go

This is a clone of https://github.com/noobaa/noobaa-operator/pull/392
Signed-off-by: RAJAT SINGH <rajasing@redhat.com>

GCP:Creation of default backing store

---

deploy/internal/cloud_creds_gcp_cr.yaml
go.mod
go.sum
pkg/bundle/deploy.go
pkg/diagnose/diagnose.go
pkg/system/phase2_creating.go
pkg/system/phase4_configuring.go
pkg/system/reconciler.go
pkg/util/util.go

(cherry picked from commit 6159d6a302c4d6470589a3e8b1d6481ab8552dab)
(cherry picked from commit 691bd1ee43c19f94ff6f8d4c545b461573d3f8c6)
Backport to 5.6

Backport to 5.6

---

pkg/backingstore/reconciler.go
pkg/system/phase2_creating.go
pkg/system/phase4_configuring.go

fixing missing affinity for noobaa pods

---

doc/bucket-class-crd.md
doc/namespace-store-crd.md

Initial Design for NamespaceStore CRD and the expansion of bucketclass CRD for supporting namespace feature.

Design of CRD expansion for namespace feature

---

doc/bucket-class-crd.md
doc/namespace-store-crd.md

(cherry picked from commit 93b48f9c79e9fd5f18dd32e8c6055fe2b00d8ea3)

Backport to 5.7: Design of CRD expansion for namespace feature

---

deploy/internal/deployment-endpoint.yaml
deploy/internal/statefulset-core.yaml
pkg/bundle/deploy.go
pkg/options/options.go
pkg/system/phase2_creating.go
pkg/system/reconciler.go

1. Added new secret that would be the Root Key for the new encryption feature. choosing random bytes is only temporary implementation.
1. 
1.

Adding Root secret - dbg

---

pkg/diagnose/diagnose.go

(cherry picked from commit f16609d4441625ee2d93b475fa8b7e301d3c4f69)
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1893624

Backport to 5.6: Created diagnostic tar file directly to the specified dir

---

pkg/backingstore/reconciler.go
pkg/system/phase2_creating.go
pkg/system/phase4_configuring.go

(cherry picked from commit e9dd989112210f0b5a67d2b0e904f01196bc0739)
Fixes 1883828

Backport to 5.6: pod affinity fix

---

README.md
pkg/options/options.go

changed noobaa-core image in options.go to noobaa:5.6.0

---

.github/workflows/testing.yml
.github/workflows/weekly-build.yml

Signed-off-by: Nimrod Becker <bnimrod@gmail.com>
- Push CLI to noobaa-operator-CLI bucket on AWS
- Update version to the latest weekly core built (same data as operator schedule)

[GH Action] Update core image and push CLI

---

README.md
pkg/bundle/deploy.go
version/version.go

Bump version to 5.7.0

---

deploy/crds/noobaa.io_noobaas_crd.yaml
deploy/internal/deployment-endpoint.yaml
deploy/internal/job-upgrade-db.yaml
deploy/internal/statefulset-core.yaml
deploy/internal/statefulset-postgres-db.yaml
deploy/role.yaml
pkg/apis/noobaa/v1alpha1/noobaa_types.go
pkg/bundle/deploy.go
pkg/system/phase2_creating.go
pkg/system/phase4_configuring.go
pkg/system/reconciler.go
pkg/system/system.go
pkg/util/util.go

Migration job between Mongo to Postgres

---

deploy/crds/noobaa.io_noobaas_crd.yaml
deploy/internal/deployment-endpoint.yaml
deploy/internal/job-upgrade-db.yaml
deploy/internal/statefulset-core.yaml
deploy/internal/statefulset-postgres-db.yaml
deploy/role.yaml
pkg/apis/noobaa/v1alpha1/noobaa_types.go
pkg/bundle/deploy.go
pkg/system/phase2_creating.go
pkg/system/phase4_configuring.go
pkg/system/reconciler.go
pkg/system/system.go
pkg/util/util.go

(cherry picked from commit 8f40bc18cd8704b1faf523b6afc30418698e3d7a)

Backport to 5.7

---

deploy/obc/storage_class.yaml
pkg/bundle/deploy.go

- Consumed by OCP UI to describe the storage class

Add annotation to NooBaa storage class to describe it

---

pkg/system/system.go

Signed-off-by: Jenia White <jeniawhite92@gmail.com>
(cherry picked from commit 0898455fa00ef5a2bf4b4c59e2597493f5f1fff3)

Backport to 5.7: Patching dbType on non CLI deploy

---

pkg/namespacestore/reconciler.go
pkg/nb/api.go
pkg/nb/types.go
pkg/options/options.go
pkg/system/phase4_configuring.go

Upgrade namespace CRDs

---

pkg/system/phase4_configuring.go

fix ceph object store user UID check

---

go.mod
go.sum

updated lib-bucket-provisioner version

---

go.mod
go.sum

(cherry picked from commit fa6157122e64446fe4d5a78d11e650c74af0455e)

Backport to 5.7: updated lib-bucket-provisioner version

---

pkg/system/phase2_creating.go
pkg/system/phase4_configuring.go
pkg/system/reconciler.go

better checking system status before migrating
stopping all endpoints before upgrade
throwing temp errors while migration is not finished
adding mergeEnvs to endpoints as well - to get new default env vars

Upgrade additions

---

pkg/controller/namespacestore/namespacestore_controller.go
pkg/namespacestore/reconciler.go
pkg/system/phase4_configuring.go

1. updated namespace store phase by namespace resources mode
2. namespace bucketclass phase will be updated in the bucketclass reconciler according to its namespace stores.

Update namespace store phase by namespace resources mode

---

.github/workflows/weekly-build.yml

weekly-build.yml - Fixed Duplicate id

weekly-build.yml - Fixed Duplicate id

---

.github/workflows/weekly-build.yml

weekly-build:
Fix make image and tag

[GH Actions] weekly-build: Fix make image and tag

---

deploy/internal/prometheus-rules.yaml
pkg/bundle/deploy.go

Update prometheus alerts yaml

---

doc/bucket-class-crd.md

Delete hubPrefix from Docs

---

pkg/system/phase2_creating.go
pkg/system/system.go
pkg/util/util.go

KMS gaps fixes

---

pkg/backingstore/reconciler.go

Change mapping of initializing mode code to creating backingstore phase

---

pkg/backingstore/backingstore.go
pkg/namespacestore/namespacestore.go
pkg/util/util.go

noobaa cli enhancement - Create backingstore and namespacestore by specifying existing secret name

---

pkg/controller/backingstore/backingstore_controller.go
pkg/controller/noobaa/noobaa_controller.go
pkg/util/predicates.go

Add owner filter predicate

---

.github/workflows/weekly-build.yml
Makefile

[GH Action] weekly-build.yml fix the filename

[GH Action] weekly-build.yml fix the filename

---

pkg/system/phase4_configuring.go
pkg/system/reconciler.go

Add non external root key check before calling kubecheck

---

pkg/system/phase2_creating.go
pkg/system/reconciler.go
pkg/util/util.go

Add more delete failed messages on external root key deletion

---

pkg/system/cmd_ui.go

UI command prints the correct mgmt address
Fixes BZ #1928487

UI command prints the correct mgmt address

---

doc/bucket-class-crd.md

Updated bucketclass cli commands in docs

---

pkg/obc/provisioner.go

Fixed stuck in pending OBC NS that couldn't create buckets in DS on internal.
Applied default bucket class to OBC NS with the creation of the tiering policy for the OBC NS.
TODO: Need to see what happens on OBC NS Cache because cannot configure both tiering and namespace in the bucket class, currently using default as well.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1927330

Fixing stuck in pending OBC NS

---

pkg/diagnose/diagnose.go

cli diagnose to collect endpoint logs

---

doc/bucket-class-crd.md

Fix bucketclass docs

---

pkg/system/phase2_creating.go

added log messages to migration process

---

pkg/obc/provisioner.go

instead of delete_bucket_and_objects which isn't relevant for ns
fix BZ1932400

namespace bucket will be normally  deleted

---

pkg/diagnose/diagnose.go

Add db pods to cli diagnose command

---

pkg/install/install.go
pkg/system/system.go

CLI Install show db image

---

.github/workflows/run_ci.yml

[GH Action] Running Generate API before Build

[GH Action] Running Generate API before Build

---

.github/workflows/run_ci.yml

[GH Actions] Fix GOROOT

---

deploy/scc.yaml
pkg/bundle/deploy.go
pkg/operator/operator.go
pkg/util/util.go

Will create Noobaa SCC if not found and SCC CRD exist
Added option to uninstall SCC by running: ```noobaa uninstall --cleanup ```

Creating Noobaa SCC when installing using cli

---

pkg/system/phase2_creating.go
pkg/system/phase4_configuring.go
pkg/system/reconciler.go
pkg/util/util.go

Signed-off-by: Ambika Nair <ambiknai@in.ibm.com>

Backport to 5.6: In IBM Cloud if COS cred secret is missing use pv-pool for default

---

pkg/obc/provisioner.go
test/cli/test_cli_functions.sh

Cache OBC - We wont try to create tiering policy twice

---

pkg/obc/provisioner.go
test/cli/test_cli_functions.sh

fix to 1937768
(cherry picked from commit e0279d9c92106d71486303917fa6b10d08c58a56)

Backport to 5.7: Cache OBC - We wont try to create tiering policy twice

---

deploy/internal/deployment-endpoint.yaml
pkg/bundle/deploy.go
pkg/system/phase4_configuring.go

necessary for logs collection by must-gather
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1894378

added app=noobaa label to endpoint pods

---

pkg/util/util.go

(cherry picked from commit 680080a8348789b4f6de931f5cb36381eb17ea3e)

Backport to 5.7: fix kms - missing backend path field

---

.travis/install-minikube.sh

Bumped minikube from v1.8.2 to v1.18.1
Bumped kubernetes from v1.17.3 to v1.20.2

Bumped the minikube version from v1.8.2 to v1.18.1

---

README.md
pkg/options/options.go

* changed ContainerImageTag to 5.7.0
* fixed versions in README

changes for 5.7.0 release

---

pkg/bucketclass/reconciler.go
pkg/nb/types.go
pkg/obc/provisioner.go
pkg/options/options.go

* need to update noobaa core image after core changes will be merged.

Fixed create bucket call - namespace bucket config

---

.github/workflows/manual-build.yaml

Signed-off-by: Nimrod Becker <bnimrod@gmail.com>

Add initial manual build workflow

---

.github/workflows/manual-build.yaml

Signed-off-by: Nimrod Becker <bnimrod@gmail.com>

fix name of workflow

---

.github/workflows/manual-build.yml

Signed-off-by: Nimrod Becker <bnimrod@gmail.com>

fix indent

---

deploy/internal/deployment-endpoint.yaml
pkg/bundle/deploy.go
pkg/system/phase4_configuring.go

changes for OCS-4.8. revert some of the changes done for NSFS
- changed service account to noobaa
- removed the requested securityContext
fixes bz https://bugzilla.redhat.com/show_bug.cgi?id=1952344

changed noobaa-endpoint security context

---

pkg/system/phase2_creating.go

Signed-off-by: Evgeniy Belyi <jeniawhite92@gmail.com>
(cherry picked from commit bb34314602244f67380bc8a895bf12515d50ab88)

Addition of labels to reconcile after upgrade from last version

---

.github/workflows/manual-build.yml
.travis/upload-s3-object-using-curl.sh

[GH Action] upload the cli using curl into s3

[GH Action] upload the cli using curl into s3

---

pkg/system/phase4_configuring.go

Undoing unneeded change to container security context

---

pkg/system/phase4_configuring.go

Fix wrong namespace stores types when creating from upgrade 

---

README.md
pkg/bundle/deploy.go
version/version.go

Bump version to 5.9

---

pkg/obc/provisioner.go

- let the library decide if deletion is necessary.
- warn if ob has a ReclaimPolicy != Delete
(cherry picked from commit 0ca913eb48f1fdbc12e176d4b26a3a83c27e85fa)

Backport to 5.7 - ignore ReclaimPolicy in provisioner Delete implementation

---

go.mod
go.sum

Change go mode directive to go 1.15

Change go mode directive to go 1.15

---

pkg/backingstore/backingstore.go
pkg/bucket/bucket.go
pkg/bucketclass/bucketclass.go
pkg/cli/cli.go
pkg/namespacestore/namespacestore.go
pkg/obc/obc.go
pkg/options/options.go
pkg/pvstore/pvstore.go

This reverts commit 1d4db95f3a30f056b46bfe573a7329d96202c015.

Revert "Generate an error if a user wrongly inputs options with –"

---

pkg/system/reconciler.go

Checking Service "noobaa-db" only if we use mongo
(cherry picked from commit 36a07deed625ff587dfa82bd2b116316f19df249)

Backport to 5.8

---

pkg/backingstore/backingstore.go
pkg/bucket/bucket.go
pkg/bucketclass/bucketclass.go
pkg/cli/cli.go
pkg/crd/crd.go
pkg/diagnose/diagnose.go
pkg/install/install.go
pkg/namespacestore/namespacestore.go
pkg/obc/obc.go
pkg/olm/olm.go
pkg/operator/operator.go
pkg/options/options.go
pkg/pvstore/pvstore.go
pkg/system/cmd_ui.go
pkg/system/system.go
pkg/version/version.go

Fixes #484
Use cobra args validations - https://github.com/spf13/cobra#positional-and-custom-arguments

Fix: "Generate an error if a user wrongly inputs options with –" 

---

pkg/diagnose/diagnose.go
pkg/util/util.go

Add capture of the following:
* Previous pod logs
* Output of "pod describe"
Fixes: #678
Sample run files captured:
BackingStoreList_crs.yaml
BucketClassList_crs.yaml
NooBaaList_crs.yaml
noobaa-core-0-core-previous.log
noobaa-core-0-core.log
noobaa-core-0-describe.txt
noobaa-db-pg-0-db-previous.log
noobaa-db-pg-0-db.log
noobaa-db-pg-0-describe.txt
noobaa-db-pg-0-init.log
noobaa-endpoint-77cc5fc5bd-gnvnd-describe.txt
noobaa-endpoint-77cc5fc5bd-gnvnd-endpoint.log
noobaa-operator-558d5d767b-dmfpv-describe.txt
noobaa-operator-558d5d767b-dmfpv-noobaa-operator-previous.log
noobaa-operator-558d5d767b-dmfpv-noobaa-operator.log

noobaa cli diagnose enhancements

---

pkg/system/phase4_configuring.go

Wait for the endpoint deployment to become ready
before creating the controlling HPA at phase4
Issue
====
See https://bugzilla.redhat.com/show_bug.cgi?id=1885524
Test
===
Run in parallel  `watch kubectl get deployment noobaa-endpoint` and  `noobaa install`. Verify that operator is waiting for the deployment to become ready before reconciling the HPA resource. Expected logs sample:
```
➜  kubectl logs -n noobaa noobaa-operator-558d5d767b-qh2nn      -f | grep "endpoint deployment"
time="2021-06-09T09:18:44Z" level=warning msg="⏳ Temporary Error: not enough available replicas in endpoint deployment" sys=noobaa/noobaa
time="2021-06-09T09:18:49Z" level=warning msg="⏳ Temporary Error: not enough available replicas in endpoint deployment" sys=noobaa/noobaa
time="2021-06-09T09:18:54Z" …
```

HPA: create after the deployment is ready

---

pkg/system/phase4_configuring.go

In order to avoid the removing existing mount points when namespacestore gets the rejected state,
ignore the state and try to configure the mounts.

Skip namespacestores with invalid configuration only

---

deploy/crds/noobaa.io_noobaas_crd.yaml
pkg/apis/noobaa/v1alpha1/noobaa_types.go
pkg/bundle/deploy.go
pkg/options/options.go
pkg/system/phase2_creating.go
pkg/system/system.go
test/cli/test_cli_functions.sh

Changing debug-level flag to get a preset option
Related to https://github.com/noobaa/noobaa-core/pull/6697

debug-level flag will get a preset option

---

pkg/diagnose/diagnose.go

- Diagnose will collect scc related to noobaa

Diagnose will collect scc related to noobaa

---

pkg/system/phase2_creating.go
pkg/system/system.go

(cherry picked from commit fa33919e1ba15f67430740763634aaeefa64b09b)

[Backport to 5.8] if dbtype is not provided try to infer it from the db image name

---

pkg/olm/olm.go
pkg/operator/operator.go

fix for https://bugzilla.redhat.com/show_bug.cgi?id=1991822

only set images envs for ODF CSV

---

doc/bucket-class-crd.md
doc/obc-provisioner.md

Add documentation to replication policy usage in bucketclass and OBC

---

pkg/system/phase2_creating.go
pkg/system/system.go

(cherry picked from commit fa33919e1ba15f67430740763634aaeefa64b09b)

[Backport to 5.7] if dbtype is not provided try to infer it from the db image name

---

pkg/system/phase4_configuring.go

Add disable SSL to RGW connection

---

.github/workflows/manual-build.yml

GH Action Add push to quay repo

GH Action Add push to quay repo

---

.github/workflows/manual-build.yml
Makefile
build/bundle/Dockerfile
build/bundle/annotations.yaml

* added `bundle-image` target to `Makefile`
* build and push bundle image in `manual-build.yml`

updated build action to build and push bundle image to quay

---

pkg/system/phase4_configuring.go

Add insecure transportation for creation bucket on RGW

---

pkg/bucket/bucket.go
pkg/bucketclass/bucketclass.go
test/cli/test_cli_flow.sh
test/cli/test_cli_functions.sh

- Changing the flow of the tests and adding some printings
- Fixed some typos
- Add data to a printing

Changing the flow of the tests

---

deploy/internal/prometheus-rules.yaml
pkg/bundle/deploy.go

Adding noobaa-odf.rules

---

deploy/internal/prometheus-rules.yaml
pkg/bundle/deploy.go

Update prom rules in operator

---

pkg/obc/provisioner.go
pkg/system/phase4_configuring.go

This reverts commit 95c959832067a30025dcf2a5961e1545f068fe77, reversing
changes made to 8ea58b6d218a6d3291f7d5499333f409fb743980.
1. 
1. 
1.

Revert "Merge pull request #792 from dannyzaken/danny-backport-5.8"

---

deploy/internal/admission-webhook.yaml
pkg/bundle/deploy.go
pkg/olm/olm.go

1. Generating our custom validation webhook configuration in the CSV.
2. This will trigger the OLM to generate the required resources to operate the webhook.
1. 
1.

Add webhook configuration to csv

---

pkg/nb/rpc_ws.go

- Implements WS ping heartbeat to improve server disconnect event
detection
- Add connect context timeout
1. 
1. 
1.

Websocket client - improve server disconnect detection

---

.github/workflows/run_admission_test.yml
Makefile
deploy/internal/admission-webhook.yaml
pkg/admission/server.go
pkg/admission/test/integ/admission_integ_test.go
pkg/admission/test/integ/admission_suite_integ_test.go
pkg/admission/test/unit/admission_suite_unit_test.go
pkg/admission/test/unit/admission_unit_test.go
pkg/admission/validate_backingstore.go
pkg/admission/validate_namespacestore.go
pkg/admission/validator.go
pkg/backingstore/reconciler.go
pkg/bundle/deploy.go
pkg/olm/olm.go
pkg/operator/manager.go
pkg/operator/operator.go
pkg/util/util.go

1. add admission webhook server.
2. add validation of CREATE/UPDATE/DELETE operations for BS/NS resources.
1. 
1. `ginkgo -v pkg/admission/test/integ`
2. `ginkgo -v pkg/admission/test/unit`

Add admission validation webhook server

---

README.md
pkg/bundle/deploy.go
version/version.go

Bump version to 5.10

---

pkg/options/options.go

updated ContainerImageTag for 5.9.0 release

---

pkg/nb/types.go
pkg/system/phase4_configuring.go

1. Add a custom `String()` for the `CreateSystemParams` struct to gain control on the printed values.
1. 
1.

Fix password logged in clear text

---

deploy/internal/deployment-endpoint.yaml
deploy/internal/statefulset-core.yaml
pkg/bundle/deploy.go

Fix for https://bugzilla.redhat.com/show_bug.cgi?id=2009650
1. Changing default CPU request/limit to 999m - due to issue with hyperthreading
1.  https://bugzilla.redhat.com/show_bug.cgi?id=2009650
1.

Changing default CPU request/limit to 999m

---

deploy/internal/deployment-endpoint.yaml
deploy/internal/statefulset-core.yaml
deploy/scc_endpoint.yaml
pkg/bundle/deploy.go
pkg/system/phase2_creating.go
pkg/system/phase4_configuring.go
version/version.go

1. Backport to 5.9 - NS FS Fixes only

Backport to 5.9 - NS FS Fixes only

---

.github/workflows/run_kms_ibm_kp_test.yml
pkg/util/kms/kms_ibm_kp_storage.go

KMS: Rename conf key IBM_KP_INSTANCE_ID -> IBM_KP_SERVICE_INSTANCE_ID per UI request
[KMS Test - IBM KP #70](https://github.com/baum/noobaa-operator/actions/runs/1718546381)
[KMS Test - IBM KP #71](https://github.com/baum/noobaa-operator/actions/runs/1722808323)

KMS: Rename conf key IBM_KP_INSTANCE_ID -> IBM_KP_SERVICE_INSTANCE_ID

---

deploy/crds/noobaa.io_noobaas_crd.yaml
deploy/internal/deployment-endpoint.yaml
deploy/internal/route-sts.yaml
deploy/internal/service-sts.yaml
pkg/apis/noobaa/v1alpha1/noobaa_types.go
pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
pkg/bundle/deploy.go
pkg/options/options.go
pkg/system/phase2_creating.go
pkg/system/phase3_connecting.go
pkg/system/reconciler.go
pkg/system/system.go

1. Added STS route and service.
1. 
1.

STS service and route addition

---

pkg/nb/api.go
pkg/nb/types.go
pkg/noobaaaccount/noobaaaccount.go
test/cli/test_cli_functions.sh

1. Add reset password to the account menu in the CLI
2. Added tests to test_cli_functions.sh
1. Fixing: [BZ 2027849](https://bugzilla.redhat.com/show_bug.cgi?id=2027849)
1. Reset a password.

Add reset password to the account menu in the CLI

---

.github/workflows/run_kms_ibm_kp_test.yml
pkg/admission/test/unit/admission_unit_test.go
pkg/admission/validate_backingstore.go
pkg/admission/validate_bucketclass.go
pkg/admission/validate_namespacestore.go
pkg/backingstore/backingstore.go
pkg/backingstore/reconciler.go
pkg/bucketclass/bucketclass.go
pkg/bucketclass/reconciler.go
pkg/namespacestore/namespacestore.go
pkg/namespacestore/reconciler.go
pkg/namespacestore/validation_test.go
pkg/nb/api.go
pkg/nb/types.go
pkg/noobaaaccount/noobaaaccount.go
pkg/util/kms/kms_ibm_kp_storage.go
pkg/validations/backingstore_validations.go
pkg/validations/bucketclass_validation.go
pkg/validations/namespacestore_validations.go
test/cli/test_cli_functions.sh

Backport to 5.10

---

pkg/util/util.go

fixing getAvailableKubeCli

---

pkg/obc/provisioner.go
test/cli/test_cli_flow.sh
test/cli/test_cli_functions.sh

- Fix r.OBC nil pointer dereference
-  https://bugzilla.redhat.com/show_bug.cgi?id=2038884

Fix r.OBC nil pointer dereference

---

deploy/internal/configmap-postgres-db.yaml
pkg/bundle/deploy.go

(cherry picked from commit 246d7c8510c6589d70f86141ee33284dc03d6c12)

Backport to 5.9: Increase postgres max connections

---

deploy/internal/admission-webhook.yaml
pkg/admission/validate_noobaaaccount.go
pkg/admission/validator.go
pkg/bundle/deploy.go
pkg/validations/noobaaaccount_validation.go

- Adding webhook to noobaaaccounts - nsfs config only

Adding webhook to noobaaaccounts - nsfs config only

---

pkg/admission/test/unit/admission_unit_test.go

- Adding NooBaaAccount admission unit tests
1. Run `ginkgo -v pkg/admission/test/unit`

Adding NooBaaAccount admission unit tests

---

build/install-operator-sdk.sh

Fix install-operator-sdk.sh PLATFORM

Fix install-operator-sdk.sh PLATFORM

---

.github/workflows/run_ci.yml
Makefile
test/cli/test_cli_flow.sh

- Divide the config map cli test to reduce CI run time

Divide the config map cli test to reduce CI run time

---

.github/workflows/run_ci.yml
Makefile
build/install-operator-sdk.sh
pkg/admission/test/unit/admission_unit_test.go
pkg/obc/obc.go
test/cli/test_cli_flow.sh

1. Add Regenerate S3 Credentials for OBC to the CLI
1. Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2027849

[Backport to 5.10] Add Regenerate S3 Credentials for OBC to the CLI

---

pkg/noobaaaccount/noobaaaccount.go
pkg/noobaaaccount/reconciler.go
test/cli/test_cli_functions.sh

- Fix noobaaaccount to be able to get also namespacestore as a resource
(cherry picked from commit 501816886236c0f7880af0c0f01732525a536f74)

[Backport to 5.10] Fix noobaaaccount to be able to get also namespacestore as a resource

---

pkg/system/azure_utils.go

1. 
1. fix https://bugzilla.redhat.com/show_bug.cgi?id=2029749
1.

[backport to 5.9] create azure StorageAccount with minTLS 1.2

---

pkg/backingstore/backingstore.go
pkg/backingstore/reconciler.go
test/cli/test_cli_flow.sh
test/cli/test_cli_functions.sh

(cherry picked from commit 25ef2bfd642dfd7e9e3ff1a3619449acaa8ac5db)
1. 
1. 
1.

[5.8 special backport] Allow definition of pv-pool backing store agent resources requests/limits

---

deploy/internal/route-s3.yaml
pkg/bundle/deploy.go

1. Backport to 5.8 special build - testing purposes

Backport to 5.8 special build

---

deploy/internal/route-s3.yaml
pkg/backingstore/backingstore.go
pkg/backingstore/reconciler.go
pkg/bundle/deploy.go
test/cli/test_cli_flow.sh
test/cli/test_cli_functions.sh

Backported the following changes:
1. https://github.com/noobaa/noobaa-operator/pull/751
2. https://github.com/noobaa/noobaa-operator/pull/879
1. 
1.

backport to 5.9

---

pkg/backingstore/reconciler.go
pkg/namespacestore/reconciler.go

1. fix misplaced error raising in load store secret after setting secret owner reference.
1. 
1.

Fix set ownerReference bug in load store secret

---

test/cli/test_cli_flow.sh
test/cli/test_cli_functions.sh

1. Fixed cli tests not running

Fixed cli tests not running

---

README.md
pkg/bundle/deploy.go
version/version.go

1. bumped version to 5.10.1
1. 
1.

[5.10] bumped version to 5.10.1

---

deploy/cluster_role.yaml
deploy/crds/noobaa.io_noobaas_crd.yaml
pkg/admission/validate_noobaa.go
pkg/apis/noobaa/v1alpha1/noobaa_types.go
pkg/backingstore/backingstore.go
pkg/bundle/deploy.go
pkg/install/install.go
pkg/namespacestore/namespacestore.go
pkg/operator/operator.go
pkg/system/phase4_configuring.go
pkg/system/system.go
pkg/util/util.go

Backport to 5.11

---

pkg/options/options.go

1. updated the reference to the core image to tag `5.10.1`
1. 
1.

[5.10] updated core image to 5.10.1

---

pkg/nb/types.go
pkg/obc/provisioner.go
pkg/options/options.go
pkg/util/util.go
test/cli/test_cli_functions.sh

1. add `LogBasedReplicationInfo` field to `BucketReplicationParams` for support in log based replication required information
2. dependent on https://github.com/noobaa/noobaa-core/pull/6937
1. 
1.

Log based replication params change

---

.travis/deploy-validate-vault.sh

Add a procedure to create noobaa service account token if it is missing

Create service account token if it is missing

---

README.md
pkg/bundle/deploy.go
version/version.go

Bump version to 5.12

---

deploy/internal/statefulset-postgres-db.yaml
pkg/bundle/deploy.go

1.  We need to set also collation for the initdb container in order to fix 2068110
1.  Fixed BZ2068110
1.

Fixing LC_COLLATE - operator side

---

pkg/admission/test/unit/admission_unit_test.go
pkg/admission/validate_noobaa.go
pkg/install/install.go
pkg/system/phase4_configuring.go
pkg/system/system.go
pkg/util/util.go
pkg/validations/noobaa_validation.go
test/cli/test_cli_functions.sh

1. Add a static webhook validation that checks if AllowNoobaaDeletion flag is turned.
2. Setting AllowNoobaaDeletion to true in the cli delete process.
1.

Add webhook validation on noobaa deletion

---

pkg/backingstore/backingstore.go
pkg/backingstore/reconciler.go
pkg/namespacestore/namespacestore.go
pkg/namespacestore/reconciler.go
pkg/util/util.go

(cherry picked from commit bc3152195011270f40a0f5140d80375816291a8b)
1. 
1. 
1.

Backport to 5.11: fix identical secrets

---

pkg/admission/test/unit/admission_unit_test.go
pkg/admission/validate_noobaa.go
pkg/install/install.go
pkg/system/phase4_configuring.go
pkg/system/system.go
pkg/util/util.go
pkg/validations/noobaa_validation.go
test/cli/test_cli_functions.sh

(cherry picked from commit 389f6f8cd9c345623c8adec011d7fce4b59e6863)
1. 
1.  related to https://bugzilla.redhat.com/show_bug.cgi?id=2088587
1.

[Backport to 5.11] Add webhook validation on noobaa deletion

---

pkg/system/phase2_creating.go

Signed-off-by: Evgeniy Belyi <jeniawhite92@gmail.com>
(cherry picked from commit bb34314602244f67380bc8a895bf12515d50ab88)
1. 
1. 
1.

Backport to 5.8: Addition of labels to reconcile after upgrade from last version

---

doc/namespace-store-crd.md

For namespace-store-crd.md links are broken
Signed-off-by: Sheetal Pamecha <spamecha@redhat.com>
1. 
1. 
1.

doc: correct 404 page not found error

---

pkg/system/system.go
pkg/util/util.go

Signed-off-by: nik-redhat <nladha@redhat.com>
1. Added a new util function `PrettyPrint` to print each item of a string array in newline if the length is more than 1.
1. Fixed #267

cli: Print on newline, if more than one value

---

pkg/system/reconciler.go
pkg/system/system.go

1. Init noobaa services pointer before populating their statuses.
1. 
1.

Init noobaa services before populating the status

---

deploy/internal/prometheus-rules.yaml
pkg/bundle/deploy.go

-------
Add metrics, `odf_system_objects_total` and `odf_system_bucket_count`.
1. 
1.

Add metrics, odf_system_objects_total and odf_system_bucket_count

---

deploy/internal/prometheus-rules.yaml
pkg/bundle/deploy.go

https://github.com/noobaa/noobaa-mixins/pull/30
-------
This commit removes the labels from,
- odf_system_bucket_count
- odf_system_objects_total
1. 
1.

remove the labels from odf_system object and bucket count

---

deploy/crds/noobaa.io_namespacestores_crd.yaml
pkg/apis/noobaa/v1alpha1/bucketclass_types.go
pkg/apis/noobaa/v1alpha1/namespacestore_types.go
pkg/bucketclass/bucketclass.go
pkg/bucketclass/reconciler.go
pkg/bundle/deploy.go
pkg/namespacestore/namespacestore.go
pkg/namespacestore/reconciler.go
pkg/nb/types.go
pkg/obc/provisioner.go
pkg/validations/bucketclass_validation.go

1. Add access mode field to namespacestore resource.
1. 
1.

Add access mode to namespacestore resource

---

deploy/internal/configmap-ca-inject.yaml
pkg/bundle/deploy.go
pkg/system/phase2_creating.go
pkg/system/phase4_configuring.go
pkg/system/reconciler.go

(cherry picked from commit f193d70b5d98fdc73a0d67da9ef797121409f6d5)
1. backport of https://github.com/noobaa/noobaa-operator/pull/977
1. 
1.

[backport to 5.11] support OCP injected CA

---

pkg/bundle/deploy.go
version/version.go

1. bumped version to 5.11.2
1. 
1.

[5.11] bumped version to 5.11.2

---

.travis/deploy-validate-vault.sh

(cherry picked from commit 9df8b07de486dd726c49d1f7512bf530572d77cf)
1. CI change only 
2. fixes KMS test
1. 
1.

[backport to 5.10] Add a procedure to create noobaa service account token if it is missing

---

deploy/internal/configmap-ca-inject.yaml
pkg/bundle/deploy.go
pkg/system/phase2_creating.go
pkg/system/phase4_configuring.go
pkg/system/reconciler.go

(cherry picked from commit f193d70b5d98fdc73a0d67da9ef797121409f6d5)
1. 
1. 
1.

[Backport to 5.10] support OCP injected CA

---

deploy/internal/deployment-endpoint.yaml
pkg/admission/test/integ/admission_integ_test.go
pkg/admission/test/unit/admission_unit_test.go
pkg/backingstore/reconciler.go
pkg/bundle/deploy.go
pkg/namespacestore/namespacestore.go
pkg/namespacestore/reconciler.go
pkg/util/util.go
pkg/validations/namespacestore_validations.go

1. Adding support for Namespace STS
2. Adding CLI for creating NS STS
3. Changing the validation to allow STS on NS

Support STS credentials for Namespace store

---

deploy/internal/deployment-endpoint.yaml
pkg/admission/test/integ/admission_integ_test.go
pkg/admission/test/unit/admission_unit_test.go
pkg/backingstore/reconciler.go
pkg/bundle/deploy.go
pkg/namespacestore/namespacestore.go
pkg/namespacestore/reconciler.go
pkg/util/util.go
pkg/validations/namespacestore_validations.go

Add create Namespace AWSSTSS3 to the cli
(cherry picked from commit 00587bb83f72faad369cff5920287ebf044d37ea)
1. 
1. 
1.

[Backport to 5.12] Add create Namespace AWSSTSS3 to the cli

---

pkg/bucket/bucket.go
pkg/bucketclass/bucketclass.go
pkg/bundler/bundler.go
pkg/cli/cli.go
pkg/operator/manager.go
pkg/system/phase2_creating.go
pkg/system/reconciler.go
pkg/util/util.go

(cherry picked from commit c7e76e54a01fe67ea40de17c3327ebd9ca0bb1ba)
1. [Backport to 5.12] Supporting warn level in operator

[Backport to 5.12] Supporting warn level in operator

---

deploy/olm/noobaa-operator.clusterserviceversion.yaml
pkg/bundle/deploy.go
pkg/olm/olm.go

Adding disconnected annotations to the CSV

Adding disconnected annotations to the CSV

---

deploy/olm/noobaa-operator.clusterserviceversion.yaml
pkg/bundle/deploy.go
pkg/olm/olm.go

Adding disconnected annotations to the CSV
(cherry picked from commit 407563c1fc7cf4ec127585d229304b6d3878de62)

[Backport to 5.12] Adding disconnected annotations to the CSV

---

doc/backing-store-crd.md

1. Updating the doc about the support to PV pool
1. -
1. -

Update in Backing Store CRD Documentation

---

README.md
pkg/bundle/deploy.go
version/version.go

Bump version to 5.13

---

.github/workflows/golangci-lint.yml
pkg/admission/validator.go
pkg/backingstore/backingstore.go
pkg/bundler/bundler.go
pkg/namespacestore/namespacestore.go
pkg/nb/rpc_http.go
pkg/nb/rpc_ws.go
pkg/olm/olm.go
pkg/system/phase4_configuring.go
pkg/util/kms/kms_vault.go
pkg/util/util.go

Fix for https://bugzilla.redhat.com/show_bug.cgi?id=2121353
(cherry picked from commit 41cbb87ebfe52dcd809cb5ae3e705b1cdceb8c0b)

[Backport to 5.11] Handle creating backingstore with the CLI and the "--secret-name" option.

---

README.md
pkg/bundle/deploy.go
version/version.go

This PR updates the NooBaa version to point to the next release version.

[5.8] Update version to 5.8.18

---

README.md
pkg/bundle/deploy.go
version/version.go

This PR updates the NooBaa version to point to the next release version.

[5.9] Update version to 5.9.14

---

README.md
pkg/bundle/deploy.go
version/version.go

This PR updates the NooBaa version to point to the next release version.

[5.10] Update version to 5.10.10

---

deploy/crds/noobaa.io_noobaas_crd.yaml
pkg/apis/noobaa/v1alpha1/noobaa_types.go
pkg/bundle/deploy.go
pkg/options/options.go
pkg/system/phase1_verifying.go
pkg/system/phase2_creating.go
pkg/system/phase4_configuring.go
pkg/system/system.go
test/cli/test_cli_flow.sh
test/cli/test_cli_functions.sh

…tBackingStoreSpec
Signed-off-by: Aayush Chouhan <achouhan@redhat.com>
1. deprecated `DefaultBackingStoreSpec`
2. Added flag `DisableDefaultBackingStore` to allow deletion of default backingstore.

Support feature to disable default backingstore

---

deploy/internal/deployment-endpoint.yaml
deploy/internal/statefulset-core.yaml
pkg/bundle/deploy.go
pkg/options/options.go
pkg/system/phase4_configuring.go

Mounting noobaa-auth-token secret into a file
mounting JWT_SECRET and SERVER_SECRET secret into a file
1.  Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2152143
- https://github.com/noobaa/noobaa-core/pull/7156

Mounting secrets into a file instead of secretKeyRef

---

.github/workflows/releaser.yaml
build/Dockerfile
build/tools/builder-pre.sh
build/tools/builder.sh
build/tools/releaser-post.sh
build/tools/releaser.sh
build/tools/utils.sh
pkg/util/kms/test/kmip/pykmip/Dockerfile

[5.12] Backport automated releaser

---

build/tools/builder-pre.sh
build/tools/utils.sh

This PR attempts to fix minor bugs in the releaser script.

Fix releaser... again

---

.travis/install-kmip-kms-noobaa.sh
build/tools/builder-pre.sh
build/tools/utils.sh

[5.12] Backport releaser fixes and KMIP fix

---

pkg/noobaaaccount/noobaaaccount.go
test/cli/test_cli_functions.sh

Signed-off-by: Aayush Chouhan <achouhan@redhat.com>
1.  Implemented a CLI command to update the default resource in noobaa account, that helps us in deletion of noobaa default backingstore.

Added CLI command to update noobaa account for default resource

---

pkg/util/util.go

1. Update AWS regions.
1. Update AWS regions.
1. none.

Fix Bug BZ 2183480 | Update AWS Regions

---

.github/workflows/golangci-lint.yml

github action: bump golangci lint version

---

deploy/internal/statefulset-db.yaml
deploy/internal/statefulset-postgres-db.yaml
deploy/scc_db.yaml
pkg/bundle/deploy.go
pkg/system/phase2_creating.go

```
remove ownership change init container
fix fsgroup
(cherry picked from commit a15e2e590734a57e30efe073bc4e0c9b8510aa91)
```

[Backport to 5.13] remove ownership change init container

---

deploy/operator.yaml
pkg/bundle/deploy.go

(cherry picked from commit 2628d3cbff25774b59a5f7895d8db020d082d34b)

[Backport 5.12] add security context to NooBaa operator pod

---

.github/workflows/golangci-lint.yml
.github/workflows/run_admission_test.yml
.github/workflows/run_ci.yml
.github/workflows/run_hac_test.yml
.github/workflows/run_kms_dev_test.yml
.github/workflows/run_kms_ibm_kp_test.yml
.github/workflows/run_kms_tls_sa_test.yml
.github/workflows/run_kms_tls_token_test.yml
.github/workflows/testing.yml
pkg/util/util.go

[Backport to 5.10] Update AWS regions

---

pkg/system/phase2_creating.go
pkg/system/reconciler.go

1. moved the code to after we reconcile the noobaa-config config map, before it was always empty
1. Fixed BZ#1932846
1.

Fixing issue with operator log level

---

pkg/system/phase2_creating.go
pkg/system/reconciler.go

(cherry picked from commit 03a98466ecc9610a7048d83ed1d33ef0b388292e)
1. 
1. 
1.

[backport to 5.13] Fixing log set location in the operator

---

deploy/internal/prometheus-rules.yaml
pkg/bundle/deploy.go

Aligning description for NooBaaBucketExceedingQuantityQuotaState and NooBaaBucketReachingQuantityQuotaState with the description in mixins

Description changed

---

deploy/internal/prometheus-rules.yaml
pkg/bundle/deploy.go

This got introduced in https://github.com/noobaa/noobaa-operator/pull/1125/files and removing it through this comment

Remove unwanted character "\" from the description

---

deploy/internal/prometheus-rules.yaml
pkg/bundle/deploy.go

1. backported PRs
1. https://github.com/noobaa/noobaa-operator/pull/1117
2. https://github.com/noobaa/noobaa-operator/pull/1125
1.  BZ https://github.com/noobaa/noobaa-operator/pull/1117
1.

[Backport to 5.13] - Adding quantity quota alerts

---

pkg/nb/api.go
pkg/nb/types.go

1. fix incorrect function ListAccountsAPI(): add missing parameters
1. https://github.com/noobaa/noobaa-operator/issues/872
1.

Fix incorrect function ListAccountsAPI()

---

README.md
pkg/bundle/deploy.go
version/version.go

bumped version to 5.14.0

---

Makefile
build/gen-odf-package.sh
pkg/options/options.go

COSI | Enable downstream cosi side car image replacement

---

doc/cosi-provisioner.md
pkg/apis/noobaa/v1alpha1/cosi_types.go
pkg/cosi/cosi.go
pkg/cosi/cosi_access_class.go
pkg/cosi/cosi_bucket_access.go
pkg/cosi/cosi_bucket_claim.go
pkg/cosi/cosi_bucket_class.go
pkg/cosi/cosi_cli_test.go

1. Added cosi bucket access and bucket access class commands to noobaa cli.
2. Supported create, list, status and delete for both COSI bucket access and bucke access tclass
3. Added to COSI types
4. Updated docs
5. Added cli integration tests
1.

COSI | CLI | Bucket Access Class & Bucket Access implementation

---

doc/cosi-provisioner.md
pkg/apis/noobaa/v1alpha1/cosi_types.go
pkg/cosi/cosi.go
pkg/cosi/cosi_access_class.go
pkg/cosi/cosi_bucket_access.go
pkg/cosi/cosi_bucket_claim.go
pkg/cosi/cosi_bucket_class.go
pkg/cosi/cosi_cli_test.go

Signed-off-by: Romy <35330373+romayalon@users.noreply.github.com>
(cherry picked from commit c52a2a556ed67be1baf1d835285656d5b9d8dd69)
1. 
1. 
1.

[backport to 5.14] bucket access class impl

---

README.md

With releases being made from new releaser scripts, the asset structure has changed. The PR reflects those changes in the README.

[Chore] Update install instructions for NooBaa

---

.github/workflows/manual-build.yml
.github/workflows/run_admission_test.yml
.github/workflows/run_ci.yml
.github/workflows/run_cosi_test.yaml
.github/workflows/run_hac_test.yml
.github/workflows/run_kms_dev_test.yml
.github/workflows/run_kms_ibm_kp_test.yml
.github/workflows/run_kms_kmip_test.yml
.github/workflows/run_kms_rotate_test.yml
.github/workflows/run_kms_tls_sa_test.yml
.github/workflows/run_kms_tls_token_test.yml
.github/workflows/testing.yml
go.mod
pkg/cli/cli.go

update go version to 1.20 from 1.19

update go version

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.13] Bump version to 5.13.1

---

.github/workflows/run_admission_test.yml
README.md
pkg/bundle/deploy.go
version/version.go

[5.13] Bump version to 5.13.2

---

pkg/nb/router.go

Signed-off-by: Aayush Chouhan <aayush.chouhan97@gmail.com>
(cherry picked from commit 0f3dd04f29952dbe87b357653c8ac4ab6f6fb2f3)
1. rebased https://github.com/noobaa/noobaa-operator/pull/1203 
1. 
1.

[backport to 5.14] Fixed noobaa CLI api calls to object_api

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.13] Bump version to 5.13.3

---

pkg/cosi/cosi_bucket_claim.go
pkg/cosi/provisioner.go
pkg/cosi/validation.go
pkg/obc/obc.go
pkg/obc/provisioner.go
pkg/obc/validation.go
pkg/validations/common_bucket_validation_integ_test.go
pkg/validations/common_bucket_validations.go

Signed-off-by: Romy <35330373+romayalon@users.noreply.github.com>
(cherry picked from commit 1691b443fed869d2d4c36d35a064c8ff660b1632)
1. https://bugzilla.redhat.com/show_bug.cgi?id=2231709

[Backport to 4.14] fix obc with replication cli creation and validation

---

README.md
pkg/bundle/deploy.go
version/version.go

Bump version to 5.15

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.13] Bump version to 5.13.4

---

pkg/cli/cli.go
pkg/crd/crd.go
pkg/install/install.go
pkg/operator/operator.go
pkg/system/system.go

1. Implement the ability to upgrade the product from the CLI

Implement upgrade via CLI

---

doc/external-postgres.md

Update documentation with SSL

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.13] Bump version to 5.13.5

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.14] Bump version from 5.14.0 to 5.14.1

[5.14] Bump version from 5.14.0 to 5.14.1

---

doc/backing-store-crd.md

1. Update backingstore doc related to AWS STS.
1. none
1. none

Doc | Update Backingstore Doc Related to AWS STS

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.14] Bumping the version from 5.14.1 to 5.14.2

[5.14] Bumping the version from 5.14.1 to 5.14.2

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.14] Bumping the version from 5.14.2 to 5.14.3

[5.14] Bumping the version from 5.14.2 to 5.14.3

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.13] Bump version to 5.13.6

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.12] Bump version to 5.12.11

[5.12] Bump version to 5.12.11

---

doc/dev_guide/create_aws_sts_setup_on_minikube.md

1.  Create AWS STS setup on minikube (for developers), based on @ezio-auditore steps.
1. none
1. none

Doc | Create AWS STS Setup on Minikube Dev Guide

---

.github/workflows/golangci-lint.yml
.github/workflows/run_ci.yml
pkg/noobaaaccount/noobaaaccount.go
pkg/obc/obc.go

1. Backported #1230 and #1231
1. https://bugzilla.redhat.com/show_bug.cgi?id=2246877
1.

[Backport to 5.12] Bug Fix BZ 2242414

---

Makefile
build/gen-odf-package.sh
deploy/crds/noobaa.io_noobaas.yaml
deploy/internal/configmap-postgres-initdb.yaml
pkg/apis/noobaa/v1alpha1/noobaa_types.go
pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
pkg/bundle/deploy.go
pkg/olm/olm.go
pkg/options/options.go
pkg/system/phase2_creating.go

[Backport to 5.15] Add upgrade process for postgres DB version 15

---

pkg/bucket/bucket.go

Added command line parameters
1. --max-size
2. --max-objects
to noobaa command to set/update quota on a bucket

Set quota directly on a bucket

---

pkg/apis/noobaa/v1alpha1/noobaaaccount_types.go
pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
pkg/bucket/bucket.go
pkg/nb/types.go
pkg/noobaaaccount/noobaaaccount.go
pkg/noobaaaccount/reconciler.go

1. CLI additions:
2. `force_md5_etag` on account - #1241 
3. set quota on bucket - #1252 
1. 
1.

[5.15] - CLI Additions 

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.13] Bump version to 5.13.7

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.14] Bumping version from 5.14.3 to 5.14.4

[5.14] Bumping version from 5.14.3 to 5.14.4

---

pkg/backingstore/backingstore.go
pkg/backingstore/reconciler.go

Remove upgradeBackingStore
1.  Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2255586
2. Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2258681
3. Fixes: https://github.com/noobaa/noobaa-operator/issues/1282

Remove upgradeBackingStore

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.14] Bumping the version from 5.14.4 to 5.14.5

[5.14] Bumping the version from 5.14.4 to 5.14.5

---

.github/workflows/run_cosi_test.yaml
deploy/operator.yaml
pkg/bundle/deploy.go
pkg/controller/add_cosi.go
pkg/operator/operator.go

1. Moving COSI temporarily out of the code - currently moved to comments
1. 
1.

Moving COSI temporarily out of the code

---

pkg/backingstore/backingstore.go
pkg/backingstore/reconciler.go

Remove upgradeBackingStore
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2260851
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2260331
(cherry picked from commit 448a5c67392e6b6ab65ada4266fe0c4805e748a6)

[Backport into 5.14] Remove upgradeBackingStore

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.13] Bump version to 5.13.8

---

doc/external-postgres.md

Update external-postgres.md - 'c' should be the correct one

---

doc/dev_guide/troubleshoot_sts_cluster.md

1. Add a case in the guide TroubleShoot AWS STS Cluster.
1. none
1. none

Doc | Add a Case in the Guide Troubleshoot AWS STS Cluster

---

README.md

1. Update readme flags:
- Update flags (added `psql-12-image`).
- Remove redundant a newline.
- Add missing s in `--test-env` description.
1. none
1. none

Doc | Update Readme Flags

---

pkg/system/phase4_configuring.go

1. Remove the certificate fix just for GCP as it was causing reflection errors (See #1312 for more info).
1. https://bugzilla.redhat.com/show_bug.cgi?id=2267857
1.

Partial revert of #1304

---

pkg/system/phase4_configuring.go

1. Remove the certificate fix just for GCP as it was causing reflection errors (See #1312 for more info).
1. https://bugzilla.redhat.com/show_bug.cgi?id=2267857
1.

[BACKPORT 5.15] Partial revert of #1304

---

.github/workflows/golangci-lint.yml
README.md
pkg/bundle/deploy.go
version/version.go

[5.14] Bumping the version from 5.14.5 to 5.14.6

[5.14] Bumping the version from 5.14.5 to 5.14.6

---

pkg/system/phase2_creating.go

(cherry picked from commit 3247ac803e77787f775223df028da897fe0b96f1)
1. Backported https://github.com/noobaa/noobaa-operator/pull/1319
1. 
1.

[Backport to 5.15] fixing returned status and adding prints

---

deploy/crds/noobaa.io_noobaas.yaml
deploy/internal/service-syslog.yaml
deploy/internal/statefulset-core.yaml
pkg/apis/noobaa/v1alpha1/noobaa_types.go
pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
pkg/bundle/deploy.go
pkg/options/options.go
pkg/system/phase2_creating.go
pkg/system/system.go

Adding a sidecar container which will run rsyslod and logrotate It will also be running a log segregate script.

bucket_logging: Bucket log processing in side car container

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.15] Bumping version from 5.15.0 to 5.15.1

[5.15] Bumping version from 5.15.0 to 5.15.1

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.14] Bumping version from 5.14.6 to 5.14.7

 [5.14] Bumping version from 5.14.6 to 5.14.7

---

README.md
pkg/bundle/deploy.go
version/version.go

Bump version to 5.17.0

---

.github/workflows/golangci-lint.yml
README.md
pkg/bundle/deploy.go
version/version.go

[5.13] Bump version to 5.13.9

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.15] Bumping version from 5.15.1 to 5.15.2

[5.15] Bumping version from 5.15.1 to 5.15.2

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.16] Fixing the version to be 5.16.0

[5.16] Fixing the version to be 5.16.0

---

deploy/internal/pod-agent.yaml
pkg/bundle/deploy.go

1. Changing default CPU/Memory request from 100m/400Mi to 999m/1Gi
1. Fixed https://bugzilla.redhat.com/show_bug.cgi?id=2272664
1.

Fix default resource request/limit for PV pool pods

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.15] Bump version to 5.15.3

---

deploy/internal/pod-agent.yaml
deploy/internal/statefulset-postgres-db.yaml
deploy/role.yaml
deploy/scc.yaml
deploy/scc_db.yaml
deploy/scc_endpoint.yaml
pkg/bundle/deploy.go

include pod agent change
make gen-api
update deploy.go
address PR comments
(cherry picked from commit 76d4722eafa80d492599495cd5e05e34a41ef294)
1. 
1. 
1.

[Backport | 5.15] SCC fixes

---

pkg/cosi/provisioner.go
pkg/nb/types.go
pkg/noobaaaccount/noobaaaccount.go
pkg/noobaaaccount/reconciler.go
pkg/obc/obc.go
pkg/obc/provisioner.go
pkg/system/phase4_configuring.go

Fixed AccessKeys printings on RPC calls
Fixes: https://github.com/noobaa/noobaa-operator/issues/1358

Fixed AccessKeys printings on RPC calls

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.14] Bumping version from 5.14.7 to 5.14.8

[5.14] Bumping version from 5.14.7 to 5.14.8

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.14] Bumping version from 5.14.8 to 5.14.9

[5.14] Bumping version from 5.14.8 to 5.14.9

---

deploy/internal/nsfs-pvc-cr.yaml
pkg/bundle/deploy.go

Change accessmode from ReadWriteOnce to ReadWriteMany

Modify nsfs default pvc yaml file

---

deploy/internal/pod-agent.yaml
deploy/internal/statefulset-postgres-db.yaml
deploy/role.yaml
deploy/scc.yaml
deploy/scc_db.yaml
deploy/scc_endpoint.yaml
pkg/bundle/deploy.go

Backport SCC fixes related commits to 5.14

[Backport | 5.14] SCC fixes

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.15] Bump version to 5.15.4

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.14] Bumping version from 5.14.9 to 5.14.10

[5.14] Bumping version from 5.14.9 to 5.14.10

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.16] Bumping version from 5.16.0 to 5.16.1

[5.16] Bumping version from 5.16.0 to 5.16.1

---

Makefile
build/gen-odf-package.sh
pkg/olm/olm.go
pkg/options/options.go
pkg/system/phase2_creating.go
pkg/system/reconciler.go
pkg/system/system.go

Backport of PR - #1396 
(cherry picked from commit 992d39bfafd516138dc3fe70a12f40e51f4a4805)

[Backport 5.16] Added a workaround for postgres upgrade failures

---

deploy/internal/pod-agent.yaml
pkg/backingstore/reconciler.go
pkg/bundle/deploy.go
pkg/controller/backingstore/backingstore_controller.go

- Add NOOBAA_LOG_LEVEL to the agent pod
- Watching for changes in the noobaa-config on the backingstore reconciler
- Updating the NOOBAA_LOG_LEVEL according to the config map
- Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2297448

Add NOOBAA_LOG_LEVEL to the agent pod

---

README.md
pkg/bundle/deploy.go
version/version.go

Bump version to 5.18.0

---

deploy/internal/statefulset-core.yaml
deploy/role_core.yaml
deploy/scc_core.yaml
pkg/bundle/deploy.go
pkg/system/phase2_creating.go

1. Using the same SCC as the DB doesn't work - we should create a special SCC for core.
1. 
1.

SCC fixes - new SCC for core

---

doc/dev_guide/create_aws_role.sh
doc/dev_guide/troubleshoot_sts_cluster.md

1. Update docs related to STS:
- Add comment about OIDC configuration in ROSA HCP.
- Add step when the ARN is invalid in a cluster.
1. Was raised as a part of [BZ 2302350](https://bugzilla.redhat.com/show_bug.cgi?id=2302350)
1. None

Docs | STS | Update Docs

---

.github/workflows/manual-build.yml
.github/workflows/releaser.yaml
.github/workflows/run_admission_test.yml
.github/workflows/run_ci.yml
.github/workflows/run_cosi_test.yaml
.github/workflows/run_hac_test.yml
.github/workflows/run_kms_azure_vault_test.yml
.github/workflows/run_kms_dev_test.yml
.github/workflows/run_kms_ibm_kp_test.yml
.github/workflows/run_kms_kmip_test.yml
.github/workflows/run_kms_rotate_test.yml
.github/workflows/run_kms_tls_sa_test.yml
.github/workflows/run_kms_tls_token_test.yml
.github/workflows/testing.yml

- actions/setup-go from v4 (or v2) to v5
- actions/upload-artifact from v3 to v4
Fixes: https://github.com/noobaa/noobaa-operator/issues/1031

Update GH actions

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.15] Bumping version from 5.15.6 to 5.15.7

[5.15] Bumping version from 5.15.6 to 5.15.7

---

deploy/role_binding_core.yaml
deploy/role_core.yaml
pkg/bundle/deploy.go
pkg/operator/operator.go
pkg/system/phase2_creating.go

1. We changed in the yaml but not in the reconciler - now suppose to work
2. because of the wrong serviceAccount - core was running with anyuid SCC instead of noobaa-core.
1. https://bugzilla.redhat.com/show_bug.cgi?id=2309700
1.

Fix serviceAccount for noobaa-core

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.14] Bumping version from 5.14.10 to 5.14.11

[5.14] Bumping version from 5.14.10 to 5.14.11

---

deploy/internal/route-s3.yaml
pkg/bundle/deploy.go

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2271776
(cherry picked from commit b710fd7629197c43bdf19c05c7f9fe0a0bc185df)

[Backport into 5.14] adding disable_cookies annotation

---

.github/workflows/run_cosi_test.yaml
deploy/operator.yaml
pkg/bundle/deploy.go
pkg/controller/add_cosi.go
pkg/operator/operator.go

(cherry picked from commit aa38ce08587ca9d76a357813334b6e6665301a9f)

[Backport into 5.14] Moving COSI temporarily out of the code

---

pkg/backingstore/backingstore.go
pkg/install/install.go
pkg/namespacestore/namespacestore.go
pkg/noobaaaccount/noobaaaccount.go
pkg/obc/obc.go

Fixing the CLI decision error handling to avoid lint errors

Fixing the CLI decision error handling to avoid lint errors

---

deploy/role_binding_core.yaml
pkg/bundle/deploy.go

(cherry picked from commit 6a82a2d23ad3c450c9d0e8da2b292e67cdd78f47)
1. 
1. 
1.

[Backport 5.17] Remove hardcoded namespace from rolebinding

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.16] Bumping version from 5.16.2 to 5.16.3

[5.16] Bumping version from 5.16.2 to 5.16.3

---

pkg/bucket/bucket.go

1. Currently, bucket quota is not working as expected it is failing to update quota when we pass max-size in other then bytes format. We have added a validation check for the quota and applied some fixes to work with any format of max-size.
1. Improvement: #1252 
1. Update the bucket quota using various formats (Gi, Ti etc.) and verify the quota is correctly reflected in binary format using cli commands.
2. Test invalid formats to ensure the system returns an error and does not update the quota.

Added a validation check for quota config in bucket

---

pkg/system/phase2_creating.go

1. use service url with namespace for POSTGRES_HOST to fix for GKE
1. Fixes #432
1. Deploy in GKE

Fix #432 POSTGRES_HOST use service url with namespace

---

pkg/obc/provisioner.go

1. Removed semicolon from statement
2. Removed extra spaces
1. 
1.

Minor lint fixes

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.15] Bumping version from 5.15.7 to 5.15.8

[5.15] Bumping version from 5.15.7 to 5.15.8

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.14] Bumping version from 5.14.11 to 5.14.12

[5.14] Bumping version from 5.14.11 to 5.14.12

---

deploy/internal/configmap-ca-inject.yaml
deploy/operator.yaml
pkg/bundle/deploy.go
pkg/olm/olm.go
pkg/system/azure_utils.go
pkg/system/phase2_creating.go
pkg/system/phase4_configuring.go
pkg/util/util.go

1. Backport #1328 to 5.15
https://bugzilla.redhat.com/show_bug.cgi?id=2271580

[Backport to 5.15] Modify the handling of injected OCP CA bundles

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.17] Bumping version from 5.17.0 to 5.17.1

[5.17] Bumping version from 5.17.0 to 5.17.1

---

.github/workflows/golangci-lint.yml
.golangci.yml
Makefile
pkg/backingstore/backingstore.go
pkg/bucketclass/bucketclass.go
pkg/cosi/provisioner.go
pkg/install/install.go
pkg/namespacestore/namespacestore.go
pkg/nb/rpc_ws.go
pkg/noobaaaccount/noobaaaccount.go
pkg/obc/obc.go
pkg/obc/provisioner.go
pkg/system/reconciler.go
pkg/util/kms/test/dev/kms_dev_test.go
pkg/util/kms/test/ibm-kp/kms_ibm_kp_test.go

1. [Backport into 5.16] CI | Fixing deprecated linter

[Backport into 5.16] CI | Fixing deprecated linter

---

README.md
deploy/cluster_role.yaml
doc/bucket-types.md
pkg/bundle/deploy.go
pkg/util/util.go
test/cli/test_cli_functions.sh

1. Bug-fix for fetching region from AWS cluster obj in GetAWSRegion()
1. https://issues.redhat.com/browse/DFBUGS-747

[Backport into 5.18] Bug-fix for fetching region from AWS cluster obj in GetAWSRegion()

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.16] Bumping version from 5.16.4 to 5.16.5

[5.16] Bumping version from 5.16.4 to 5.16.5

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.17] Bumping version from 5.17.1 to 5.17.2

---

.github/workflows/golangci-lint.yml
.golangci.yml
Makefile
README.md
pkg/backingstore/backingstore.go
pkg/bucketclass/bucketclass.go
pkg/bundle/deploy.go
pkg/cosi/provisioner.go
pkg/install/install.go
pkg/namespacestore/namespacestore.go
pkg/nb/rpc_ws.go
pkg/noobaaaccount/noobaaaccount.go
pkg/obc/obc.go
pkg/obc/provisioner.go
pkg/system/reconciler.go
pkg/util/kms/test/dev/kms_dev_test.go
pkg/util/kms/test/ibm-kp/kms_ibm_kp_test.go
version/version.go

[5.15] Bumping version from 5.15.9 to 5.15.10

[5.15] Bumping version from 5.15.9 to 5.15.10

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.16] Bumping version from 5.16.5 to 5.16.6

[5.16] Bumping version from 5.16.5 to 5.16.6

---

README.md
pkg/bundle/deploy.go
version/version.go

Bump version to 5.19.0

---

Makefile
README.md
pkg/bundle/deploy.go
version/version.go

[5.17] Bumping version from 5.17.2 to 5.17.4

[5.17] Bumping version from 5.17.2 to 5.17.4

---

.github/workflows/manual-build.yml
.github/workflows/releaser.yaml
.github/workflows/run_admission_test.yml
.github/workflows/run_ci.yml
.github/workflows/run_cosi_test.yaml
.github/workflows/run_hac_test.yml
.github/workflows/run_kms_azure_vault_test.yml
.github/workflows/run_kms_dev_test.yml
.github/workflows/run_kms_ibm_kp_test.yml
.github/workflows/run_kms_kmip_test.yml
.github/workflows/run_kms_rotate_test.yml
.github/workflows/run_kms_tls_sa_test.yml
.github/workflows/run_kms_tls_token_test.yml
.github/workflows/testing.yml
Makefile
README.md
pkg/bundle/deploy.go
version/version.go

[5.16] Bumping version from 5.16.6 to 5.16.7

[5.16] Bumping version from 5.16.6 to 5.16.7

---

.github/workflows/releaser.yaml
.github/workflows/run_admission_test.yml
.github/workflows/run_cosi_test.yaml
Makefile
README.md
pkg/bundle/deploy.go
version/version.go

[5.15] Bumping version from 5.15.10 to 5.15.11

[5.15] Bumping version from 5.15.10 to 5.15.11

---

README.md
pkg/bundle/deploy.go
pkg/system/phase4_configuring.go
version/version.go

[5.17] Bumping version from 5.17.4 to 5.17.5

[5.17] Bumping version from 5.17.4 to 5.17.5

---

pkg/system/phase4_configuring.go

(cherry picked from commit 9d900da25c310a925bb422f77cb0d10faedc7926)

[Backport into 5.18] fixed lint error

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.17] Bumping version from 5.17.5 to 5.17.6

[5.17] Bumping version from 5.17.5 to 5.17.6

---

build/gen-odf-package.sh
pkg/cnpg/cnpg.go
pkg/olm/olm.go

- Added the deployment's label in the generated CSV
- Minimizing the modifications in the cnpg yamls. Replacing the full API version (postgresql.cnpg.io) instead of the top-level (cnpg.io)
1. 
1.

CNPG fixes for ODF build

---

build/gen-odf-package.sh

1. uncommented the flag `--cnpg-image`
1. 
1.

fix to gen-odf-package.sh

---

deploy/cluster_role.yaml
pkg/bucket/bucket.go
pkg/bundle/deploy.go
pkg/util/util.go

1. Fix for region fetch from GetAWSRegion()
2. Added a validation check for quota config in bucket and some code fixes
1. https://issues.redhat.com/browse/DFBUGS-1370
2. https://issues.redhat.com/browse/DFBUGS-1282

[Backport into 5.17] Bug fixes for parsed AWS region and quota always result 1PB quota limit

---

deploy/cluster_role.yaml
pkg/bundle/deploy.go
pkg/util/util.go

Signed-off-by: Aayush Chouhan <achouhan@redhat.com>
(cherry picked from commit 00c3d880883475260c49a951947082d5b799f6a6)
1. https://issues.redhat.com/browse/DFBUGS-1417

[Backport into 5.16] Fix for region fetch from GetAWSRegion()

---

pkg/system/phase2_creating.go
pkg/util/kms/kms_version.go
pkg/util/kms/test/rotate/kms_rotate_test.go
pkg/util/kms/test/rotate/kms_rotate_unit_test.go

1. Will mount keys from the last 6 months - minimum keys set to 50.
1. Fixed https://issues.redhat.com/browse/DFBUGS-1344
1.

Fixing mount volume root keys - limit the secret size

---

README.md
pkg/bundle/deploy.go
pkg/system/phase4_configuring.go
version/version.go

[5.15] Bumping version from 5.15.11 to 5.15.13

[5.15] Bumping version from 5.15.11 to 5.15.13

---

README.md
pkg/bundle/deploy.go
pkg/system/phase4_configuring.go
version/version.go

[5.14] Bumping version from 5.14.15 to 5.14.17

[5.14] Bumping version from 5.14.15 to 5.14.17

---

pkg/olm/olm.go

1. CNPG Webhooks were missing from the  CSV, which prevented the CNPG pod from starting.
1. 
1.

Added CNPG webhooks definitions to CSV

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.18] Bumping version from 5.18.0 to 5.18.1

[5.18] Bumping version from 5.18.0 to 5.18.1

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.18] Bumping version from 5.18.1 to 5.18.2

[5.18] Bumping version from 5.18.1 to 5.18.2

---

.github/workflows/run_cnpg_deployment_test.yml
deploy/crds/noobaa.io_noobaas.yaml
pkg/apis/noobaa/v1alpha1/noobaa_types.go
pkg/apis/noobaa/v1alpha1/zz_generated.deepcopy.go
pkg/bundle/deploy.go
pkg/cnpg/cnpg.go
pkg/install/install.go
pkg/system/db_reconciler.go
pkg/system/system.go
pkg/util/util.go

- added support for node affinity and tolerations
- added PostgreSQL config values to cluster spec
- Added `dbConf` field to `dbSpec` to allow overriding default parameters
- Wait for noobaa-operator and cnpg-operator to be ready before creating a system. 
1. 
1.

Cluster reconcile changes

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.16] Bumping version from 5.16.9 to 5.16.10

[5.16] Bumping version from 5.16.9 to 5.16.10

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.15] Bumping version from 5.15.13 to 5.15.14

[5.15] Bumping version from 5.15.13 to 5.15.14

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.17] Bumping version from 5.17.7 to 5.17.7

[5.17] Bumping version from 5.17.7 to 5.17.7

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.14] Bumping version from 5.14.17 to 5.14.18

[5.14] Bumping version from 5.14.17 to 5.14.18

---

pkg/admission/test/unit/admission_unit_test.go
pkg/validations/namespacestore_validations.go

1. Bocke NSS creation  SigVersion v4 and endpoint non-secure from openshift console using yaml
1. https://github.com/noobaa/noobaa-operator/issues/1586
1.  go test ./pkg/admission/test/unit/

Webhook block NSS creation when SigVersion v4 and endpoint non-secure

---

pkg/util/kms/kms_azure.go
pkg/util/kms/test/azure-vault/kms_azure_vault_test.go

Support key rotation to Azure vault

---

pkg/util/kms/kms_azure.go
pkg/util/kms/test/azure-vault/kms_azure_vault_test.go

(cherry picked from commit 205c23410697f1ec4d153004745e66d9619ba32f)
1. 
1. 
1.

[5.19 Backport] Support key rotation to Azure vault

---

.github/workflows/run_admission_test.yml

1. Update run_admission_test.yml to use native github action minikube

Update run_admission_test.yml to use native github action minikube

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.18] Bumping version from 5.18.2 to 5.18.3

[5.18] Bumping version from 5.18.2 to 5.18.3

---

.github/workflows/cli-tests.yml
.github/workflows/core-config-map-tests.yml
.github/workflows/run_admission_test.yml

Update setup-minikube from v0.0.14 to v0.0.19 and kubernetes-version to v1.33.0

Update setup-minikube from v0.0.14 to v0.0.19 and kubernetes-version to v1.33.0

---

pkg/bucket/bucket.go
pkg/nb/types.go
pkg/noobaaaccount/noobaaaccount.go
pkg/noobaaaccount/reconciler.go
pkg/util/util.go

1. [Backport into 5.16] Fix for quota always result 1PB quota limit
1. https://issues.redhat.com/browse/DFBUGS-2572

[Backport into 5.16] Fix for quota always result 1PB quota limit

---

pkg/util/kms/kms_kmip.go
pkg/util/kms/kms_kmip_storage.go
pkg/util/kms/kms_version.go
pkg/util/kms/test/kmip/kms_kmip_test.go

(cherry picked from commit ae7408d1d02ad2ba1e331834b22c546dd689d1e3)
1. 
1. 
1.

[5.19 Backport] Support key rotation for KMIP KMS

---

.github/workflows/core-config-map-tests.yml
pkg/bundle/deploy.go
version/version.go

[5.14] Bumping version from 5.14.19 to 5.14.20

[5.14] Bumping version from 5.14.19 to 5.14.20

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.19] Bumping version from 5.19.0 to 5.19.1

[5.19] Bumping version from 5.19.0 to 5.19.1

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.14] Bumping version from 5.14.20 to 5.14.21

[5.14] Bumping version from 5.14.20 to 5.14.21

---

pkg/system/db_reconciler.go

Change the kubecheck of standaloneDBPod to be quiet
1. https://issues.redhat.com/browse/DFBUGS-2869

Change the kubecheck of standaloneDBPod to be quiet

---

README.md
pkg/bundle/deploy.go
version/version.go

[5.19] Bumping version from 5.19.4 to 5.19.6

[5.19] Bumping version from 5.19.4 to 5.19.6
